
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE 0
#define PARTNER_STEVEN 1
#define PARTNER_RIVAL_MALE 2
#define PARTNER_RIVAL_FEMALE 3
#define PARTNER_SHARPY 4
#define PARTNER_CAMELIA 5
#define PARTNER_NORMAN 6
#define PARTNER_LANETTE 7
#define PARTNER_COUNT 8

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
