#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_BALSAM,
    SP_NAME_AIDEE,
    SP_NAME_BIRCH,
    SP_NAME_RIVAL,
    SP_NAME_RICK,
    SP_NAME_SHARPY,
    SP_NAME_CAMELIA,

    SP_NAME_JOEL,
    SP_NAME_ANNE,
    SP_NAME_SAMANTHA,
    SP_NAME_KIRA,
    SP_NAME_DAN,
    SP_NAME_HERMIT,
    SP_NAME_JIMMY,
    SP_NAME_IVAN,
    SP_NAME_DYSTOPIAN,
    SP_NAME_DRAMAACTOR,
    SP_NAME_DRAMAACTRESS,
    SP_NAME_SUPERSUBSTITUTE,
    SP_NAME_SWAGGY,
    SP_NAME_GABBY,
    SP_NAME_GLACIA,

    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
