gText_Birch_Welcome::
	.string "Well well, I thought you'd never call.\n"
	.string "Welcome back to society, soldier!\p"
	.string "No one's heard from you since you came\n"
	.string "back from the war. Was about time!\p"
	.string "You've been shut in so long, I bet you\n"
	.string "don't know what has happened in Hoenn.\p"
	.string "Let me give you a crash course.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This sorry thing here is a “Safemon”-\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "After the war with Kanto, Devon Co. and\n"
	.string "Silph Co. signed a peace treaty....\p"
	.string "Which mandated all Pokémon in Hoenn to\n"
	.string "be made weaker. Safer. Hence the name.\p"
	.string "It was to prevent them from being used\n"
	.string "as weapons in another war.\p"
	.string "The project has only begun, but in\n"
	.string "time, every Pokémon will be “safened”.\p"
	.string "Some say that it's cruel, that these\n"
	.string "companies are going too far...\p"
	.string "But I wouldn't say that out loud, if I\n"
	.string "were you.\p"
	.string "Not unless you want people to think\n"
	.string "you are a Rebel. That's trouble.\p"
	.string "Speaking of trouble, your ID expired\n"
	.string "after all this time.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "So I need your info to renew it.\p"
	.string "$"
gText_Birch_BoyOrGirl::
	.string "Send me a picture of you."
	.string "$"

gText_Birch_WhatsYourName::
	.string "Wow, you look terrible!\p"
	.string "Okay, I need a name as well.$"

gText_Birch_SoItsPlayer::
	.string "What did you say? {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Got it. That's one less thing...\p"
	.string "Who am I? Oh, I guess you wanted to\n"
	.string "talk to your grandpa, Professor Birch.\p"
	.string "Well, he's retired now. I'm Professor\n"
	.string "Balsam, the new Littleroot Lab lead.\p"
	.string "Professor Birch asked me to take care\n"
	.string "of you if you reached out.\p"
	.string "At least until you get used to society\n"
	.string "again. Which I hope is soon.\p"
	.string "$"

gText_Birch_AreYouReady::

	.string "Well {PLAYER}, it’s been a lovely chat...\p"
	.string "But I have some work to do.\p"
	.string "Drop by the lab tomorrow, and we’ll talk\n"
	.string "some more, alright?\p"
	.string "See you soon, soldier!\p"
	.string "$"