gText_Birch_Welcome::
	.string "Well well, I thought you'd never call.\n"
	.string "Welcome back to society, soldier!\p"
	.string "You haven't left home since coming\n"
	.string "back from the war. Was about time!\p"
	.string "You've been in there so long, I bet you\n"
	.string "don't know what has happened in Hoenn.\p"
	.string "Let me give you a crash course.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This sorry thing here is a “SAFEMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "After the war with Kanto, Devon Corp.\n"
	.string "and Silph.Co signed a peace treaty....\p"
	.string "Which stated that all Pokémon in both\n"
	.string "regions should be turned into weaker\l"
	.string "versions of themselves - SAFEMON.\p"
	.string "It was to prevent them from being used\n"
	.string "as weapons in another war.\p"
	.string "Some say that it's cruel, that these\n"
	.string "companies are going too far...\p"
	.string "But I wouldn't say that out loud, if I\n"
	.string "were you.\p"
	.string "Not unless you want people to think\n"
	.string "you are a REBEL. That's trouble.\p"
	.string "Speaking of trouble, your ID expired\n"
	.string "after all this time.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "So I need your info to fill a new one.\p"
	.string "$"
gText_Birch_BoyOrGirl::
	.string "Send me a picture of you."
	.string "$"

gText_Birch_WhatsYourName::
	.string "Wow, you look terrible!\p"
	.string "Oh, I need a name as well.$"

gText_Birch_SoItsPlayer::
	.string "What did you say? {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Got it. I'll send your ID for you to\n"
	.string "print. Don't leave home without it.\p"
	.string "Who am I? I'm Professor Balsam, the new\n"
	.string "lead of Littleroot's Pokémon lab.\p"
	.string "If it wasn't obvious, I've been tasked\n"
	.string "with babysitting you for a while.\p"
	.string "At least until you get used to society\n"
	.string "again. Which I hope is soon.\p"
	.string "$"

gText_Birch_AreYouReady::

	.string "Well {PLAYER}, it’s been a lovely chat...\p"
	.string "But I’ve got some stuff to do.\p"
	.string "Drop by the lab tomorrow, and we’ll talk\n"
	.string "some more, alright?\p"
	.string "See you soon, soldier!\p"
	.string "$"