gBirchDexRatingText_AreYouCurious::
	.string "AIDE: Oh hey {PLAYER}!\p"
	.string "I guess you want to check your\n"
	.string "Devon Dex progress.\p"
	.string "Let me get into your profile\n"
	.string "real quick. Hmm...$"

gBirchDexRatingText_Cancel::
	.string "Uhm... it seems you have\n"
	.string "barely registered any data\l"
	.string "since I gave you the dex.\p"
	.string "It's okay to take your time,\n"
	.string "but I'd really appreciate some\l"
	.string "results here!\p"
	.string "If we don't, we're going to get\n"
	.string "it from Balsam... and I'm sure\l"
	.string "neither of us want that.\p"
	.string "So try hitting a Devon Mart,\n"
	.string "get some Devon Balls, and start\l"
	.string "catching! Counting on you!$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Pokémon Visual Data:{STR_VAR_1} species.\n"
	.string "Pokémon Acquired Data: {STR_VAR_2} species.$"

gBirchDexRatingText_LessThan10::
	.string "... you're not allergic to tall\n"
	.string "grass, are you {PLAYER}?.\l"
	.string "Ahaha, just kidding! I have your!\n"
	.string "medical records here, I know you aren't!\p"
	.string "No, but seriously - I'm sure there's\n"
	.string "more Pokémon between the lab and\l"
	.string "Oldale than what you've caught.\p"
	.string "Check Littleroot's Cemetery, the\n"
	.string "Great Crater - oh, and the\l"
	.string "tunnel by the lab's basement.\p"
	.string "You'll pump those numbers up\n"
	.string "in no time. Good luck!.$"

gBirchDexRatingText_LessThan20::
	.string "Well, it's a modest start, but it's\n"
	.string "a start nonetheless!\p"
	.string "Hey, have you checked Oldale's\n"
	.string "Warehouse?\p"
	.string "When the Rebels took over it, many\n"
	.string "Pokémon who were used for work\l"
	.string "there broke free in the chaos.\p"
	.string "I hear there's many of them left.\l"
	.string "You're welcome for the info!$"

gBirchDexRatingText_LessThan30::
	.string "Yould have registered more\n"
	.string "data in all this time...\p"
	.string "But hey, I know you've been\n"
	.string "busy doing other stuff!\p"
	.string "Do you have a fishing rod?\p"
	.string "Hoenn is drier now than\n"
	.string "before the war, but you can\l"
	.string "still fish many species.\p"
	.string "So get on reeling!$"

gBirchDexRatingText_LessThan40::
	.string "Well, your dex is starting to\n"
	.string "take shape now!\p"
	.string "Hey, remember to try and turn\n"
	.string "Safemon back into Pokémon.\p"
	.string "If you do that, you can\n"
	.string "get 2 dex entries per catch.\p"
	.string "As I say - work smarter, not\n"
	.string "harder! Keep at it!$"

gBirchDexRatingText_LessThan50::
	.string "That's a lot of species, but...\n"
	.string "my estimates indicate there's\l"
	.string "still many more in Hoenn now!\p"
	.string "Have you hit the Rebel Arcade?\n"
	.string "They have some unique Pokémon\l"
	.string "there listed as prizes.\p"
	.string "Not the most ethical thing,\n"
	.string "but it's the times we live in!\p"
	.string "Plus, playing videogames is a$"
	.string "fun way to collect. Start gaming!$"

gBirchDexRatingText_LessThan60::
	.string "Wowie, you've surpassed the 50\n"
	.string "mark! That's a milestone!\p"
	.string "Hey, Professor - do you have\n"
	.string "any words of encouragement\l"
	.string "for {PLAYER} here?\p"
	.string "PROF. BALSAM: ... good job.\n"
	.string "Keep it up.\p"
	.string "AIDE: Ahaha... bit succint, but\n"
	.string "that's the Professor for you!\p"
	.string "Between you and me... she's\n"
	.string "more impressed than she lets on.\p"
	.string "PROF. BALSAM: Stop chit-chatting.\n"
	.string "and get back to work!\p"
	.string "AIDE: Oops, I've said too much...\n"
	.string "Till the next report, {PLAYER}$"

gBirchDexRatingText_LessThan70::
	.string "Instead of just catching POKéMON,\n"
	.string "how about making them evolve, too?$"

gBirchDexRatingText_LessThan80::
	.string "This is going to be a fantastic\n"
	.string "POKéDEX.\l"
	.string "That's the feeling I'm getting.$"

gBirchDexRatingText_LessThan90::
	.string "You've collected this many…\n"
	.string "Your talent is remarkable!$"

gBirchDexRatingText_LessThan100::
	.string "Have you visited the SAFARI ZONE?\p"
	.string "I hear there are some POKéMON that\n"
	.string "can only be caught there.$"

gBirchDexRatingText_LessThan110::
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "This is an impressive POKéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "There might be POKéMON that can be\n"
	.string "found using ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "You should get some more POKéMON\n"
	.string "by trading with others.$"

gBirchDexRatingText_LessThan140::
	.string "I've heard of POKéMON that evolve\n"
	.string "when they come to fully love their\l"
	.string "TRAINERS.$"

gBirchDexRatingText_LessThan150::
	.string "I had no idea that there were so\n"
	.string "many POKéMON species in the HOENN\l"
	.string "region.$"

gBirchDexRatingText_LessThan160::
	.string "On occasion, some POKéMON appear\n"
	.string "in large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"

gBirchDexRatingText_LessThan170::
	.string "One can get a very good idea about\n"
	.string "the POKéMON of the HOENN region\l"
	.string "by looking through your POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "I would say you already qualify as\n"
	.string "a POKéMON PROFESSOR, and a good\l"
	.string "one, too!$"

gBirchDexRatingText_LessThan190::
	.string "With a POKéDEX this complete,\n"
	.string "you're a real professional at this!$"

gBirchDexRatingText_LessThan200::
	.string "You're very close to completing\n"
	.string "this POKéDEX.\l"
	.string "I can feel it in my bones!$"

gBirchDexRatingText_DexCompleted::
	.string "Congratulations!\n"
	.string "Your POKéDEX is complete!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've caught {STR_VAR_2} POKéMON…$"
