# 1 "data/maps/Route104Lighthouse_2/scripts.pory"


Route104Lighthouse_2_MapScripts::
# 6 "data/maps/Route104Lighthouse_2/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, DayNightMusicRoute104
# 7 "data/maps/Route104Lighthouse_2/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, DayNightMusicRoute104
# 8 "data/maps/Route104Lighthouse_2/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, DayNightMusicRoute104
	.byte 0

