# 1 "data/maps/OldaleWarehouseColdStorage/scripts.pory"


OldaleWarehouseColdStorage_MapScripts::
# 6 "data/maps/OldaleWarehouseColdStorage/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, DayNightAmbientLight
# 7 "data/maps/OldaleWarehouseColdStorage/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, DayNightAmbientLight
# 8 "data/maps/OldaleWarehouseColdStorage/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, DayNightAmbientLight
	.byte 0

