# 1 "data/maps/LittlerootTown/scripts.pory"

# 2 "data/maps/LittlerootTown/scripts.pory"

# 3 "data/maps/LittlerootTown/scripts.pory"
# 1 "data/maps/LittlerootTown/scripts.pory"
# 4 "data/maps/LittlerootTown/scripts.pory"

# 5 "data/maps/LittlerootTown/scripts.pory"
# 2 "data/maps/LittlerootTown/scripts.pory"
# 6 "data/maps/LittlerootTown/scripts.pory"

# 7 "data/maps/LittlerootTown/scripts.pory"
# 3 "data/maps/LittlerootTown/scripts.pory"
# 8 "data/maps/LittlerootTown/scripts.pory"
# 8 "data/maps/LittlerootTown/scripts.pory"
# 9 "data/maps/LittlerootTown/scripts.pory"

# 10 "data/maps/LittlerootTown/scripts.pory"
# 9 "data/maps/LittlerootTown/scripts.pory"
# 11 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_TOWN_STATE
# 12 "data/maps/LittlerootTown/scripts.pory"
# 10 "data/maps/LittlerootTown/scripts.pory"
# 13 "data/maps/LittlerootTown/scripts.pory"
	@ 1: Met Rival
# 14 "data/maps/LittlerootTown/scripts.pory"
# 11 "data/maps/LittlerootTown/scripts.pory"
# 15 "data/maps/LittlerootTown/scripts.pory"
	@ 2: Saving Birch
# 16 "data/maps/LittlerootTown/scripts.pory"
# 12 "data/maps/LittlerootTown/scripts.pory"
# 17 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Received Pokedex
# 18 "data/maps/LittlerootTown/scripts.pory"
# 13 "data/maps/LittlerootTown/scripts.pory"
# 19 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Received Running Shoes
# 20 "data/maps/LittlerootTown/scripts.pory"
# 14 "data/maps/LittlerootTown/scripts.pory"
# 21 "data/maps/LittlerootTown/scripts.pory"

# 22 "data/maps/LittlerootTown/scripts.pory"
# 15 "data/maps/LittlerootTown/scripts.pory"
# 23 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_INTRO_STATE
# 24 "data/maps/LittlerootTown/scripts.pory"
# 16 "data/maps/LittlerootTown/scripts.pory"
# 25 "data/maps/LittlerootTown/scripts.pory"
	@ 1: In truck male
# 26 "data/maps/LittlerootTown/scripts.pory"
# 17 "data/maps/LittlerootTown/scripts.pory"
# 27 "data/maps/LittlerootTown/scripts.pory"
	@ 2: In truck female
# 28 "data/maps/LittlerootTown/scripts.pory"
# 18 "data/maps/LittlerootTown/scripts.pory"
# 29 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Entered house
# 30 "data/maps/LittlerootTown/scripts.pory"
# 19 "data/maps/LittlerootTown/scripts.pory"
# 31 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Told to go set clock
# 32 "data/maps/LittlerootTown/scripts.pory"
# 20 "data/maps/LittlerootTown/scripts.pory"
# 33 "data/maps/LittlerootTown/scripts.pory"
	@ 5: Entered 2F to set clock
# 34 "data/maps/LittlerootTown/scripts.pory"
# 21 "data/maps/LittlerootTown/scripts.pory"
# 35 "data/maps/LittlerootTown/scripts.pory"
	@ 6: Set clock
# 36 "data/maps/LittlerootTown/scripts.pory"
# 22 "data/maps/LittlerootTown/scripts.pory"
# 37 "data/maps/LittlerootTown/scripts.pory"
	@ 7: Told to go meet rival
# 38 "data/maps/LittlerootTown/scripts.pory"
# 23 "data/maps/LittlerootTown/scripts.pory"
# 39 "data/maps/LittlerootTown/scripts.pory"

# 40 "data/maps/LittlerootTown/scripts.pory"
# 24 "data/maps/LittlerootTown/scripts.pory"
# 41 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_HOUSES_STATE_MAY
# 42 "data/maps/LittlerootTown/scripts.pory"
# 25 "data/maps/LittlerootTown/scripts.pory"
# 43 "data/maps/LittlerootTown/scripts.pory"
	@                    and VAR_LITTLEROOT_HOUSES_STATE_BRENDAN
# 44 "data/maps/LittlerootTown/scripts.pory"
# 26 "data/maps/LittlerootTown/scripts.pory"
# 45 "data/maps/LittlerootTown/scripts.pory"
	@ 1: On Truck (and is corresponding gender)
# 46 "data/maps/LittlerootTown/scripts.pory"
# 27 "data/maps/LittlerootTown/scripts.pory"
# 47 "data/maps/LittlerootTown/scripts.pory"
	@ 2: Met Rival's Mom (and is corresponding gender)
# 48 "data/maps/LittlerootTown/scripts.pory"
# 28 "data/maps/LittlerootTown/scripts.pory"
# 49 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Entered Hall of Fame
# 50 "data/maps/LittlerootTown/scripts.pory"
# 29 "data/maps/LittlerootTown/scripts.pory"
# 51 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Completed Lati TV / SS Ticket event
# 52 "data/maps/LittlerootTown/scripts.pory"
# 30 "data/maps/LittlerootTown/scripts.pory"
# 53 "data/maps/LittlerootTown/scripts.pory"
	@ 5: Exited house after above event
# 54 "data/maps/LittlerootTown/scripts.pory"
# 31 "data/maps/LittlerootTown/scripts.pory"
# 55 "data/maps/LittlerootTown/scripts.pory"

# 56 "data/maps/LittlerootTown/scripts.pory"
# 32 "data/maps/LittlerootTown/scripts.pory"
# 57 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_RIVAL_STATE
# 58 "data/maps/LittlerootTown/scripts.pory"
# 33 "data/maps/LittlerootTown/scripts.pory"
# 59 "data/maps/LittlerootTown/scripts.pory"
	@ 1: Never occurs
# 60 "data/maps/LittlerootTown/scripts.pory"
# 34 "data/maps/LittlerootTown/scripts.pory"
# 61 "data/maps/LittlerootTown/scripts.pory"
	@ 2: Entered Rival's bedroom
# 62 "data/maps/LittlerootTown/scripts.pory"
# 35 "data/maps/LittlerootTown/scripts.pory"
# 63 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Met Rival
# 64 "data/maps/LittlerootTown/scripts.pory"
# 36 "data/maps/LittlerootTown/scripts.pory"
# 65 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Received Pokedex
# 66 "data/maps/LittlerootTown/scripts.pory"
# 37 "data/maps/LittlerootTown/scripts.pory"
# 67 "data/maps/LittlerootTown/scripts.pory"

# 68 "data/maps/LittlerootTown/scripts.pory"
# 38 "data/maps/LittlerootTown/scripts.pory"
# 69 "data/maps/LittlerootTown/scripts.pory"

# 70 "data/maps/LittlerootTown/scripts.pory"
# 39 "data/maps/LittlerootTown/scripts.pory"
# 71 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_OnTransition:
# 72 "data/maps/LittlerootTown/scripts.pory"
# 40 "data/maps/LittlerootTown/scripts.pory"
# 73 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_VISITED_LITTLEROOT_TOWN
# 74 "data/maps/LittlerootTown/scripts.pory"
# 41 "data/maps/LittlerootTown/scripts.pory"
# 75 "data/maps/LittlerootTown/scripts.pory"
	call Common_EventScript_SetupRivalGfxId
# 76 "data/maps/LittlerootTown/scripts.pory"
# 42 "data/maps/LittlerootTown/scripts.pory"
# 77 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_INTRO_STATE, 2, LittlerootTown_EventScript_MoveMomToMaysDoor
# 78 "data/maps/LittlerootTown/scripts.pory"
# 43 "data/maps/LittlerootTown/scripts.pory"
# 79 "data/maps/LittlerootTown/scripts.pory"
# 44 "data/maps/LittlerootTown/scripts.pory"
# 80 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_TOWN_STATE, 3, LittlerootTown_EventScript_SetMomStandingInFrontOfDoorPos
# 81 "data/maps/LittlerootTown/scripts.pory"
# 45 "data/maps/LittlerootTown/scripts.pory"
# 82 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_HOUSES_STATE_MAY, 4, LittlerootTown_EventScript_SetExitedHouseAfterLatiSSTicketEvent
# 83 "data/maps/LittlerootTown/scripts.pory"
# 46 "data/maps/LittlerootTown/scripts.pory"
# 84 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_HOUSES_STATE_BRENDAN, 4, LittlerootTown_EventScript_SetExitedHouseAfterLatiSSTicketEvent
# 85 "data/maps/LittlerootTown/scripts.pory"
# 47 "data/maps/LittlerootTown/scripts.pory"
# 86 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_OLDALE_RIVAL_STATE, 1, LittlerootTown_EventScript_MoveRivalFromOldale
# 87 "data/maps/LittlerootTown/scripts.pory"
# 48 "data/maps/LittlerootTown/scripts.pory"
# 88 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_RIVAL_STATE, 3, LittlerootTown_EventScript_SetRivalLeftForRoute103
# 89 "data/maps/LittlerootTown/scripts.pory"
# 49 "data/maps/LittlerootTown/scripts.pory"
# 90 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 1, LittlerootTown_EventScript_HideMapNamePopup
# 91 "data/maps/LittlerootTown/scripts.pory"
# 50 "data/maps/LittlerootTown/scripts.pory"
# 92 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 2, LittlerootTown_EventScript_LeftLabAfterDexUpgrade
# 93 "data/maps/LittlerootTown/scripts.pory"
# 51 "data/maps/LittlerootTown/scripts.pory"
# 94 "data/maps/LittlerootTown/scripts.pory"
	end
# 95 "data/maps/LittlerootTown/scripts.pory"
# 52 "data/maps/LittlerootTown/scripts.pory"
# 96 "data/maps/LittlerootTown/scripts.pory"

# 97 "data/maps/LittlerootTown/scripts.pory"
# 53 "data/maps/LittlerootTown/scripts.pory"
# 98 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_LeftLabAfterDexUpgrade::
# 99 "data/maps/LittlerootTown/scripts.pory"
# 54 "data/maps/LittlerootTown/scripts.pory"
# 100 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 3
# 101 "data/maps/LittlerootTown/scripts.pory"
# 55 "data/maps/LittlerootTown/scripts.pory"
# 102 "data/maps/LittlerootTown/scripts.pory"
	return
# 103 "data/maps/LittlerootTown/scripts.pory"
# 56 "data/maps/LittlerootTown/scripts.pory"
# 104 "data/maps/LittlerootTown/scripts.pory"

# 105 "data/maps/LittlerootTown/scripts.pory"
# 57 "data/maps/LittlerootTown/scripts.pory"
# 106 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_HideMapNamePopup::
# 107 "data/maps/LittlerootTown/scripts.pory"
# 58 "data/maps/LittlerootTown/scripts.pory"
# 108 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_MAP_NAME_POPUP
# 109 "data/maps/LittlerootTown/scripts.pory"
# 59 "data/maps/LittlerootTown/scripts.pory"
# 110 "data/maps/LittlerootTown/scripts.pory"
	return
# 111 "data/maps/LittlerootTown/scripts.pory"
# 60 "data/maps/LittlerootTown/scripts.pory"
# 112 "data/maps/LittlerootTown/scripts.pory"

# 113 "data/maps/LittlerootTown/scripts.pory"
# 61 "data/maps/LittlerootTown/scripts.pory"
# 114 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalLeftForRoute103::
# 115 "data/maps/LittlerootTown/scripts.pory"
# 62 "data/maps/LittlerootTown/scripts.pory"
# 116 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_RIVAL_LEFT_FOR_ROUTE103
# 117 "data/maps/LittlerootTown/scripts.pory"
# 63 "data/maps/LittlerootTown/scripts.pory"
# 118 "data/maps/LittlerootTown/scripts.pory"
	return
# 119 "data/maps/LittlerootTown/scripts.pory"
# 64 "data/maps/LittlerootTown/scripts.pory"
# 120 "data/maps/LittlerootTown/scripts.pory"

# 121 "data/maps/LittlerootTown/scripts.pory"
# 65 "data/maps/LittlerootTown/scripts.pory"
# 122 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MoveRivalFromOldale::
# 123 "data/maps/LittlerootTown/scripts.pory"
# 66 "data/maps/LittlerootTown/scripts.pory"
# 124 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_OLDALE_RIVAL_STATE, 2
# 125 "data/maps/LittlerootTown/scripts.pory"
# 67 "data/maps/LittlerootTown/scripts.pory"
# 126 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_OLDALE_TOWN_RIVAL
# 127 "data/maps/LittlerootTown/scripts.pory"
# 68 "data/maps/LittlerootTown/scripts.pory"
# 128 "data/maps/LittlerootTown/scripts.pory"
	return
# 129 "data/maps/LittlerootTown/scripts.pory"
# 69 "data/maps/LittlerootTown/scripts.pory"
# 130 "data/maps/LittlerootTown/scripts.pory"

# 131 "data/maps/LittlerootTown/scripts.pory"
# 70 "data/maps/LittlerootTown/scripts.pory"
# 132 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetExitedHouseAfterLatiSSTicketEvent::
# 133 "data/maps/LittlerootTown/scripts.pory"
# 71 "data/maps/LittlerootTown/scripts.pory"
# 134 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_HOUSES_STATE_MAY, 5
# 135 "data/maps/LittlerootTown/scripts.pory"
# 72 "data/maps/LittlerootTown/scripts.pory"
# 136 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_HOUSES_STATE_BRENDAN, 5
# 137 "data/maps/LittlerootTown/scripts.pory"
# 73 "data/maps/LittlerootTown/scripts.pory"
# 138 "data/maps/LittlerootTown/scripts.pory"
	return
# 139 "data/maps/LittlerootTown/scripts.pory"
# 74 "data/maps/LittlerootTown/scripts.pory"
# 140 "data/maps/LittlerootTown/scripts.pory"

# 141 "data/maps/LittlerootTown/scripts.pory"
# 75 "data/maps/LittlerootTown/scripts.pory"
# 142 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MoveMomToMaysDoor::
# 143 "data/maps/LittlerootTown/scripts.pory"
	return
# 144 "data/maps/LittlerootTown/scripts.pory"
# 78 "data/maps/LittlerootTown/scripts.pory"
# 145 "data/maps/LittlerootTown/scripts.pory"

# 146 "data/maps/LittlerootTown/scripts.pory"
# 79 "data/maps/LittlerootTown/scripts.pory"
# 147 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetTwinPos::
# 148 "data/maps/LittlerootTown/scripts.pory"
# 80 "data/maps/LittlerootTown/scripts.pory"
# 149 "data/maps/LittlerootTown/scripts.pory"
	goto_if_eq VAR_LITTLEROOT_TOWN_STATE, 0, LittlerootTown_EventScript_SetTwinGuardingRoutePos
# 150 "data/maps/LittlerootTown/scripts.pory"
	return
# 151 "data/maps/LittlerootTown/scripts.pory"
# 84 "data/maps/LittlerootTown/scripts.pory"
# 152 "data/maps/LittlerootTown/scripts.pory"

# 153 "data/maps/LittlerootTown/scripts.pory"
# 85 "data/maps/LittlerootTown/scripts.pory"
# 154 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetTwinGuardingRoutePos::
# 155 "data/maps/LittlerootTown/scripts.pory"
	return
# 156 "data/maps/LittlerootTown/scripts.pory"
# 89 "data/maps/LittlerootTown/scripts.pory"
# 157 "data/maps/LittlerootTown/scripts.pory"

# 158 "data/maps/LittlerootTown/scripts.pory"
# 90 "data/maps/LittlerootTown/scripts.pory"
# 159 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetMomStandingInFrontOfDoorPos::
# 160 "data/maps/LittlerootTown/scripts.pory"
# 91 "data/maps/LittlerootTown/scripts.pory"
# 161 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE
# 162 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 163 "data/maps/LittlerootTown/scripts.pory"
# 94 "data/maps/LittlerootTown/scripts.pory"
# 164 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetMomInFrontOfDoorMale
# 165 "data/maps/LittlerootTown/scripts.pory"
# 95 "data/maps/LittlerootTown/scripts.pory"
# 166 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_SetMomInFrontOfDoorFemale
# 167 "data/maps/LittlerootTown/scripts.pory"
# 96 "data/maps/LittlerootTown/scripts.pory"
# 168 "data/maps/LittlerootTown/scripts.pory"
	return
# 169 "data/maps/LittlerootTown/scripts.pory"
# 97 "data/maps/LittlerootTown/scripts.pory"
# 170 "data/maps/LittlerootTown/scripts.pory"

# 171 "data/maps/LittlerootTown/scripts.pory"
# 98 "data/maps/LittlerootTown/scripts.pory"
# 172 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetMomInFrontOfDoorMale::
# 173 "data/maps/LittlerootTown/scripts.pory"
	return
# 174 "data/maps/LittlerootTown/scripts.pory"
# 101 "data/maps/LittlerootTown/scripts.pory"
# 175 "data/maps/LittlerootTown/scripts.pory"

# 176 "data/maps/LittlerootTown/scripts.pory"
# 102 "data/maps/LittlerootTown/scripts.pory"
# 177 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetMomInFrontOfDoorFemale::
# 178 "data/maps/LittlerootTown/scripts.pory"
	return
# 179 "data/maps/LittlerootTown/scripts.pory"
# 105 "data/maps/LittlerootTown/scripts.pory"
# 180 "data/maps/LittlerootTown/scripts.pory"

# 181 "data/maps/LittlerootTown/scripts.pory"
# 106 "data/maps/LittlerootTown/scripts.pory"
# 182 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_OnFrame:
# 183 "data/maps/LittlerootTown/scripts.pory"
# 107 "data/maps/LittlerootTown/scripts.pory"
# 184 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_LITTLEROOT_INTRO_STATE, 1, LittlerootTown_EventScript_StepOffTruckMale
# 185 "data/maps/LittlerootTown/scripts.pory"
# 108 "data/maps/LittlerootTown/scripts.pory"
# 186 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_LITTLEROOT_INTRO_STATE, 2, LittlerootTown_EventScript_StepOffTruckFemale
# 187 "data/maps/LittlerootTown/scripts.pory"
# 109 "data/maps/LittlerootTown/scripts.pory"
# 188 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 1, LittlerootTown_EventScript_BeginDexUpgradeScene
# 189 "data/maps/LittlerootTown/scripts.pory"
# 110 "data/maps/LittlerootTown/scripts.pory"
# 190 "data/maps/LittlerootTown/scripts.pory"
	.2byte 0
# 191 "data/maps/LittlerootTown/scripts.pory"
# 111 "data/maps/LittlerootTown/scripts.pory"
# 192 "data/maps/LittlerootTown/scripts.pory"

# 193 "data/maps/LittlerootTown/scripts.pory"
# 112 "data/maps/LittlerootTown/scripts.pory"
# 194 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_StepOffTruckMale::
# 195 "data/maps/LittlerootTown/scripts.pory"
# 113 "data/maps/LittlerootTown/scripts.pory"
# 196 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 197 "data/maps/LittlerootTown/scripts.pory"
# 114 "data/maps/LittlerootTown/scripts.pory"
# 198 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8004, 5
# 199 "data/maps/LittlerootTown/scripts.pory"
# 115 "data/maps/LittlerootTown/scripts.pory"
# 200 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8005, 8
# 201 "data/maps/LittlerootTown/scripts.pory"
# 116 "data/maps/LittlerootTown/scripts.pory"
# 202 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GoInsideWithMom
# 203 "data/maps/LittlerootTown/scripts.pory"
# 117 "data/maps/LittlerootTown/scripts.pory"
# 204 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_TRUCK
# 205 "data/maps/LittlerootTown/scripts.pory"
# 118 "data/maps/LittlerootTown/scripts.pory"
# 206 "data/maps/LittlerootTown/scripts.pory"
	warpsilent MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F, 8, 8
# 207 "data/maps/LittlerootTown/scripts.pory"
# 119 "data/maps/LittlerootTown/scripts.pory"
# 208 "data/maps/LittlerootTown/scripts.pory"
	waitstate
# 209 "data/maps/LittlerootTown/scripts.pory"
# 120 "data/maps/LittlerootTown/scripts.pory"
# 210 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 211 "data/maps/LittlerootTown/scripts.pory"
# 121 "data/maps/LittlerootTown/scripts.pory"
# 212 "data/maps/LittlerootTown/scripts.pory"
	end
# 213 "data/maps/LittlerootTown/scripts.pory"
# 122 "data/maps/LittlerootTown/scripts.pory"
# 214 "data/maps/LittlerootTown/scripts.pory"

# 215 "data/maps/LittlerootTown/scripts.pory"
# 123 "data/maps/LittlerootTown/scripts.pory"
# 216 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_StepOffTruckFemale::
# 217 "data/maps/LittlerootTown/scripts.pory"
# 124 "data/maps/LittlerootTown/scripts.pory"
# 218 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 219 "data/maps/LittlerootTown/scripts.pory"
# 125 "data/maps/LittlerootTown/scripts.pory"
# 220 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8004, 14
# 221 "data/maps/LittlerootTown/scripts.pory"
# 126 "data/maps/LittlerootTown/scripts.pory"
# 222 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8005, 8
# 223 "data/maps/LittlerootTown/scripts.pory"
# 127 "data/maps/LittlerootTown/scripts.pory"
# 224 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GoInsideWithMom
# 225 "data/maps/LittlerootTown/scripts.pory"
# 128 "data/maps/LittlerootTown/scripts.pory"
# 226 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_TRUCK
# 227 "data/maps/LittlerootTown/scripts.pory"
# 129 "data/maps/LittlerootTown/scripts.pory"
# 228 "data/maps/LittlerootTown/scripts.pory"
	warpsilent MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F, 2, 8
# 229 "data/maps/LittlerootTown/scripts.pory"
# 130 "data/maps/LittlerootTown/scripts.pory"
# 230 "data/maps/LittlerootTown/scripts.pory"
	waitstate
# 231 "data/maps/LittlerootTown/scripts.pory"
# 131 "data/maps/LittlerootTown/scripts.pory"
# 232 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 233 "data/maps/LittlerootTown/scripts.pory"
# 132 "data/maps/LittlerootTown/scripts.pory"
# 234 "data/maps/LittlerootTown/scripts.pory"
	end
# 235 "data/maps/LittlerootTown/scripts.pory"
# 133 "data/maps/LittlerootTown/scripts.pory"
# 236 "data/maps/LittlerootTown/scripts.pory"

# 237 "data/maps/LittlerootTown/scripts.pory"
# 134 "data/maps/LittlerootTown/scripts.pory"
# 238 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoInsideWithMom::
# 239 "data/maps/LittlerootTown/scripts.pory"
# 135 "data/maps/LittlerootTown/scripts.pory"
# 240 "data/maps/LittlerootTown/scripts.pory"
	delay 15
# 241 "data/maps/LittlerootTown/scripts.pory"
# 136 "data/maps/LittlerootTown/scripts.pory"
# 242 "data/maps/LittlerootTown/scripts.pory"
	playse SE_LEDGE
# 243 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, LittlerootTown_Movement_PlayerStepOffTruck
# 244 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 245 "data/maps/LittlerootTown/scripts.pory"
# 139 "data/maps/LittlerootTown/scripts.pory"
# 246 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8004, VAR_0x8005
# 247 "data/maps/LittlerootTown/scripts.pory"
# 140 "data/maps/LittlerootTown/scripts.pory"
# 248 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 249 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 250 "data/maps/LittlerootTown/scripts.pory"
# 144 "data/maps/LittlerootTown/scripts.pory"
# 251 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8004, VAR_0x8005
# 252 "data/maps/LittlerootTown/scripts.pory"
# 145 "data/maps/LittlerootTown/scripts.pory"
# 253 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 254 "data/maps/LittlerootTown/scripts.pory"
# 146 "data/maps/LittlerootTown/scripts.pory"
# 255 "data/maps/LittlerootTown/scripts.pory"
	delay 10
# 256 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 257 "data/maps/LittlerootTown/scripts.pory"
# 149 "data/maps/LittlerootTown/scripts.pory"
# 258 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_OurNewHomeLetsGoInside, MSGBOX_DEFAULT
# 259 "data/maps/LittlerootTown/scripts.pory"
# 150 "data/maps/LittlerootTown/scripts.pory"
# 260 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 261 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, LittlerootTown_Movement_PlayerApproachDoor
# 262 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 263 "data/maps/LittlerootTown/scripts.pory"
# 154 "data/maps/LittlerootTown/scripts.pory"
# 264 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8004, VAR_0x8005
# 265 "data/maps/LittlerootTown/scripts.pory"
# 155 "data/maps/LittlerootTown/scripts.pory"
# 266 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 267 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, LittlerootTown_Movement_PlayerEnterHouse
# 268 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 269 "data/maps/LittlerootTown/scripts.pory"
# 159 "data/maps/LittlerootTown/scripts.pory"
# 270 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE
# 271 "data/maps/LittlerootTown/scripts.pory"
# 160 "data/maps/LittlerootTown/scripts.pory"
# 272 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_INTRO_STATE, 3
# 273 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat LOCALID_PLAYER, MAP_LITTLEROOT_TOWN
# 274 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8004, VAR_0x8005
# 275 "data/maps/LittlerootTown/scripts.pory"
# 163 "data/maps/LittlerootTown/scripts.pory"
# 276 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 277 "data/maps/LittlerootTown/scripts.pory"
# 164 "data/maps/LittlerootTown/scripts.pory"
# 278 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_FAT_MAN
# 279 "data/maps/LittlerootTown/scripts.pory"
# 165 "data/maps/LittlerootTown/scripts.pory"
# 280 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_MAP_NAME_POPUP
# 281 "data/maps/LittlerootTown/scripts.pory"
# 166 "data/maps/LittlerootTown/scripts.pory"
# 282 "data/maps/LittlerootTown/scripts.pory"
	return
# 283 "data/maps/LittlerootTown/scripts.pory"
# 167 "data/maps/LittlerootTown/scripts.pory"
# 284 "data/maps/LittlerootTown/scripts.pory"

# 285 "data/maps/LittlerootTown/scripts.pory"
# 168 "data/maps/LittlerootTown/scripts.pory"
# 286 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomExitHouse:
# 287 "data/maps/LittlerootTown/scripts.pory"
# 169 "data/maps/LittlerootTown/scripts.pory"
# 288 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 289 "data/maps/LittlerootTown/scripts.pory"
# 170 "data/maps/LittlerootTown/scripts.pory"
# 290 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 291 "data/maps/LittlerootTown/scripts.pory"
# 171 "data/maps/LittlerootTown/scripts.pory"
# 292 "data/maps/LittlerootTown/scripts.pory"

# 293 "data/maps/LittlerootTown/scripts.pory"
# 172 "data/maps/LittlerootTown/scripts.pory"
# 294 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerAtTruck:
# 295 "data/maps/LittlerootTown/scripts.pory"
# 173 "data/maps/LittlerootTown/scripts.pory"
# 296 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 297 "data/maps/LittlerootTown/scripts.pory"
# 174 "data/maps/LittlerootTown/scripts.pory"
# 298 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_left
# 299 "data/maps/LittlerootTown/scripts.pory"
# 175 "data/maps/LittlerootTown/scripts.pory"
# 300 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 301 "data/maps/LittlerootTown/scripts.pory"
# 176 "data/maps/LittlerootTown/scripts.pory"
# 302 "data/maps/LittlerootTown/scripts.pory"

# 303 "data/maps/LittlerootTown/scripts.pory"
# 177 "data/maps/LittlerootTown/scripts.pory"
# 304 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachDoor:
# 305 "data/maps/LittlerootTown/scripts.pory"
# 178 "data/maps/LittlerootTown/scripts.pory"
# 306 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 307 "data/maps/LittlerootTown/scripts.pory"
# 179 "data/maps/LittlerootTown/scripts.pory"
# 308 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 309 "data/maps/LittlerootTown/scripts.pory"
# 180 "data/maps/LittlerootTown/scripts.pory"
# 310 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 311 "data/maps/LittlerootTown/scripts.pory"
# 181 "data/maps/LittlerootTown/scripts.pory"
# 312 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 313 "data/maps/LittlerootTown/scripts.pory"
# 182 "data/maps/LittlerootTown/scripts.pory"
# 314 "data/maps/LittlerootTown/scripts.pory"

# 315 "data/maps/LittlerootTown/scripts.pory"
# 183 "data/maps/LittlerootTown/scripts.pory"
# 316 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomEnterHouse:
# 317 "data/maps/LittlerootTown/scripts.pory"
# 184 "data/maps/LittlerootTown/scripts.pory"
# 318 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 319 "data/maps/LittlerootTown/scripts.pory"
# 185 "data/maps/LittlerootTown/scripts.pory"
# 320 "data/maps/LittlerootTown/scripts.pory"
	set_invisible
# 321 "data/maps/LittlerootTown/scripts.pory"
# 186 "data/maps/LittlerootTown/scripts.pory"
# 322 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 323 "data/maps/LittlerootTown/scripts.pory"
# 187 "data/maps/LittlerootTown/scripts.pory"
# 324 "data/maps/LittlerootTown/scripts.pory"

# 325 "data/maps/LittlerootTown/scripts.pory"
# 188 "data/maps/LittlerootTown/scripts.pory"
# 326 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PlayerApproachDoor:
# 327 "data/maps/LittlerootTown/scripts.pory"
# 189 "data/maps/LittlerootTown/scripts.pory"
# 328 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 329 "data/maps/LittlerootTown/scripts.pory"
# 190 "data/maps/LittlerootTown/scripts.pory"
# 330 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 331 "data/maps/LittlerootTown/scripts.pory"
# 191 "data/maps/LittlerootTown/scripts.pory"
# 332 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 333 "data/maps/LittlerootTown/scripts.pory"
# 192 "data/maps/LittlerootTown/scripts.pory"
# 334 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 335 "data/maps/LittlerootTown/scripts.pory"
# 193 "data/maps/LittlerootTown/scripts.pory"
# 336 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 337 "data/maps/LittlerootTown/scripts.pory"
# 194 "data/maps/LittlerootTown/scripts.pory"
# 338 "data/maps/LittlerootTown/scripts.pory"

# 339 "data/maps/LittlerootTown/scripts.pory"
# 195 "data/maps/LittlerootTown/scripts.pory"
# 340 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PlayerEnterHouse:
# 341 "data/maps/LittlerootTown/scripts.pory"
# 196 "data/maps/LittlerootTown/scripts.pory"
# 342 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 343 "data/maps/LittlerootTown/scripts.pory"
# 197 "data/maps/LittlerootTown/scripts.pory"
# 344 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 345 "data/maps/LittlerootTown/scripts.pory"
# 198 "data/maps/LittlerootTown/scripts.pory"
# 346 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 347 "data/maps/LittlerootTown/scripts.pory"
# 199 "data/maps/LittlerootTown/scripts.pory"
# 348 "data/maps/LittlerootTown/scripts.pory"

# 349 "data/maps/LittlerootTown/scripts.pory"
# 200 "data/maps/LittlerootTown/scripts.pory"
# 350 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PlayerStepOffTruck:
# 351 "data/maps/LittlerootTown/scripts.pory"
# 201 "data/maps/LittlerootTown/scripts.pory"
# 352 "data/maps/LittlerootTown/scripts.pory"
	jump_right
# 353 "data/maps/LittlerootTown/scripts.pory"
# 202 "data/maps/LittlerootTown/scripts.pory"
# 354 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 355 "data/maps/LittlerootTown/scripts.pory"
# 203 "data/maps/LittlerootTown/scripts.pory"
# 356 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 357 "data/maps/LittlerootTown/scripts.pory"
# 204 "data/maps/LittlerootTown/scripts.pory"
# 358 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 359 "data/maps/LittlerootTown/scripts.pory"
# 205 "data/maps/LittlerootTown/scripts.pory"
# 360 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 361 "data/maps/LittlerootTown/scripts.pory"
# 206 "data/maps/LittlerootTown/scripts.pory"
# 362 "data/maps/LittlerootTown/scripts.pory"

# 363 "data/maps/LittlerootTown/scripts.pory"
# 207 "data/maps/LittlerootTown/scripts.pory"
# 364 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BeginDexUpgradeScene::
# 365 "data/maps/LittlerootTown/scripts.pory"
# 208 "data/maps/LittlerootTown/scripts.pory"
# 366 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 367 "data/maps/LittlerootTown/scripts.pory"
# 209 "data/maps/LittlerootTown/scripts.pory"
# 368 "data/maps/LittlerootTown/scripts.pory"
	playse SE_PIN
# 369 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 370 "data/maps/LittlerootTown/scripts.pory"
# 212 "data/maps/LittlerootTown/scripts.pory"
# 371 "data/maps/LittlerootTown/scripts.pory"
	delay 80
# 372 "data/maps/LittlerootTown/scripts.pory"
# 213 "data/maps/LittlerootTown/scripts.pory"
# 373 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_BirchSomethingToShowYouAtLab, MSGBOX_DEFAULT
# 374 "data/maps/LittlerootTown/scripts.pory"
# 214 "data/maps/LittlerootTown/scripts.pory"
# 375 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 376 "data/maps/LittlerootTown/scripts.pory"
# 215 "data/maps/LittlerootTown/scripts.pory"
# 377 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_RIVAL
# 378 "data/maps/LittlerootTown/scripts.pory"
# 216 "data/maps/LittlerootTown/scripts.pory"
# 379 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCH
# 380 "data/maps/LittlerootTown/scripts.pory"
# 217 "data/maps/LittlerootTown/scripts.pory"
# 381 "data/maps/LittlerootTown/scripts.pory"
	delay 20
# 382 "data/maps/LittlerootTown/scripts.pory"
# 218 "data/maps/LittlerootTown/scripts.pory"
# 383 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_MAP_NAME_POPUP
# 384 "data/maps/LittlerootTown/scripts.pory"
# 219 "data/maps/LittlerootTown/scripts.pory"
# 385 "data/maps/LittlerootTown/scripts.pory"
	warp MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB, 6, 5
# 386 "data/maps/LittlerootTown/scripts.pory"
# 220 "data/maps/LittlerootTown/scripts.pory"
# 387 "data/maps/LittlerootTown/scripts.pory"
	waitstate
# 388 "data/maps/LittlerootTown/scripts.pory"
# 221 "data/maps/LittlerootTown/scripts.pory"
# 389 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 390 "data/maps/LittlerootTown/scripts.pory"
# 222 "data/maps/LittlerootTown/scripts.pory"
# 391 "data/maps/LittlerootTown/scripts.pory"
	end
# 392 "data/maps/LittlerootTown/scripts.pory"
# 223 "data/maps/LittlerootTown/scripts.pory"
# 393 "data/maps/LittlerootTown/scripts.pory"

# 394 "data/maps/LittlerootTown/scripts.pory"
# 224 "data/maps/LittlerootTown/scripts.pory"
# 395 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_OnWarp:
# 396 "data/maps/LittlerootTown/scripts.pory"
# 225 "data/maps/LittlerootTown/scripts.pory"
# 397 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 1, LittlerootTown_EventScript_SetRivalBirchPosForDexUpgrade
# 398 "data/maps/LittlerootTown/scripts.pory"
# 226 "data/maps/LittlerootTown/scripts.pory"
# 399 "data/maps/LittlerootTown/scripts.pory"
	.2byte 0
# 400 "data/maps/LittlerootTown/scripts.pory"
# 227 "data/maps/LittlerootTown/scripts.pory"
# 401 "data/maps/LittlerootTown/scripts.pory"

# 402 "data/maps/LittlerootTown/scripts.pory"
# 228 "data/maps/LittlerootTown/scripts.pory"
# 403 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalBirchPosForDexUpgrade::
# 404 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 405 "data/maps/LittlerootTown/scripts.pory"
# 232 "data/maps/LittlerootTown/scripts.pory"
# 406 "data/maps/LittlerootTown/scripts.pory"
	goto_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeMale
# 407 "data/maps/LittlerootTown/scripts.pory"
# 233 "data/maps/LittlerootTown/scripts.pory"
# 408 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeFemale
# 409 "data/maps/LittlerootTown/scripts.pory"
# 234 "data/maps/LittlerootTown/scripts.pory"
# 410 "data/maps/LittlerootTown/scripts.pory"
	end
# 411 "data/maps/LittlerootTown/scripts.pory"
# 235 "data/maps/LittlerootTown/scripts.pory"
# 412 "data/maps/LittlerootTown/scripts.pory"

# 413 "data/maps/LittlerootTown/scripts.pory"
# 236 "data/maps/LittlerootTown/scripts.pory"
# 414 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeMale::
# 415 "data/maps/LittlerootTown/scripts.pory"
	end
# 416 "data/maps/LittlerootTown/scripts.pory"
# 240 "data/maps/LittlerootTown/scripts.pory"
# 417 "data/maps/LittlerootTown/scripts.pory"

# 418 "data/maps/LittlerootTown/scripts.pory"
# 241 "data/maps/LittlerootTown/scripts.pory"
# 419 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeFemale::
# 420 "data/maps/LittlerootTown/scripts.pory"
	end
# 421 "data/maps/LittlerootTown/scripts.pory"
# 245 "data/maps/LittlerootTown/scripts.pory"
# 422 "data/maps/LittlerootTown/scripts.pory"

# 423 "data/maps/LittlerootTown/scripts.pory"
# 246 "data/maps/LittlerootTown/scripts.pory"
# 424 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_FatMan::
# 425 "data/maps/LittlerootTown/scripts.pory"
# 247 "data/maps/LittlerootTown/scripts.pory"
# 426 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_CanUsePCToStoreItems, MSGBOX_NPC
# 427 "data/maps/LittlerootTown/scripts.pory"
# 248 "data/maps/LittlerootTown/scripts.pory"
# 428 "data/maps/LittlerootTown/scripts.pory"
	end
# 429 "data/maps/LittlerootTown/scripts.pory"
# 249 "data/maps/LittlerootTown/scripts.pory"
# 430 "data/maps/LittlerootTown/scripts.pory"

# 431 "data/maps/LittlerootTown/scripts.pory"
# 250 "data/maps/LittlerootTown/scripts.pory"
# 432 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_Boy::
# 433 "data/maps/LittlerootTown/scripts.pory"
# 251 "data/maps/LittlerootTown/scripts.pory"
# 434 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_BirchSpendsDaysInLab, MSGBOX_NPC
# 435 "data/maps/LittlerootTown/scripts.pory"
# 252 "data/maps/LittlerootTown/scripts.pory"
# 436 "data/maps/LittlerootTown/scripts.pory"
	end
# 437 "data/maps/LittlerootTown/scripts.pory"
# 253 "data/maps/LittlerootTown/scripts.pory"
# 438 "data/maps/LittlerootTown/scripts.pory"

# 439 "data/maps/LittlerootTown/scripts.pory"
# 254 "data/maps/LittlerootTown/scripts.pory"
# 440 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_Twin::
# 441 "data/maps/LittlerootTown/scripts.pory"
# 255 "data/maps/LittlerootTown/scripts.pory"
# 442 "data/maps/LittlerootTown/scripts.pory"
	lock
# 443 "data/maps/LittlerootTown/scripts.pory"
# 256 "data/maps/LittlerootTown/scripts.pory"
# 444 "data/maps/LittlerootTown/scripts.pory"
	faceplayer
# 445 "data/maps/LittlerootTown/scripts.pory"
# 257 "data/maps/LittlerootTown/scripts.pory"
# 446 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set FLAG_ADVENTURE_STARTED, LittlerootTown_EventScript_GoodLuck
# 447 "data/maps/LittlerootTown/scripts.pory"
# 258 "data/maps/LittlerootTown/scripts.pory"
# 448 "data/maps/LittlerootTown/scripts.pory"
# 259 "data/maps/LittlerootTown/scripts.pory"
# 449 "data/maps/LittlerootTown/scripts.pory"
	goto_if_ne VAR_LITTLEROOT_TOWN_STATE, 0, LittlerootTown_EventScript_GoSaveBirch
# 450 "data/maps/LittlerootTown/scripts.pory"
# 260 "data/maps/LittlerootTown/scripts.pory"
# 451 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut, MSGBOX_DEFAULT
# 452 "data/maps/LittlerootTown/scripts.pory"
# 261 "data/maps/LittlerootTown/scripts.pory"
# 453 "data/maps/LittlerootTown/scripts.pory"
	release
# 454 "data/maps/LittlerootTown/scripts.pory"
# 262 "data/maps/LittlerootTown/scripts.pory"
# 455 "data/maps/LittlerootTown/scripts.pory"
	end
# 456 "data/maps/LittlerootTown/scripts.pory"
# 263 "data/maps/LittlerootTown/scripts.pory"
# 457 "data/maps/LittlerootTown/scripts.pory"

# 458 "data/maps/LittlerootTown/scripts.pory"
# 264 "data/maps/LittlerootTown/scripts.pory"
# 459 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoSaveBirch::
# 460 "data/maps/LittlerootTown/scripts.pory"
# 265 "data/maps/LittlerootTown/scripts.pory"
# 461 "data/maps/LittlerootTown/scripts.pory"
	special GetPlayerBigGuyGirlString
# 462 "data/maps/LittlerootTown/scripts.pory"
# 266 "data/maps/LittlerootTown/scripts.pory"
# 463 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_CanYouGoSeeWhatsHappening, MSGBOX_DEFAULT
# 464 "data/maps/LittlerootTown/scripts.pory"
# 267 "data/maps/LittlerootTown/scripts.pory"
# 465 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 466 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 467 "data/maps/LittlerootTown/scripts.pory"
# 270 "data/maps/LittlerootTown/scripts.pory"
# 468 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_TOWN_STATE, 2
# 469 "data/maps/LittlerootTown/scripts.pory"
# 271 "data/maps/LittlerootTown/scripts.pory"
# 470 "data/maps/LittlerootTown/scripts.pory"
	release
# 471 "data/maps/LittlerootTown/scripts.pory"
# 272 "data/maps/LittlerootTown/scripts.pory"
# 472 "data/maps/LittlerootTown/scripts.pory"
	end
# 473 "data/maps/LittlerootTown/scripts.pory"
# 273 "data/maps/LittlerootTown/scripts.pory"
# 474 "data/maps/LittlerootTown/scripts.pory"

# 475 "data/maps/LittlerootTown/scripts.pory"
# 274 "data/maps/LittlerootTown/scripts.pory"
# 476 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_YouSavedBirch::
# 477 "data/maps/LittlerootTown/scripts.pory"
# 275 "data/maps/LittlerootTown/scripts.pory"
# 478 "data/maps/LittlerootTown/scripts.pory"
	special GetPlayerBigGuyGirlString
# 479 "data/maps/LittlerootTown/scripts.pory"
# 276 "data/maps/LittlerootTown/scripts.pory"
# 480 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_YouSavedBirch, MSGBOX_DEFAULT
# 481 "data/maps/LittlerootTown/scripts.pory"
# 277 "data/maps/LittlerootTown/scripts.pory"
# 482 "data/maps/LittlerootTown/scripts.pory"
	release
# 483 "data/maps/LittlerootTown/scripts.pory"
# 278 "data/maps/LittlerootTown/scripts.pory"
# 484 "data/maps/LittlerootTown/scripts.pory"
	end
# 485 "data/maps/LittlerootTown/scripts.pory"
# 279 "data/maps/LittlerootTown/scripts.pory"
# 486 "data/maps/LittlerootTown/scripts.pory"

# 487 "data/maps/LittlerootTown/scripts.pory"
# 280 "data/maps/LittlerootTown/scripts.pory"
# 488 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoodLuck::
# 489 "data/maps/LittlerootTown/scripts.pory"
# 281 "data/maps/LittlerootTown/scripts.pory"
# 490 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_GoodLuckCatchingPokemon, MSGBOX_DEFAULT
# 491 "data/maps/LittlerootTown/scripts.pory"
# 282 "data/maps/LittlerootTown/scripts.pory"
# 492 "data/maps/LittlerootTown/scripts.pory"
	release
# 493 "data/maps/LittlerootTown/scripts.pory"
# 283 "data/maps/LittlerootTown/scripts.pory"
# 494 "data/maps/LittlerootTown/scripts.pory"
	end
# 495 "data/maps/LittlerootTown/scripts.pory"
# 284 "data/maps/LittlerootTown/scripts.pory"
# 496 "data/maps/LittlerootTown/scripts.pory"

# 497 "data/maps/LittlerootTown/scripts.pory"
# 285 "data/maps/LittlerootTown/scripts.pory"
# 498 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_NeedPokemonTriggerLeft::
# 499 "data/maps/LittlerootTown/scripts.pory"
# 286 "data/maps/LittlerootTown/scripts.pory"
# 500 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 501 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 502 "data/maps/LittlerootTown/scripts.pory"
# 289 "data/maps/LittlerootTown/scripts.pory"
# 503 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_DangerousWithoutPokemon
# 504 "data/maps/LittlerootTown/scripts.pory"
# 290 "data/maps/LittlerootTown/scripts.pory"
# 505 "data/maps/LittlerootTown/scripts.pory"
# 291 "data/maps/LittlerootTown/scripts.pory"
# 506 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 507 "data/maps/LittlerootTown/scripts.pory"
# 292 "data/maps/LittlerootTown/scripts.pory"
# 508 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 509 "data/maps/LittlerootTown/scripts.pory"
# 293 "data/maps/LittlerootTown/scripts.pory"
# 510 "data/maps/LittlerootTown/scripts.pory"
	end
# 511 "data/maps/LittlerootTown/scripts.pory"
# 294 "data/maps/LittlerootTown/scripts.pory"
# 512 "data/maps/LittlerootTown/scripts.pory"

# 513 "data/maps/LittlerootTown/scripts.pory"
# 295 "data/maps/LittlerootTown/scripts.pory"
# 514 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_DangerousWithoutPokemon::
# 515 "data/maps/LittlerootTown/scripts.pory"
# 296 "data/maps/LittlerootTown/scripts.pory"
# 516 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut, MSGBOX_DEFAULT
# 517 "data/maps/LittlerootTown/scripts.pory"
# 297 "data/maps/LittlerootTown/scripts.pory"
# 518 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 519 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, LittlerootTown_Movement_PushPlayerBackFromRoute
# 520 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 521 "data/maps/LittlerootTown/scripts.pory"
# 301 "data/maps/LittlerootTown/scripts.pory"
# 522 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_DangerousIfYouDontHavePokemon, MSGBOX_DEFAULT
# 523 "data/maps/LittlerootTown/scripts.pory"
# 302 "data/maps/LittlerootTown/scripts.pory"
# 524 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 525 "data/maps/LittlerootTown/scripts.pory"
# 303 "data/maps/LittlerootTown/scripts.pory"
# 526 "data/maps/LittlerootTown/scripts.pory"
	return
# 527 "data/maps/LittlerootTown/scripts.pory"
# 304 "data/maps/LittlerootTown/scripts.pory"
# 528 "data/maps/LittlerootTown/scripts.pory"

# 529 "data/maps/LittlerootTown/scripts.pory"
# 305 "data/maps/LittlerootTown/scripts.pory"
# 530 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinApproachPlayerLeft:
# 531 "data/maps/LittlerootTown/scripts.pory"
# 306 "data/maps/LittlerootTown/scripts.pory"
# 532 "data/maps/LittlerootTown/scripts.pory"
	face_right
# 533 "data/maps/LittlerootTown/scripts.pory"
# 307 "data/maps/LittlerootTown/scripts.pory"
# 534 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 535 "data/maps/LittlerootTown/scripts.pory"
# 308 "data/maps/LittlerootTown/scripts.pory"
# 536 "data/maps/LittlerootTown/scripts.pory"
	disable_jump_landing_ground_effect
# 537 "data/maps/LittlerootTown/scripts.pory"
# 309 "data/maps/LittlerootTown/scripts.pory"
# 538 "data/maps/LittlerootTown/scripts.pory"
	jump_in_place_right
# 539 "data/maps/LittlerootTown/scripts.pory"
# 310 "data/maps/LittlerootTown/scripts.pory"
# 540 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 541 "data/maps/LittlerootTown/scripts.pory"
# 311 "data/maps/LittlerootTown/scripts.pory"
# 542 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 543 "data/maps/LittlerootTown/scripts.pory"
# 312 "data/maps/LittlerootTown/scripts.pory"
# 544 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 545 "data/maps/LittlerootTown/scripts.pory"
# 313 "data/maps/LittlerootTown/scripts.pory"
# 546 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 547 "data/maps/LittlerootTown/scripts.pory"
# 314 "data/maps/LittlerootTown/scripts.pory"
# 548 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 549 "data/maps/LittlerootTown/scripts.pory"
# 315 "data/maps/LittlerootTown/scripts.pory"
# 550 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 551 "data/maps/LittlerootTown/scripts.pory"
# 316 "data/maps/LittlerootTown/scripts.pory"
# 552 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 553 "data/maps/LittlerootTown/scripts.pory"
# 317 "data/maps/LittlerootTown/scripts.pory"
# 554 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_left
# 555 "data/maps/LittlerootTown/scripts.pory"
# 318 "data/maps/LittlerootTown/scripts.pory"
# 556 "data/maps/LittlerootTown/scripts.pory"
	face_down
# 557 "data/maps/LittlerootTown/scripts.pory"
# 319 "data/maps/LittlerootTown/scripts.pory"
# 558 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 559 "data/maps/LittlerootTown/scripts.pory"
# 320 "data/maps/LittlerootTown/scripts.pory"
# 560 "data/maps/LittlerootTown/scripts.pory"

# 561 "data/maps/LittlerootTown/scripts.pory"
# 321 "data/maps/LittlerootTown/scripts.pory"
# 562 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinPushPlayerFromRoute:
# 563 "data/maps/LittlerootTown/scripts.pory"
# 322 "data/maps/LittlerootTown/scripts.pory"
# 564 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 565 "data/maps/LittlerootTown/scripts.pory"
# 323 "data/maps/LittlerootTown/scripts.pory"
# 566 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 567 "data/maps/LittlerootTown/scripts.pory"
# 324 "data/maps/LittlerootTown/scripts.pory"
# 568 "data/maps/LittlerootTown/scripts.pory"

# 569 "data/maps/LittlerootTown/scripts.pory"
# 325 "data/maps/LittlerootTown/scripts.pory"
# 570 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinReturnLeft:
# 571 "data/maps/LittlerootTown/scripts.pory"
# 326 "data/maps/LittlerootTown/scripts.pory"
# 572 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 573 "data/maps/LittlerootTown/scripts.pory"
# 327 "data/maps/LittlerootTown/scripts.pory"
# 574 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 575 "data/maps/LittlerootTown/scripts.pory"
# 328 "data/maps/LittlerootTown/scripts.pory"
# 576 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 577 "data/maps/LittlerootTown/scripts.pory"
# 329 "data/maps/LittlerootTown/scripts.pory"
# 578 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 579 "data/maps/LittlerootTown/scripts.pory"
# 330 "data/maps/LittlerootTown/scripts.pory"
# 580 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 581 "data/maps/LittlerootTown/scripts.pory"
# 331 "data/maps/LittlerootTown/scripts.pory"
# 582 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 583 "data/maps/LittlerootTown/scripts.pory"
# 332 "data/maps/LittlerootTown/scripts.pory"
# 584 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 585 "data/maps/LittlerootTown/scripts.pory"
# 333 "data/maps/LittlerootTown/scripts.pory"
# 586 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 587 "data/maps/LittlerootTown/scripts.pory"
# 334 "data/maps/LittlerootTown/scripts.pory"
# 588 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_down
# 589 "data/maps/LittlerootTown/scripts.pory"
# 335 "data/maps/LittlerootTown/scripts.pory"
# 590 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 591 "data/maps/LittlerootTown/scripts.pory"
# 336 "data/maps/LittlerootTown/scripts.pory"
# 592 "data/maps/LittlerootTown/scripts.pory"

# 593 "data/maps/LittlerootTown/scripts.pory"
# 337 "data/maps/LittlerootTown/scripts.pory"
# 594 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PushPlayerBackFromRoute:
# 595 "data/maps/LittlerootTown/scripts.pory"
# 338 "data/maps/LittlerootTown/scripts.pory"
# 596 "data/maps/LittlerootTown/scripts.pory"
	lock_facing_direction
# 597 "data/maps/LittlerootTown/scripts.pory"
# 339 "data/maps/LittlerootTown/scripts.pory"
# 598 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 599 "data/maps/LittlerootTown/scripts.pory"
# 340 "data/maps/LittlerootTown/scripts.pory"
# 600 "data/maps/LittlerootTown/scripts.pory"
	unlock_facing_direction
# 601 "data/maps/LittlerootTown/scripts.pory"
# 341 "data/maps/LittlerootTown/scripts.pory"
# 602 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 603 "data/maps/LittlerootTown/scripts.pory"
# 342 "data/maps/LittlerootTown/scripts.pory"
# 604 "data/maps/LittlerootTown/scripts.pory"

# 605 "data/maps/LittlerootTown/scripts.pory"
# 343 "data/maps/LittlerootTown/scripts.pory"
# 606 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_NeedPokemonTriggerRight::
# 607 "data/maps/LittlerootTown/scripts.pory"
# 344 "data/maps/LittlerootTown/scripts.pory"
# 608 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 609 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 610 "data/maps/LittlerootTown/scripts.pory"
# 347 "data/maps/LittlerootTown/scripts.pory"
# 611 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_DangerousWithoutPokemon
# 612 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 613 "data/maps/LittlerootTown/scripts.pory"
# 350 "data/maps/LittlerootTown/scripts.pory"
# 614 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 615 "data/maps/LittlerootTown/scripts.pory"
# 351 "data/maps/LittlerootTown/scripts.pory"
# 616 "data/maps/LittlerootTown/scripts.pory"
	end
# 617 "data/maps/LittlerootTown/scripts.pory"
# 352 "data/maps/LittlerootTown/scripts.pory"
# 618 "data/maps/LittlerootTown/scripts.pory"

# 619 "data/maps/LittlerootTown/scripts.pory"
# 353 "data/maps/LittlerootTown/scripts.pory"
# 620 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinApproachPlayerRight:
# 621 "data/maps/LittlerootTown/scripts.pory"
# 354 "data/maps/LittlerootTown/scripts.pory"
# 622 "data/maps/LittlerootTown/scripts.pory"
	face_right
# 623 "data/maps/LittlerootTown/scripts.pory"
# 355 "data/maps/LittlerootTown/scripts.pory"
# 624 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 625 "data/maps/LittlerootTown/scripts.pory"
# 356 "data/maps/LittlerootTown/scripts.pory"
# 626 "data/maps/LittlerootTown/scripts.pory"
	disable_jump_landing_ground_effect
# 627 "data/maps/LittlerootTown/scripts.pory"
# 357 "data/maps/LittlerootTown/scripts.pory"
# 628 "data/maps/LittlerootTown/scripts.pory"
	jump_in_place_right
# 629 "data/maps/LittlerootTown/scripts.pory"
# 358 "data/maps/LittlerootTown/scripts.pory"
# 630 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 631 "data/maps/LittlerootTown/scripts.pory"
# 359 "data/maps/LittlerootTown/scripts.pory"
# 632 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 633 "data/maps/LittlerootTown/scripts.pory"
# 360 "data/maps/LittlerootTown/scripts.pory"
# 634 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 635 "data/maps/LittlerootTown/scripts.pory"
# 361 "data/maps/LittlerootTown/scripts.pory"
# 636 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 637 "data/maps/LittlerootTown/scripts.pory"
# 362 "data/maps/LittlerootTown/scripts.pory"
# 638 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 639 "data/maps/LittlerootTown/scripts.pory"
# 363 "data/maps/LittlerootTown/scripts.pory"
# 640 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 641 "data/maps/LittlerootTown/scripts.pory"
# 364 "data/maps/LittlerootTown/scripts.pory"
# 642 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 643 "data/maps/LittlerootTown/scripts.pory"
# 365 "data/maps/LittlerootTown/scripts.pory"
# 644 "data/maps/LittlerootTown/scripts.pory"
	face_down
# 645 "data/maps/LittlerootTown/scripts.pory"
# 366 "data/maps/LittlerootTown/scripts.pory"
# 646 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 647 "data/maps/LittlerootTown/scripts.pory"
# 367 "data/maps/LittlerootTown/scripts.pory"
# 648 "data/maps/LittlerootTown/scripts.pory"

# 649 "data/maps/LittlerootTown/scripts.pory"
# 368 "data/maps/LittlerootTown/scripts.pory"
# 650 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinReturnRight:
# 651 "data/maps/LittlerootTown/scripts.pory"
# 369 "data/maps/LittlerootTown/scripts.pory"
# 652 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 653 "data/maps/LittlerootTown/scripts.pory"
# 370 "data/maps/LittlerootTown/scripts.pory"
# 654 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 655 "data/maps/LittlerootTown/scripts.pory"
# 371 "data/maps/LittlerootTown/scripts.pory"
# 656 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 657 "data/maps/LittlerootTown/scripts.pory"
# 372 "data/maps/LittlerootTown/scripts.pory"
# 658 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 659 "data/maps/LittlerootTown/scripts.pory"
# 373 "data/maps/LittlerootTown/scripts.pory"
# 660 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 661 "data/maps/LittlerootTown/scripts.pory"
# 374 "data/maps/LittlerootTown/scripts.pory"
# 662 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_down
# 663 "data/maps/LittlerootTown/scripts.pory"
# 375 "data/maps/LittlerootTown/scripts.pory"
# 664 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 665 "data/maps/LittlerootTown/scripts.pory"
# 376 "data/maps/LittlerootTown/scripts.pory"
# 666 "data/maps/LittlerootTown/scripts.pory"

# 667 "data/maps/LittlerootTown/scripts.pory"
# 377 "data/maps/LittlerootTown/scripts.pory"
# 668 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoSaveBirchTrigger::
# 669 "data/maps/LittlerootTown/scripts.pory"
# 378 "data/maps/LittlerootTown/scripts.pory"
# 670 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 671 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 672 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 673 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 674 "data/maps/LittlerootTown/scripts.pory"
# 383 "data/maps/LittlerootTown/scripts.pory"
# 675 "data/maps/LittlerootTown/scripts.pory"
	special GetPlayerBigGuyGirlString
# 676 "data/maps/LittlerootTown/scripts.pory"
# 384 "data/maps/LittlerootTown/scripts.pory"
# 677 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_CanYouGoSeeWhatsHappening, MSGBOX_DEFAULT
# 678 "data/maps/LittlerootTown/scripts.pory"
# 385 "data/maps/LittlerootTown/scripts.pory"
# 679 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 680 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 681 "data/maps/LittlerootTown/scripts.pory"
# 388 "data/maps/LittlerootTown/scripts.pory"
# 682 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_TOWN_STATE, 2
# 683 "data/maps/LittlerootTown/scripts.pory"
# 389 "data/maps/LittlerootTown/scripts.pory"
# 684 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 685 "data/maps/LittlerootTown/scripts.pory"
# 390 "data/maps/LittlerootTown/scripts.pory"
# 686 "data/maps/LittlerootTown/scripts.pory"
	end
# 687 "data/maps/LittlerootTown/scripts.pory"
# 391 "data/maps/LittlerootTown/scripts.pory"
# 688 "data/maps/LittlerootTown/scripts.pory"

# 689 "data/maps/LittlerootTown/scripts.pory"
# 392 "data/maps/LittlerootTown/scripts.pory"
# 690 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_TownSign::
# 691 "data/maps/LittlerootTown/scripts.pory"
# 393 "data/maps/LittlerootTown/scripts.pory"
# 692 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_TownSign, MSGBOX_SIGN
# 693 "data/maps/LittlerootTown/scripts.pory"
# 394 "data/maps/LittlerootTown/scripts.pory"
# 694 "data/maps/LittlerootTown/scripts.pory"
	end
# 695 "data/maps/LittlerootTown/scripts.pory"
# 395 "data/maps/LittlerootTown/scripts.pory"
# 696 "data/maps/LittlerootTown/scripts.pory"

# 697 "data/maps/LittlerootTown/scripts.pory"
# 396 "data/maps/LittlerootTown/scripts.pory"
# 698 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BirchsLabSign::
# 699 "data/maps/LittlerootTown/scripts.pory"
# 397 "data/maps/LittlerootTown/scripts.pory"
# 700 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ProfBirchsLab, MSGBOX_SIGN
# 701 "data/maps/LittlerootTown/scripts.pory"
# 398 "data/maps/LittlerootTown/scripts.pory"
# 702 "data/maps/LittlerootTown/scripts.pory"
	end
# 703 "data/maps/LittlerootTown/scripts.pory"
# 399 "data/maps/LittlerootTown/scripts.pory"
# 704 "data/maps/LittlerootTown/scripts.pory"

# 705 "data/maps/LittlerootTown/scripts.pory"
# 400 "data/maps/LittlerootTown/scripts.pory"
# 706 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BrendansHouseSign::
# 707 "data/maps/LittlerootTown/scripts.pory"
# 401 "data/maps/LittlerootTown/scripts.pory"
# 708 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 709 "data/maps/LittlerootTown/scripts.pory"
# 402 "data/maps/LittlerootTown/scripts.pory"
# 710 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 711 "data/maps/LittlerootTown/scripts.pory"
# 403 "data/maps/LittlerootTown/scripts.pory"
# 712 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_PlayersHouseSignMale
# 713 "data/maps/LittlerootTown/scripts.pory"
# 404 "data/maps/LittlerootTown/scripts.pory"
# 714 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_BirchsHouseSignFemale
# 715 "data/maps/LittlerootTown/scripts.pory"
# 405 "data/maps/LittlerootTown/scripts.pory"
# 716 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 717 "data/maps/LittlerootTown/scripts.pory"
# 406 "data/maps/LittlerootTown/scripts.pory"
# 718 "data/maps/LittlerootTown/scripts.pory"
	end
# 719 "data/maps/LittlerootTown/scripts.pory"
# 407 "data/maps/LittlerootTown/scripts.pory"
# 720 "data/maps/LittlerootTown/scripts.pory"

# 721 "data/maps/LittlerootTown/scripts.pory"
# 408 "data/maps/LittlerootTown/scripts.pory"
# 722 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_PlayersHouseSignMale::
# 723 "data/maps/LittlerootTown/scripts.pory"
# 409 "data/maps/LittlerootTown/scripts.pory"
# 724 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_PlayersHouse, MSGBOX_DEFAULT
# 725 "data/maps/LittlerootTown/scripts.pory"
# 410 "data/maps/LittlerootTown/scripts.pory"
# 726 "data/maps/LittlerootTown/scripts.pory"
	return
# 727 "data/maps/LittlerootTown/scripts.pory"
# 411 "data/maps/LittlerootTown/scripts.pory"
# 728 "data/maps/LittlerootTown/scripts.pory"

# 729 "data/maps/LittlerootTown/scripts.pory"
# 412 "data/maps/LittlerootTown/scripts.pory"
# 730 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BirchsHouseSignFemale::
# 731 "data/maps/LittlerootTown/scripts.pory"
# 413 "data/maps/LittlerootTown/scripts.pory"
# 732 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ProfBirchsHouse, MSGBOX_DEFAULT
# 733 "data/maps/LittlerootTown/scripts.pory"
# 414 "data/maps/LittlerootTown/scripts.pory"
# 734 "data/maps/LittlerootTown/scripts.pory"
	return
# 735 "data/maps/LittlerootTown/scripts.pory"
# 415 "data/maps/LittlerootTown/scripts.pory"
# 736 "data/maps/LittlerootTown/scripts.pory"

# 737 "data/maps/LittlerootTown/scripts.pory"
# 416 "data/maps/LittlerootTown/scripts.pory"
# 738 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MaysHouseSign::
# 739 "data/maps/LittlerootTown/scripts.pory"
# 417 "data/maps/LittlerootTown/scripts.pory"
# 740 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 741 "data/maps/LittlerootTown/scripts.pory"
# 418 "data/maps/LittlerootTown/scripts.pory"
# 742 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 743 "data/maps/LittlerootTown/scripts.pory"
# 419 "data/maps/LittlerootTown/scripts.pory"
# 744 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_BirchsHouseSignMale
# 745 "data/maps/LittlerootTown/scripts.pory"
# 420 "data/maps/LittlerootTown/scripts.pory"
# 746 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_PlayersHouseSignFemale
# 747 "data/maps/LittlerootTown/scripts.pory"
# 421 "data/maps/LittlerootTown/scripts.pory"
# 748 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 749 "data/maps/LittlerootTown/scripts.pory"
# 422 "data/maps/LittlerootTown/scripts.pory"
# 750 "data/maps/LittlerootTown/scripts.pory"
	end
# 751 "data/maps/LittlerootTown/scripts.pory"
# 423 "data/maps/LittlerootTown/scripts.pory"
# 752 "data/maps/LittlerootTown/scripts.pory"

# 753 "data/maps/LittlerootTown/scripts.pory"
# 424 "data/maps/LittlerootTown/scripts.pory"
# 754 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BirchsHouseSignMale::
# 755 "data/maps/LittlerootTown/scripts.pory"
# 425 "data/maps/LittlerootTown/scripts.pory"
# 756 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ProfBirchsHouse, MSGBOX_DEFAULT
# 757 "data/maps/LittlerootTown/scripts.pory"
# 426 "data/maps/LittlerootTown/scripts.pory"
# 758 "data/maps/LittlerootTown/scripts.pory"
	return
# 759 "data/maps/LittlerootTown/scripts.pory"
# 427 "data/maps/LittlerootTown/scripts.pory"
# 760 "data/maps/LittlerootTown/scripts.pory"

# 761 "data/maps/LittlerootTown/scripts.pory"
# 428 "data/maps/LittlerootTown/scripts.pory"
# 762 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_PlayersHouseSignFemale::
# 763 "data/maps/LittlerootTown/scripts.pory"
# 429 "data/maps/LittlerootTown/scripts.pory"
# 764 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_PlayersHouse, MSGBOX_DEFAULT
# 765 "data/maps/LittlerootTown/scripts.pory"
# 430 "data/maps/LittlerootTown/scripts.pory"
# 766 "data/maps/LittlerootTown/scripts.pory"
	return
# 767 "data/maps/LittlerootTown/scripts.pory"
# 431 "data/maps/LittlerootTown/scripts.pory"
# 768 "data/maps/LittlerootTown/scripts.pory"

# 769 "data/maps/LittlerootTown/scripts.pory"
# 432 "data/maps/LittlerootTown/scripts.pory"
# 770 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger0::
# 771 "data/maps/LittlerootTown/scripts.pory"
# 433 "data/maps/LittlerootTown/scripts.pory"
# 772 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 773 "data/maps/LittlerootTown/scripts.pory"
# 434 "data/maps/LittlerootTown/scripts.pory"
# 774 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 0
# 775 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 776 "data/maps/LittlerootTown/scripts.pory"
# 437 "data/maps/LittlerootTown/scripts.pory"
# 777 "data/maps/LittlerootTown/scripts.pory"
	end
# 778 "data/maps/LittlerootTown/scripts.pory"
# 438 "data/maps/LittlerootTown/scripts.pory"
# 779 "data/maps/LittlerootTown/scripts.pory"

# 780 "data/maps/LittlerootTown/scripts.pory"
# 439 "data/maps/LittlerootTown/scripts.pory"
# 781 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger1::
# 782 "data/maps/LittlerootTown/scripts.pory"
# 440 "data/maps/LittlerootTown/scripts.pory"
# 783 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 784 "data/maps/LittlerootTown/scripts.pory"
# 441 "data/maps/LittlerootTown/scripts.pory"
# 785 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 1
# 786 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 787 "data/maps/LittlerootTown/scripts.pory"
# 444 "data/maps/LittlerootTown/scripts.pory"
# 788 "data/maps/LittlerootTown/scripts.pory"
	end
# 789 "data/maps/LittlerootTown/scripts.pory"
# 445 "data/maps/LittlerootTown/scripts.pory"
# 790 "data/maps/LittlerootTown/scripts.pory"

# 791 "data/maps/LittlerootTown/scripts.pory"
# 446 "data/maps/LittlerootTown/scripts.pory"
# 792 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger2::
# 793 "data/maps/LittlerootTown/scripts.pory"
# 447 "data/maps/LittlerootTown/scripts.pory"
# 794 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 795 "data/maps/LittlerootTown/scripts.pory"
# 448 "data/maps/LittlerootTown/scripts.pory"
# 796 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 2
# 797 "data/maps/LittlerootTown/scripts.pory"
# 449 "data/maps/LittlerootTown/scripts.pory"
# 798 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 799 "data/maps/LittlerootTown/scripts.pory"
# 450 "data/maps/LittlerootTown/scripts.pory"
# 800 "data/maps/LittlerootTown/scripts.pory"
	end
# 801 "data/maps/LittlerootTown/scripts.pory"
# 451 "data/maps/LittlerootTown/scripts.pory"
# 802 "data/maps/LittlerootTown/scripts.pory"

# 803 "data/maps/LittlerootTown/scripts.pory"
# 452 "data/maps/LittlerootTown/scripts.pory"
# 804 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger3::
# 805 "data/maps/LittlerootTown/scripts.pory"
# 453 "data/maps/LittlerootTown/scripts.pory"
# 806 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 807 "data/maps/LittlerootTown/scripts.pory"
# 454 "data/maps/LittlerootTown/scripts.pory"
# 808 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 3
# 809 "data/maps/LittlerootTown/scripts.pory"
# 455 "data/maps/LittlerootTown/scripts.pory"
# 810 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 811 "data/maps/LittlerootTown/scripts.pory"
# 456 "data/maps/LittlerootTown/scripts.pory"
# 812 "data/maps/LittlerootTown/scripts.pory"
	end
# 813 "data/maps/LittlerootTown/scripts.pory"
# 457 "data/maps/LittlerootTown/scripts.pory"
# 814 "data/maps/LittlerootTown/scripts.pory"

# 815 "data/maps/LittlerootTown/scripts.pory"
# 458 "data/maps/LittlerootTown/scripts.pory"
# 816 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger4::
# 817 "data/maps/LittlerootTown/scripts.pory"
# 459 "data/maps/LittlerootTown/scripts.pory"
# 818 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 819 "data/maps/LittlerootTown/scripts.pory"
# 460 "data/maps/LittlerootTown/scripts.pory"
# 820 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 4
# 821 "data/maps/LittlerootTown/scripts.pory"
# 461 "data/maps/LittlerootTown/scripts.pory"
# 822 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 823 "data/maps/LittlerootTown/scripts.pory"
# 462 "data/maps/LittlerootTown/scripts.pory"
# 824 "data/maps/LittlerootTown/scripts.pory"
	end
# 825 "data/maps/LittlerootTown/scripts.pory"
# 463 "data/maps/LittlerootTown/scripts.pory"
# 826 "data/maps/LittlerootTown/scripts.pory"

# 827 "data/maps/LittlerootTown/scripts.pory"
# 464 "data/maps/LittlerootTown/scripts.pory"
# 828 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger5::
# 829 "data/maps/LittlerootTown/scripts.pory"
# 465 "data/maps/LittlerootTown/scripts.pory"
# 830 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 831 "data/maps/LittlerootTown/scripts.pory"
# 466 "data/maps/LittlerootTown/scripts.pory"
# 832 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 5
# 833 "data/maps/LittlerootTown/scripts.pory"
# 467 "data/maps/LittlerootTown/scripts.pory"
# 834 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 835 "data/maps/LittlerootTown/scripts.pory"
# 468 "data/maps/LittlerootTown/scripts.pory"
# 836 "data/maps/LittlerootTown/scripts.pory"
	end
# 837 "data/maps/LittlerootTown/scripts.pory"
# 469 "data/maps/LittlerootTown/scripts.pory"
# 838 "data/maps/LittlerootTown/scripts.pory"

# 839 "data/maps/LittlerootTown/scripts.pory"
# 470 "data/maps/LittlerootTown/scripts.pory"
# 840 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger::
# 841 "data/maps/LittlerootTown/scripts.pory"
# 471 "data/maps/LittlerootTown/scripts.pory"
# 842 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 843 "data/maps/LittlerootTown/scripts.pory"
# 472 "data/maps/LittlerootTown/scripts.pory"
# 844 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_MomNoticePlayerMale
# 845 "data/maps/LittlerootTown/scripts.pory"
# 473 "data/maps/LittlerootTown/scripts.pory"
# 846 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_MomNoticePlayerFemale
# 847 "data/maps/LittlerootTown/scripts.pory"
# 474 "data/maps/LittlerootTown/scripts.pory"
# 848 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 849 "data/maps/LittlerootTown/scripts.pory"
# 475 "data/maps/LittlerootTown/scripts.pory"
# 850 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetHomeDoorCoordsMale
# 851 "data/maps/LittlerootTown/scripts.pory"
# 476 "data/maps/LittlerootTown/scripts.pory"
# 852 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_SetHomeDoorCoordsFemale
# 853 "data/maps/LittlerootTown/scripts.pory"
# 477 "data/maps/LittlerootTown/scripts.pory"
# 854 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_WaitPlayer, MSGBOX_DEFAULT
# 855 "data/maps/LittlerootTown/scripts.pory"
# 478 "data/maps/LittlerootTown/scripts.pory"
# 856 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 857 "data/maps/LittlerootTown/scripts.pory"
# 479 "data/maps/LittlerootTown/scripts.pory"
# 858 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 859 "data/maps/LittlerootTown/scripts.pory"
# 480 "data/maps/LittlerootTown/scripts.pory"
# 860 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_MomApproachPlayerMale
# 861 "data/maps/LittlerootTown/scripts.pory"
# 481 "data/maps/LittlerootTown/scripts.pory"
# 862 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_MomApproachPlayerFemale
# 863 "data/maps/LittlerootTown/scripts.pory"
# 482 "data/maps/LittlerootTown/scripts.pory"
# 864 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GiveRunningShoes
# 865 "data/maps/LittlerootTown/scripts.pory"
# 483 "data/maps/LittlerootTown/scripts.pory"
# 866 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 867 "data/maps/LittlerootTown/scripts.pory"
# 484 "data/maps/LittlerootTown/scripts.pory"
# 868 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_MomReturnHomeMale
# 869 "data/maps/LittlerootTown/scripts.pory"
# 485 "data/maps/LittlerootTown/scripts.pory"
# 870 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_MomReturnHomeFemale
# 871 "data/maps/LittlerootTown/scripts.pory"
# 486 "data/maps/LittlerootTown/scripts.pory"
# 872 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_SetReceivedRunningShoes
# 873 "data/maps/LittlerootTown/scripts.pory"
# 487 "data/maps/LittlerootTown/scripts.pory"
# 874 "data/maps/LittlerootTown/scripts.pory"
	end
# 875 "data/maps/LittlerootTown/scripts.pory"
# 488 "data/maps/LittlerootTown/scripts.pory"
# 876 "data/maps/LittlerootTown/scripts.pory"

# 877 "data/maps/LittlerootTown/scripts.pory"
# 489 "data/maps/LittlerootTown/scripts.pory"
# 878 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetHomeDoorCoordsMale::
# 879 "data/maps/LittlerootTown/scripts.pory"
# 490 "data/maps/LittlerootTown/scripts.pory"
# 880 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8009, 5
# 881 "data/maps/LittlerootTown/scripts.pory"
# 491 "data/maps/LittlerootTown/scripts.pory"
# 882 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x800A, 8
# 883 "data/maps/LittlerootTown/scripts.pory"
# 492 "data/maps/LittlerootTown/scripts.pory"
# 884 "data/maps/LittlerootTown/scripts.pory"
	return
# 885 "data/maps/LittlerootTown/scripts.pory"
# 493 "data/maps/LittlerootTown/scripts.pory"
# 886 "data/maps/LittlerootTown/scripts.pory"

# 887 "data/maps/LittlerootTown/scripts.pory"
# 494 "data/maps/LittlerootTown/scripts.pory"
# 888 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetHomeDoorCoordsFemale::
# 889 "data/maps/LittlerootTown/scripts.pory"
# 495 "data/maps/LittlerootTown/scripts.pory"
# 890 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8009, 14
# 891 "data/maps/LittlerootTown/scripts.pory"
# 496 "data/maps/LittlerootTown/scripts.pory"
# 892 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x800A, 8
# 893 "data/maps/LittlerootTown/scripts.pory"
# 497 "data/maps/LittlerootTown/scripts.pory"
# 894 "data/maps/LittlerootTown/scripts.pory"
	return
# 895 "data/maps/LittlerootTown/scripts.pory"
# 498 "data/maps/LittlerootTown/scripts.pory"
# 896 "data/maps/LittlerootTown/scripts.pory"

# 897 "data/maps/LittlerootTown/scripts.pory"
# 499 "data/maps/LittlerootTown/scripts.pory"
# 898 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomNoticePlayerMale::
# 899 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 900 "data/maps/LittlerootTown/scripts.pory"
# 502 "data/maps/LittlerootTown/scripts.pory"
# 901 "data/maps/LittlerootTown/scripts.pory"
	return
# 902 "data/maps/LittlerootTown/scripts.pory"
# 503 "data/maps/LittlerootTown/scripts.pory"
# 903 "data/maps/LittlerootTown/scripts.pory"

# 904 "data/maps/LittlerootTown/scripts.pory"
# 504 "data/maps/LittlerootTown/scripts.pory"
# 905 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomNoticePlayerFemale::
# 906 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 907 "data/maps/LittlerootTown/scripts.pory"
# 507 "data/maps/LittlerootTown/scripts.pory"
# 908 "data/maps/LittlerootTown/scripts.pory"
	return
# 909 "data/maps/LittlerootTown/scripts.pory"
# 508 "data/maps/LittlerootTown/scripts.pory"
# 910 "data/maps/LittlerootTown/scripts.pory"

# 911 "data/maps/LittlerootTown/scripts.pory"
# 509 "data/maps/LittlerootTown/scripts.pory"
# 912 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale::
# 913 "data/maps/LittlerootTown/scripts.pory"
# 510 "data/maps/LittlerootTown/scripts.pory"
# 914 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomApproachPlayer0
# 915 "data/maps/LittlerootTown/scripts.pory"
# 511 "data/maps/LittlerootTown/scripts.pory"
# 916 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomApproachPlayer1
# 917 "data/maps/LittlerootTown/scripts.pory"
# 512 "data/maps/LittlerootTown/scripts.pory"
# 918 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomApproachPlayerMale2
# 919 "data/maps/LittlerootTown/scripts.pory"
# 513 "data/maps/LittlerootTown/scripts.pory"
# 920 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomApproachPlayerMale3
# 921 "data/maps/LittlerootTown/scripts.pory"
# 514 "data/maps/LittlerootTown/scripts.pory"
# 922 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomApproachPlayerMale4
# 923 "data/maps/LittlerootTown/scripts.pory"
# 515 "data/maps/LittlerootTown/scripts.pory"
# 924 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomApproachPlayerMale5
# 925 "data/maps/LittlerootTown/scripts.pory"
# 516 "data/maps/LittlerootTown/scripts.pory"
# 926 "data/maps/LittlerootTown/scripts.pory"
	return
# 927 "data/maps/LittlerootTown/scripts.pory"
# 517 "data/maps/LittlerootTown/scripts.pory"
# 928 "data/maps/LittlerootTown/scripts.pory"

# 929 "data/maps/LittlerootTown/scripts.pory"
# 518 "data/maps/LittlerootTown/scripts.pory"
# 930 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale::
# 931 "data/maps/LittlerootTown/scripts.pory"
# 519 "data/maps/LittlerootTown/scripts.pory"
# 932 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomApproachPlayer0
# 933 "data/maps/LittlerootTown/scripts.pory"
# 520 "data/maps/LittlerootTown/scripts.pory"
# 934 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomApproachPlayer1
# 935 "data/maps/LittlerootTown/scripts.pory"
# 521 "data/maps/LittlerootTown/scripts.pory"
# 936 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomApproachPlayerFemale2
# 937 "data/maps/LittlerootTown/scripts.pory"
# 522 "data/maps/LittlerootTown/scripts.pory"
# 938 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomApproachPlayerFemale3
# 939 "data/maps/LittlerootTown/scripts.pory"
# 523 "data/maps/LittlerootTown/scripts.pory"
# 940 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomApproachPlayerFemale4
# 941 "data/maps/LittlerootTown/scripts.pory"
# 524 "data/maps/LittlerootTown/scripts.pory"
# 942 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomApproachPlayerFemale5
# 943 "data/maps/LittlerootTown/scripts.pory"
# 525 "data/maps/LittlerootTown/scripts.pory"
# 944 "data/maps/LittlerootTown/scripts.pory"
	return
# 945 "data/maps/LittlerootTown/scripts.pory"
# 526 "data/maps/LittlerootTown/scripts.pory"
# 946 "data/maps/LittlerootTown/scripts.pory"

# 947 "data/maps/LittlerootTown/scripts.pory"
# 527 "data/maps/LittlerootTown/scripts.pory"
# 948 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayer0::
# 949 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterDown
# 950 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 951 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 952 "data/maps/LittlerootTown/scripts.pory"
# 532 "data/maps/LittlerootTown/scripts.pory"
# 953 "data/maps/LittlerootTown/scripts.pory"
	return
# 954 "data/maps/LittlerootTown/scripts.pory"
# 533 "data/maps/LittlerootTown/scripts.pory"
# 955 "data/maps/LittlerootTown/scripts.pory"

# 956 "data/maps/LittlerootTown/scripts.pory"
# 534 "data/maps/LittlerootTown/scripts.pory"
# 957 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayer1::
# 958 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterDown
# 959 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 960 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 961 "data/maps/LittlerootTown/scripts.pory"
# 539 "data/maps/LittlerootTown/scripts.pory"
# 962 "data/maps/LittlerootTown/scripts.pory"
	return
# 963 "data/maps/LittlerootTown/scripts.pory"
# 540 "data/maps/LittlerootTown/scripts.pory"
# 964 "data/maps/LittlerootTown/scripts.pory"

# 965 "data/maps/LittlerootTown/scripts.pory"
# 541 "data/maps/LittlerootTown/scripts.pory"
# 966 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale2::
# 967 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 968 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 969 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 970 "data/maps/LittlerootTown/scripts.pory"
# 546 "data/maps/LittlerootTown/scripts.pory"
# 971 "data/maps/LittlerootTown/scripts.pory"
	return
# 972 "data/maps/LittlerootTown/scripts.pory"
# 547 "data/maps/LittlerootTown/scripts.pory"
# 973 "data/maps/LittlerootTown/scripts.pory"

# 974 "data/maps/LittlerootTown/scripts.pory"
# 548 "data/maps/LittlerootTown/scripts.pory"
# 975 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale3::
# 976 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 977 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 978 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 979 "data/maps/LittlerootTown/scripts.pory"
# 553 "data/maps/LittlerootTown/scripts.pory"
# 980 "data/maps/LittlerootTown/scripts.pory"
	return
# 981 "data/maps/LittlerootTown/scripts.pory"
# 554 "data/maps/LittlerootTown/scripts.pory"
# 982 "data/maps/LittlerootTown/scripts.pory"

# 983 "data/maps/LittlerootTown/scripts.pory"
# 555 "data/maps/LittlerootTown/scripts.pory"
# 984 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale4::
# 985 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 986 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 987 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 988 "data/maps/LittlerootTown/scripts.pory"
# 560 "data/maps/LittlerootTown/scripts.pory"
# 989 "data/maps/LittlerootTown/scripts.pory"
	return
# 990 "data/maps/LittlerootTown/scripts.pory"
# 561 "data/maps/LittlerootTown/scripts.pory"
# 991 "data/maps/LittlerootTown/scripts.pory"

# 992 "data/maps/LittlerootTown/scripts.pory"
# 562 "data/maps/LittlerootTown/scripts.pory"
# 993 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale5::
# 994 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 995 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 996 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 997 "data/maps/LittlerootTown/scripts.pory"
# 567 "data/maps/LittlerootTown/scripts.pory"
# 998 "data/maps/LittlerootTown/scripts.pory"
	return
# 999 "data/maps/LittlerootTown/scripts.pory"
# 568 "data/maps/LittlerootTown/scripts.pory"
# 1000 "data/maps/LittlerootTown/scripts.pory"

# 1001 "data/maps/LittlerootTown/scripts.pory"
# 569 "data/maps/LittlerootTown/scripts.pory"
# 1002 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale2::
# 1003 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1004 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1005 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1006 "data/maps/LittlerootTown/scripts.pory"
# 574 "data/maps/LittlerootTown/scripts.pory"
# 1007 "data/maps/LittlerootTown/scripts.pory"
	return
# 1008 "data/maps/LittlerootTown/scripts.pory"
# 575 "data/maps/LittlerootTown/scripts.pory"
# 1009 "data/maps/LittlerootTown/scripts.pory"

# 1010 "data/maps/LittlerootTown/scripts.pory"
# 576 "data/maps/LittlerootTown/scripts.pory"
# 1011 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale3::
# 1012 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1013 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1014 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1015 "data/maps/LittlerootTown/scripts.pory"
# 581 "data/maps/LittlerootTown/scripts.pory"
# 1016 "data/maps/LittlerootTown/scripts.pory"
	return
# 1017 "data/maps/LittlerootTown/scripts.pory"
# 582 "data/maps/LittlerootTown/scripts.pory"
# 1018 "data/maps/LittlerootTown/scripts.pory"

# 1019 "data/maps/LittlerootTown/scripts.pory"
# 583 "data/maps/LittlerootTown/scripts.pory"
# 1020 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale4::
# 1021 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1022 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1023 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1024 "data/maps/LittlerootTown/scripts.pory"
# 588 "data/maps/LittlerootTown/scripts.pory"
# 1025 "data/maps/LittlerootTown/scripts.pory"
	return
# 1026 "data/maps/LittlerootTown/scripts.pory"
# 589 "data/maps/LittlerootTown/scripts.pory"
# 1027 "data/maps/LittlerootTown/scripts.pory"

# 1028 "data/maps/LittlerootTown/scripts.pory"
# 590 "data/maps/LittlerootTown/scripts.pory"
# 1029 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale5::
# 1030 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1031 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1032 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1033 "data/maps/LittlerootTown/scripts.pory"
# 595 "data/maps/LittlerootTown/scripts.pory"
# 1034 "data/maps/LittlerootTown/scripts.pory"
	return
# 1035 "data/maps/LittlerootTown/scripts.pory"
# 596 "data/maps/LittlerootTown/scripts.pory"
# 1036 "data/maps/LittlerootTown/scripts.pory"

# 1037 "data/maps/LittlerootTown/scripts.pory"
# 597 "data/maps/LittlerootTown/scripts.pory"
# 1038 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale::
# 1039 "data/maps/LittlerootTown/scripts.pory"
# 598 "data/maps/LittlerootTown/scripts.pory"
# 1040 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomReturnHome0
# 1041 "data/maps/LittlerootTown/scripts.pory"
# 599 "data/maps/LittlerootTown/scripts.pory"
# 1042 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomReturnHome1
# 1043 "data/maps/LittlerootTown/scripts.pory"
# 600 "data/maps/LittlerootTown/scripts.pory"
# 1044 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomReturnHomeMale2
# 1045 "data/maps/LittlerootTown/scripts.pory"
# 601 "data/maps/LittlerootTown/scripts.pory"
# 1046 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomReturnHomeMale3
# 1047 "data/maps/LittlerootTown/scripts.pory"
# 602 "data/maps/LittlerootTown/scripts.pory"
# 1048 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomReturnHomeMale4
# 1049 "data/maps/LittlerootTown/scripts.pory"
# 603 "data/maps/LittlerootTown/scripts.pory"
# 1050 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomReturnHomeMale5
# 1051 "data/maps/LittlerootTown/scripts.pory"
# 604 "data/maps/LittlerootTown/scripts.pory"
# 1052 "data/maps/LittlerootTown/scripts.pory"
	return
# 1053 "data/maps/LittlerootTown/scripts.pory"
# 605 "data/maps/LittlerootTown/scripts.pory"
# 1054 "data/maps/LittlerootTown/scripts.pory"

# 1055 "data/maps/LittlerootTown/scripts.pory"
# 606 "data/maps/LittlerootTown/scripts.pory"
# 1056 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale::
# 1057 "data/maps/LittlerootTown/scripts.pory"
# 607 "data/maps/LittlerootTown/scripts.pory"
# 1058 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomReturnHome0
# 1059 "data/maps/LittlerootTown/scripts.pory"
# 608 "data/maps/LittlerootTown/scripts.pory"
# 1060 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomReturnHome1
# 1061 "data/maps/LittlerootTown/scripts.pory"
# 609 "data/maps/LittlerootTown/scripts.pory"
# 1062 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomReturnHomeFemale2
# 1063 "data/maps/LittlerootTown/scripts.pory"
# 610 "data/maps/LittlerootTown/scripts.pory"
# 1064 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomReturnHomeFemale3
# 1065 "data/maps/LittlerootTown/scripts.pory"
# 611 "data/maps/LittlerootTown/scripts.pory"
# 1066 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomReturnHomeFemale4
# 1067 "data/maps/LittlerootTown/scripts.pory"
# 612 "data/maps/LittlerootTown/scripts.pory"
# 1068 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomReturnHomeFemale5
# 1069 "data/maps/LittlerootTown/scripts.pory"
# 613 "data/maps/LittlerootTown/scripts.pory"
# 1070 "data/maps/LittlerootTown/scripts.pory"
	return
# 1071 "data/maps/LittlerootTown/scripts.pory"
# 614 "data/maps/LittlerootTown/scripts.pory"
# 1072 "data/maps/LittlerootTown/scripts.pory"

# 1073 "data/maps/LittlerootTown/scripts.pory"
# 615 "data/maps/LittlerootTown/scripts.pory"
# 1074 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHome0::
# 1075 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1076 "data/maps/LittlerootTown/scripts.pory"
# 618 "data/maps/LittlerootTown/scripts.pory"
# 1077 "data/maps/LittlerootTown/scripts.pory"
	return
# 1078 "data/maps/LittlerootTown/scripts.pory"
# 619 "data/maps/LittlerootTown/scripts.pory"
# 1079 "data/maps/LittlerootTown/scripts.pory"

# 1080 "data/maps/LittlerootTown/scripts.pory"
# 620 "data/maps/LittlerootTown/scripts.pory"
# 1081 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHome1::
# 1082 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1083 "data/maps/LittlerootTown/scripts.pory"
# 623 "data/maps/LittlerootTown/scripts.pory"
# 1084 "data/maps/LittlerootTown/scripts.pory"
	return
# 1085 "data/maps/LittlerootTown/scripts.pory"
# 624 "data/maps/LittlerootTown/scripts.pory"
# 1086 "data/maps/LittlerootTown/scripts.pory"

# 1087 "data/maps/LittlerootTown/scripts.pory"
# 625 "data/maps/LittlerootTown/scripts.pory"
# 1088 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale2::
# 1089 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1090 "data/maps/LittlerootTown/scripts.pory"
# 628 "data/maps/LittlerootTown/scripts.pory"
# 1091 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1092 "data/maps/LittlerootTown/scripts.pory"
# 629 "data/maps/LittlerootTown/scripts.pory"
# 1093 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1094 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1095 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1096 "data/maps/LittlerootTown/scripts.pory"
# 634 "data/maps/LittlerootTown/scripts.pory"
# 1097 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1098 "data/maps/LittlerootTown/scripts.pory"
# 635 "data/maps/LittlerootTown/scripts.pory"
# 1099 "data/maps/LittlerootTown/scripts.pory"
	return
# 1100 "data/maps/LittlerootTown/scripts.pory"
# 636 "data/maps/LittlerootTown/scripts.pory"
# 1101 "data/maps/LittlerootTown/scripts.pory"

# 1102 "data/maps/LittlerootTown/scripts.pory"
# 637 "data/maps/LittlerootTown/scripts.pory"
# 1103 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale3::
# 1104 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1105 "data/maps/LittlerootTown/scripts.pory"
# 640 "data/maps/LittlerootTown/scripts.pory"
# 1106 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1107 "data/maps/LittlerootTown/scripts.pory"
# 641 "data/maps/LittlerootTown/scripts.pory"
# 1108 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1109 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1110 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1111 "data/maps/LittlerootTown/scripts.pory"
# 646 "data/maps/LittlerootTown/scripts.pory"
# 1112 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1113 "data/maps/LittlerootTown/scripts.pory"
# 647 "data/maps/LittlerootTown/scripts.pory"
# 1114 "data/maps/LittlerootTown/scripts.pory"
	return
# 1115 "data/maps/LittlerootTown/scripts.pory"
# 648 "data/maps/LittlerootTown/scripts.pory"
# 1116 "data/maps/LittlerootTown/scripts.pory"

# 1117 "data/maps/LittlerootTown/scripts.pory"
# 649 "data/maps/LittlerootTown/scripts.pory"
# 1118 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale4::
# 1119 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1120 "data/maps/LittlerootTown/scripts.pory"
# 652 "data/maps/LittlerootTown/scripts.pory"
# 1121 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1122 "data/maps/LittlerootTown/scripts.pory"
# 653 "data/maps/LittlerootTown/scripts.pory"
# 1123 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1124 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1125 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1126 "data/maps/LittlerootTown/scripts.pory"
# 658 "data/maps/LittlerootTown/scripts.pory"
# 1127 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1128 "data/maps/LittlerootTown/scripts.pory"
# 659 "data/maps/LittlerootTown/scripts.pory"
# 1129 "data/maps/LittlerootTown/scripts.pory"
	return
# 1130 "data/maps/LittlerootTown/scripts.pory"
# 660 "data/maps/LittlerootTown/scripts.pory"
# 1131 "data/maps/LittlerootTown/scripts.pory"

# 1132 "data/maps/LittlerootTown/scripts.pory"
# 661 "data/maps/LittlerootTown/scripts.pory"
# 1133 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale5::
# 1134 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1135 "data/maps/LittlerootTown/scripts.pory"
# 664 "data/maps/LittlerootTown/scripts.pory"
# 1136 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1137 "data/maps/LittlerootTown/scripts.pory"
# 665 "data/maps/LittlerootTown/scripts.pory"
# 1138 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1139 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1140 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1141 "data/maps/LittlerootTown/scripts.pory"
# 670 "data/maps/LittlerootTown/scripts.pory"
# 1142 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1143 "data/maps/LittlerootTown/scripts.pory"
# 671 "data/maps/LittlerootTown/scripts.pory"
# 1144 "data/maps/LittlerootTown/scripts.pory"
	return
# 1145 "data/maps/LittlerootTown/scripts.pory"
# 672 "data/maps/LittlerootTown/scripts.pory"
# 1146 "data/maps/LittlerootTown/scripts.pory"

# 1147 "data/maps/LittlerootTown/scripts.pory"
# 673 "data/maps/LittlerootTown/scripts.pory"
# 1148 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale2::
# 1149 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1150 "data/maps/LittlerootTown/scripts.pory"
# 676 "data/maps/LittlerootTown/scripts.pory"
# 1151 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1152 "data/maps/LittlerootTown/scripts.pory"
# 677 "data/maps/LittlerootTown/scripts.pory"
# 1153 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1154 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1155 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1156 "data/maps/LittlerootTown/scripts.pory"
# 682 "data/maps/LittlerootTown/scripts.pory"
# 1157 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1158 "data/maps/LittlerootTown/scripts.pory"
# 683 "data/maps/LittlerootTown/scripts.pory"
# 1159 "data/maps/LittlerootTown/scripts.pory"
	return
# 1160 "data/maps/LittlerootTown/scripts.pory"
# 684 "data/maps/LittlerootTown/scripts.pory"
# 1161 "data/maps/LittlerootTown/scripts.pory"

# 1162 "data/maps/LittlerootTown/scripts.pory"
# 685 "data/maps/LittlerootTown/scripts.pory"
# 1163 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale3::
# 1164 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1165 "data/maps/LittlerootTown/scripts.pory"
# 688 "data/maps/LittlerootTown/scripts.pory"
# 1166 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1167 "data/maps/LittlerootTown/scripts.pory"
# 689 "data/maps/LittlerootTown/scripts.pory"
# 1168 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1169 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1170 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1171 "data/maps/LittlerootTown/scripts.pory"
# 694 "data/maps/LittlerootTown/scripts.pory"
# 1172 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1173 "data/maps/LittlerootTown/scripts.pory"
# 695 "data/maps/LittlerootTown/scripts.pory"
# 1174 "data/maps/LittlerootTown/scripts.pory"
	return
# 1175 "data/maps/LittlerootTown/scripts.pory"
# 696 "data/maps/LittlerootTown/scripts.pory"
# 1176 "data/maps/LittlerootTown/scripts.pory"

# 1177 "data/maps/LittlerootTown/scripts.pory"
# 697 "data/maps/LittlerootTown/scripts.pory"
# 1178 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale4::
# 1179 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1180 "data/maps/LittlerootTown/scripts.pory"
# 700 "data/maps/LittlerootTown/scripts.pory"
# 1181 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1182 "data/maps/LittlerootTown/scripts.pory"
# 701 "data/maps/LittlerootTown/scripts.pory"
# 1183 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1184 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1185 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1186 "data/maps/LittlerootTown/scripts.pory"
# 706 "data/maps/LittlerootTown/scripts.pory"
# 1187 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1188 "data/maps/LittlerootTown/scripts.pory"
# 707 "data/maps/LittlerootTown/scripts.pory"
# 1189 "data/maps/LittlerootTown/scripts.pory"
	return
# 1190 "data/maps/LittlerootTown/scripts.pory"
# 708 "data/maps/LittlerootTown/scripts.pory"
# 1191 "data/maps/LittlerootTown/scripts.pory"

# 1192 "data/maps/LittlerootTown/scripts.pory"
# 709 "data/maps/LittlerootTown/scripts.pory"
# 1193 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale5::
# 1194 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1195 "data/maps/LittlerootTown/scripts.pory"
# 712 "data/maps/LittlerootTown/scripts.pory"
# 1196 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1197 "data/maps/LittlerootTown/scripts.pory"
# 713 "data/maps/LittlerootTown/scripts.pory"
# 1198 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1199 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1200 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1201 "data/maps/LittlerootTown/scripts.pory"
# 718 "data/maps/LittlerootTown/scripts.pory"
# 1202 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1203 "data/maps/LittlerootTown/scripts.pory"
# 719 "data/maps/LittlerootTown/scripts.pory"
# 1204 "data/maps/LittlerootTown/scripts.pory"
	return
# 1205 "data/maps/LittlerootTown/scripts.pory"
# 720 "data/maps/LittlerootTown/scripts.pory"
# 1206 "data/maps/LittlerootTown/scripts.pory"

# 1207 "data/maps/LittlerootTown/scripts.pory"
# 721 "data/maps/LittlerootTown/scripts.pory"
# 1208 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayer0:
# 1209 "data/maps/LittlerootTown/scripts.pory"
# 722 "data/maps/LittlerootTown/scripts.pory"
# 1210 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1211 "data/maps/LittlerootTown/scripts.pory"
# 723 "data/maps/LittlerootTown/scripts.pory"
# 1212 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1213 "data/maps/LittlerootTown/scripts.pory"
# 724 "data/maps/LittlerootTown/scripts.pory"
# 1214 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1215 "data/maps/LittlerootTown/scripts.pory"
# 725 "data/maps/LittlerootTown/scripts.pory"
# 1216 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1217 "data/maps/LittlerootTown/scripts.pory"
# 726 "data/maps/LittlerootTown/scripts.pory"
# 1218 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1219 "data/maps/LittlerootTown/scripts.pory"
# 727 "data/maps/LittlerootTown/scripts.pory"
# 1220 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1221 "data/maps/LittlerootTown/scripts.pory"
# 728 "data/maps/LittlerootTown/scripts.pory"
# 1222 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1223 "data/maps/LittlerootTown/scripts.pory"
# 729 "data/maps/LittlerootTown/scripts.pory"
# 1224 "data/maps/LittlerootTown/scripts.pory"

# 1225 "data/maps/LittlerootTown/scripts.pory"
# 730 "data/maps/LittlerootTown/scripts.pory"
# 1226 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayer1:
# 1227 "data/maps/LittlerootTown/scripts.pory"
# 731 "data/maps/LittlerootTown/scripts.pory"
# 1228 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1229 "data/maps/LittlerootTown/scripts.pory"
# 732 "data/maps/LittlerootTown/scripts.pory"
# 1230 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1231 "data/maps/LittlerootTown/scripts.pory"
# 733 "data/maps/LittlerootTown/scripts.pory"
# 1232 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1233 "data/maps/LittlerootTown/scripts.pory"
# 734 "data/maps/LittlerootTown/scripts.pory"
# 1234 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1235 "data/maps/LittlerootTown/scripts.pory"
# 735 "data/maps/LittlerootTown/scripts.pory"
# 1236 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1237 "data/maps/LittlerootTown/scripts.pory"
# 736 "data/maps/LittlerootTown/scripts.pory"
# 1238 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1239 "data/maps/LittlerootTown/scripts.pory"
# 737 "data/maps/LittlerootTown/scripts.pory"
# 1240 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1241 "data/maps/LittlerootTown/scripts.pory"
# 738 "data/maps/LittlerootTown/scripts.pory"
# 1242 "data/maps/LittlerootTown/scripts.pory"

# 1243 "data/maps/LittlerootTown/scripts.pory"
# 739 "data/maps/LittlerootTown/scripts.pory"
# 1244 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale2:
# 1245 "data/maps/LittlerootTown/scripts.pory"
# 740 "data/maps/LittlerootTown/scripts.pory"
# 1246 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1247 "data/maps/LittlerootTown/scripts.pory"
# 741 "data/maps/LittlerootTown/scripts.pory"
# 1248 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1249 "data/maps/LittlerootTown/scripts.pory"
# 742 "data/maps/LittlerootTown/scripts.pory"
# 1250 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1251 "data/maps/LittlerootTown/scripts.pory"
# 743 "data/maps/LittlerootTown/scripts.pory"
# 1252 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1253 "data/maps/LittlerootTown/scripts.pory"
# 744 "data/maps/LittlerootTown/scripts.pory"
# 1254 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1255 "data/maps/LittlerootTown/scripts.pory"
# 745 "data/maps/LittlerootTown/scripts.pory"
# 1256 "data/maps/LittlerootTown/scripts.pory"

# 1257 "data/maps/LittlerootTown/scripts.pory"
# 746 "data/maps/LittlerootTown/scripts.pory"
# 1258 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale3:
# 1259 "data/maps/LittlerootTown/scripts.pory"
# 747 "data/maps/LittlerootTown/scripts.pory"
# 1260 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1261 "data/maps/LittlerootTown/scripts.pory"
# 748 "data/maps/LittlerootTown/scripts.pory"
# 1262 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1263 "data/maps/LittlerootTown/scripts.pory"
# 749 "data/maps/LittlerootTown/scripts.pory"
# 1264 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1265 "data/maps/LittlerootTown/scripts.pory"
# 750 "data/maps/LittlerootTown/scripts.pory"
# 1266 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1267 "data/maps/LittlerootTown/scripts.pory"
# 751 "data/maps/LittlerootTown/scripts.pory"
# 1268 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1269 "data/maps/LittlerootTown/scripts.pory"
# 752 "data/maps/LittlerootTown/scripts.pory"
# 1270 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1271 "data/maps/LittlerootTown/scripts.pory"
# 753 "data/maps/LittlerootTown/scripts.pory"
# 1272 "data/maps/LittlerootTown/scripts.pory"

# 1273 "data/maps/LittlerootTown/scripts.pory"
# 754 "data/maps/LittlerootTown/scripts.pory"
# 1274 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale4:
# 1275 "data/maps/LittlerootTown/scripts.pory"
# 755 "data/maps/LittlerootTown/scripts.pory"
# 1276 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1277 "data/maps/LittlerootTown/scripts.pory"
# 756 "data/maps/LittlerootTown/scripts.pory"
# 1278 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1279 "data/maps/LittlerootTown/scripts.pory"
# 757 "data/maps/LittlerootTown/scripts.pory"
# 1280 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1281 "data/maps/LittlerootTown/scripts.pory"
# 758 "data/maps/LittlerootTown/scripts.pory"
# 1282 "data/maps/LittlerootTown/scripts.pory"

# 1283 "data/maps/LittlerootTown/scripts.pory"
# 759 "data/maps/LittlerootTown/scripts.pory"
# 1284 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale5:
# 1285 "data/maps/LittlerootTown/scripts.pory"
# 760 "data/maps/LittlerootTown/scripts.pory"
# 1286 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1287 "data/maps/LittlerootTown/scripts.pory"
# 761 "data/maps/LittlerootTown/scripts.pory"
# 1288 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1289 "data/maps/LittlerootTown/scripts.pory"
# 762 "data/maps/LittlerootTown/scripts.pory"
# 1290 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1291 "data/maps/LittlerootTown/scripts.pory"
# 763 "data/maps/LittlerootTown/scripts.pory"
# 1292 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1293 "data/maps/LittlerootTown/scripts.pory"
# 764 "data/maps/LittlerootTown/scripts.pory"
# 1294 "data/maps/LittlerootTown/scripts.pory"

# 1295 "data/maps/LittlerootTown/scripts.pory"
# 765 "data/maps/LittlerootTown/scripts.pory"
# 1296 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale2:
# 1297 "data/maps/LittlerootTown/scripts.pory"
# 766 "data/maps/LittlerootTown/scripts.pory"
# 1298 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1299 "data/maps/LittlerootTown/scripts.pory"
# 767 "data/maps/LittlerootTown/scripts.pory"
# 1300 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1301 "data/maps/LittlerootTown/scripts.pory"
# 768 "data/maps/LittlerootTown/scripts.pory"
# 1302 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1303 "data/maps/LittlerootTown/scripts.pory"
# 769 "data/maps/LittlerootTown/scripts.pory"
# 1304 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1305 "data/maps/LittlerootTown/scripts.pory"
# 770 "data/maps/LittlerootTown/scripts.pory"
# 1306 "data/maps/LittlerootTown/scripts.pory"

# 1307 "data/maps/LittlerootTown/scripts.pory"
# 771 "data/maps/LittlerootTown/scripts.pory"
# 1308 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale3:
# 1309 "data/maps/LittlerootTown/scripts.pory"
# 772 "data/maps/LittlerootTown/scripts.pory"
# 1310 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1311 "data/maps/LittlerootTown/scripts.pory"
# 773 "data/maps/LittlerootTown/scripts.pory"
# 1312 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1313 "data/maps/LittlerootTown/scripts.pory"
# 774 "data/maps/LittlerootTown/scripts.pory"
# 1314 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1315 "data/maps/LittlerootTown/scripts.pory"
# 775 "data/maps/LittlerootTown/scripts.pory"
# 1316 "data/maps/LittlerootTown/scripts.pory"

# 1317 "data/maps/LittlerootTown/scripts.pory"
# 776 "data/maps/LittlerootTown/scripts.pory"
# 1318 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale4:
# 1319 "data/maps/LittlerootTown/scripts.pory"
# 777 "data/maps/LittlerootTown/scripts.pory"
# 1320 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1321 "data/maps/LittlerootTown/scripts.pory"
# 778 "data/maps/LittlerootTown/scripts.pory"
# 1322 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1323 "data/maps/LittlerootTown/scripts.pory"
# 779 "data/maps/LittlerootTown/scripts.pory"
# 1324 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1325 "data/maps/LittlerootTown/scripts.pory"
# 780 "data/maps/LittlerootTown/scripts.pory"
# 1326 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1327 "data/maps/LittlerootTown/scripts.pory"
# 781 "data/maps/LittlerootTown/scripts.pory"
# 1328 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1329 "data/maps/LittlerootTown/scripts.pory"
# 782 "data/maps/LittlerootTown/scripts.pory"
# 1330 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1331 "data/maps/LittlerootTown/scripts.pory"
# 783 "data/maps/LittlerootTown/scripts.pory"
# 1332 "data/maps/LittlerootTown/scripts.pory"

# 1333 "data/maps/LittlerootTown/scripts.pory"
# 784 "data/maps/LittlerootTown/scripts.pory"
# 1334 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale5:
# 1335 "data/maps/LittlerootTown/scripts.pory"
# 785 "data/maps/LittlerootTown/scripts.pory"
# 1336 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1337 "data/maps/LittlerootTown/scripts.pory"
# 786 "data/maps/LittlerootTown/scripts.pory"
# 1338 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1339 "data/maps/LittlerootTown/scripts.pory"
# 787 "data/maps/LittlerootTown/scripts.pory"
# 1340 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1341 "data/maps/LittlerootTown/scripts.pory"
# 788 "data/maps/LittlerootTown/scripts.pory"
# 1342 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1343 "data/maps/LittlerootTown/scripts.pory"
# 789 "data/maps/LittlerootTown/scripts.pory"
# 1344 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1345 "data/maps/LittlerootTown/scripts.pory"
# 790 "data/maps/LittlerootTown/scripts.pory"
# 1346 "data/maps/LittlerootTown/scripts.pory"

# 1347 "data/maps/LittlerootTown/scripts.pory"
# 791 "data/maps/LittlerootTown/scripts.pory"
# 1348 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHome0:
# 1349 "data/maps/LittlerootTown/scripts.pory"
# 792 "data/maps/LittlerootTown/scripts.pory"
# 1350 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1351 "data/maps/LittlerootTown/scripts.pory"
# 793 "data/maps/LittlerootTown/scripts.pory"
# 1352 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1353 "data/maps/LittlerootTown/scripts.pory"
# 794 "data/maps/LittlerootTown/scripts.pory"
# 1354 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1355 "data/maps/LittlerootTown/scripts.pory"
# 795 "data/maps/LittlerootTown/scripts.pory"
# 1356 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1357 "data/maps/LittlerootTown/scripts.pory"
# 796 "data/maps/LittlerootTown/scripts.pory"
# 1358 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1359 "data/maps/LittlerootTown/scripts.pory"
# 797 "data/maps/LittlerootTown/scripts.pory"
# 1360 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1361 "data/maps/LittlerootTown/scripts.pory"
# 798 "data/maps/LittlerootTown/scripts.pory"
# 1362 "data/maps/LittlerootTown/scripts.pory"

# 1363 "data/maps/LittlerootTown/scripts.pory"
# 799 "data/maps/LittlerootTown/scripts.pory"
# 1364 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHome1:
# 1365 "data/maps/LittlerootTown/scripts.pory"
# 800 "data/maps/LittlerootTown/scripts.pory"
# 1366 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1367 "data/maps/LittlerootTown/scripts.pory"
# 801 "data/maps/LittlerootTown/scripts.pory"
# 1368 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1369 "data/maps/LittlerootTown/scripts.pory"
# 802 "data/maps/LittlerootTown/scripts.pory"
# 1370 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1371 "data/maps/LittlerootTown/scripts.pory"
# 803 "data/maps/LittlerootTown/scripts.pory"
# 1372 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1373 "data/maps/LittlerootTown/scripts.pory"
# 804 "data/maps/LittlerootTown/scripts.pory"
# 1374 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1375 "data/maps/LittlerootTown/scripts.pory"
# 805 "data/maps/LittlerootTown/scripts.pory"
# 1376 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1377 "data/maps/LittlerootTown/scripts.pory"
# 806 "data/maps/LittlerootTown/scripts.pory"
# 1378 "data/maps/LittlerootTown/scripts.pory"

# 1379 "data/maps/LittlerootTown/scripts.pory"
# 807 "data/maps/LittlerootTown/scripts.pory"
# 1380 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale2:
# 1381 "data/maps/LittlerootTown/scripts.pory"
# 808 "data/maps/LittlerootTown/scripts.pory"
# 1382 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1383 "data/maps/LittlerootTown/scripts.pory"
# 809 "data/maps/LittlerootTown/scripts.pory"
# 1384 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1385 "data/maps/LittlerootTown/scripts.pory"
# 810 "data/maps/LittlerootTown/scripts.pory"
# 1386 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1387 "data/maps/LittlerootTown/scripts.pory"
# 811 "data/maps/LittlerootTown/scripts.pory"
# 1388 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1389 "data/maps/LittlerootTown/scripts.pory"
# 812 "data/maps/LittlerootTown/scripts.pory"
# 1390 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1391 "data/maps/LittlerootTown/scripts.pory"
# 813 "data/maps/LittlerootTown/scripts.pory"
# 1392 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1393 "data/maps/LittlerootTown/scripts.pory"
# 814 "data/maps/LittlerootTown/scripts.pory"
# 1394 "data/maps/LittlerootTown/scripts.pory"

# 1395 "data/maps/LittlerootTown/scripts.pory"
# 815 "data/maps/LittlerootTown/scripts.pory"
# 1396 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale3:
# 1397 "data/maps/LittlerootTown/scripts.pory"
# 816 "data/maps/LittlerootTown/scripts.pory"
# 1398 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1399 "data/maps/LittlerootTown/scripts.pory"
# 817 "data/maps/LittlerootTown/scripts.pory"
# 1400 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1401 "data/maps/LittlerootTown/scripts.pory"
# 818 "data/maps/LittlerootTown/scripts.pory"
# 1402 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1403 "data/maps/LittlerootTown/scripts.pory"
# 819 "data/maps/LittlerootTown/scripts.pory"
# 1404 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1405 "data/maps/LittlerootTown/scripts.pory"
# 820 "data/maps/LittlerootTown/scripts.pory"
# 1406 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1407 "data/maps/LittlerootTown/scripts.pory"
# 821 "data/maps/LittlerootTown/scripts.pory"
# 1408 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1409 "data/maps/LittlerootTown/scripts.pory"
# 822 "data/maps/LittlerootTown/scripts.pory"
# 1410 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1411 "data/maps/LittlerootTown/scripts.pory"
# 823 "data/maps/LittlerootTown/scripts.pory"
# 1412 "data/maps/LittlerootTown/scripts.pory"

# 1413 "data/maps/LittlerootTown/scripts.pory"
# 824 "data/maps/LittlerootTown/scripts.pory"
# 1414 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale4:
# 1415 "data/maps/LittlerootTown/scripts.pory"
# 825 "data/maps/LittlerootTown/scripts.pory"
# 1416 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1417 "data/maps/LittlerootTown/scripts.pory"
# 826 "data/maps/LittlerootTown/scripts.pory"
# 1418 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1419 "data/maps/LittlerootTown/scripts.pory"
# 827 "data/maps/LittlerootTown/scripts.pory"
# 1420 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1421 "data/maps/LittlerootTown/scripts.pory"
# 828 "data/maps/LittlerootTown/scripts.pory"
# 1422 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1423 "data/maps/LittlerootTown/scripts.pory"
# 829 "data/maps/LittlerootTown/scripts.pory"
# 1424 "data/maps/LittlerootTown/scripts.pory"

# 1425 "data/maps/LittlerootTown/scripts.pory"
# 830 "data/maps/LittlerootTown/scripts.pory"
# 1426 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale5:
# 1427 "data/maps/LittlerootTown/scripts.pory"
# 831 "data/maps/LittlerootTown/scripts.pory"
# 1428 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1429 "data/maps/LittlerootTown/scripts.pory"
# 832 "data/maps/LittlerootTown/scripts.pory"
# 1430 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1431 "data/maps/LittlerootTown/scripts.pory"
# 833 "data/maps/LittlerootTown/scripts.pory"
# 1432 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1433 "data/maps/LittlerootTown/scripts.pory"
# 834 "data/maps/LittlerootTown/scripts.pory"
# 1434 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1435 "data/maps/LittlerootTown/scripts.pory"
# 835 "data/maps/LittlerootTown/scripts.pory"
# 1436 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1437 "data/maps/LittlerootTown/scripts.pory"
# 836 "data/maps/LittlerootTown/scripts.pory"
# 1438 "data/maps/LittlerootTown/scripts.pory"

# 1439 "data/maps/LittlerootTown/scripts.pory"
# 837 "data/maps/LittlerootTown/scripts.pory"
# 1440 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale2:
# 1441 "data/maps/LittlerootTown/scripts.pory"
# 838 "data/maps/LittlerootTown/scripts.pory"
# 1442 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1443 "data/maps/LittlerootTown/scripts.pory"
# 839 "data/maps/LittlerootTown/scripts.pory"
# 1444 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1445 "data/maps/LittlerootTown/scripts.pory"
# 840 "data/maps/LittlerootTown/scripts.pory"
# 1446 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1447 "data/maps/LittlerootTown/scripts.pory"
# 841 "data/maps/LittlerootTown/scripts.pory"
# 1448 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1449 "data/maps/LittlerootTown/scripts.pory"
# 842 "data/maps/LittlerootTown/scripts.pory"
# 1450 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1451 "data/maps/LittlerootTown/scripts.pory"
# 843 "data/maps/LittlerootTown/scripts.pory"
# 1452 "data/maps/LittlerootTown/scripts.pory"

# 1453 "data/maps/LittlerootTown/scripts.pory"
# 844 "data/maps/LittlerootTown/scripts.pory"
# 1454 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale3:
# 1455 "data/maps/LittlerootTown/scripts.pory"
# 845 "data/maps/LittlerootTown/scripts.pory"
# 1456 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1457 "data/maps/LittlerootTown/scripts.pory"
# 846 "data/maps/LittlerootTown/scripts.pory"
# 1458 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1459 "data/maps/LittlerootTown/scripts.pory"
# 847 "data/maps/LittlerootTown/scripts.pory"
# 1460 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1461 "data/maps/LittlerootTown/scripts.pory"
# 848 "data/maps/LittlerootTown/scripts.pory"
# 1462 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1463 "data/maps/LittlerootTown/scripts.pory"
# 849 "data/maps/LittlerootTown/scripts.pory"
# 1464 "data/maps/LittlerootTown/scripts.pory"

# 1465 "data/maps/LittlerootTown/scripts.pory"
# 850 "data/maps/LittlerootTown/scripts.pory"
# 1466 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale4:
# 1467 "data/maps/LittlerootTown/scripts.pory"
# 851 "data/maps/LittlerootTown/scripts.pory"
# 1468 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1469 "data/maps/LittlerootTown/scripts.pory"
# 852 "data/maps/LittlerootTown/scripts.pory"
# 1470 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1471 "data/maps/LittlerootTown/scripts.pory"
# 853 "data/maps/LittlerootTown/scripts.pory"
# 1472 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1473 "data/maps/LittlerootTown/scripts.pory"
# 854 "data/maps/LittlerootTown/scripts.pory"
# 1474 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1475 "data/maps/LittlerootTown/scripts.pory"
# 855 "data/maps/LittlerootTown/scripts.pory"
# 1476 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1477 "data/maps/LittlerootTown/scripts.pory"
# 856 "data/maps/LittlerootTown/scripts.pory"
# 1478 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1479 "data/maps/LittlerootTown/scripts.pory"
# 857 "data/maps/LittlerootTown/scripts.pory"
# 1480 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1481 "data/maps/LittlerootTown/scripts.pory"
# 858 "data/maps/LittlerootTown/scripts.pory"
# 1482 "data/maps/LittlerootTown/scripts.pory"

# 1483 "data/maps/LittlerootTown/scripts.pory"
# 859 "data/maps/LittlerootTown/scripts.pory"
# 1484 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale5:
# 1485 "data/maps/LittlerootTown/scripts.pory"
# 860 "data/maps/LittlerootTown/scripts.pory"
# 1486 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1487 "data/maps/LittlerootTown/scripts.pory"
# 861 "data/maps/LittlerootTown/scripts.pory"
# 1488 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1489 "data/maps/LittlerootTown/scripts.pory"
# 862 "data/maps/LittlerootTown/scripts.pory"
# 1490 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1491 "data/maps/LittlerootTown/scripts.pory"
# 863 "data/maps/LittlerootTown/scripts.pory"
# 1492 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1493 "data/maps/LittlerootTown/scripts.pory"
# 864 "data/maps/LittlerootTown/scripts.pory"
# 1494 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1495 "data/maps/LittlerootTown/scripts.pory"
# 865 "data/maps/LittlerootTown/scripts.pory"
# 1496 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1497 "data/maps/LittlerootTown/scripts.pory"
# 866 "data/maps/LittlerootTown/scripts.pory"
# 1498 "data/maps/LittlerootTown/scripts.pory"

# 1499 "data/maps/LittlerootTown/scripts.pory"
# 867 "data/maps/LittlerootTown/scripts.pory"
# 1500 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomExitThroughDoor:
# 1501 "data/maps/LittlerootTown/scripts.pory"
# 868 "data/maps/LittlerootTown/scripts.pory"
# 1502 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1503 "data/maps/LittlerootTown/scripts.pory"
# 869 "data/maps/LittlerootTown/scripts.pory"
# 1504 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1505 "data/maps/LittlerootTown/scripts.pory"
# 870 "data/maps/LittlerootTown/scripts.pory"
# 1506 "data/maps/LittlerootTown/scripts.pory"

# 1507 "data/maps/LittlerootTown/scripts.pory"
# 871 "data/maps/LittlerootTown/scripts.pory"
# 1508 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_Mom::
# 1509 "data/maps/LittlerootTown/scripts.pory"
# 872 "data/maps/LittlerootTown/scripts.pory"
# 1510 "data/maps/LittlerootTown/scripts.pory"
	lock
# 1511 "data/maps/LittlerootTown/scripts.pory"
# 873 "data/maps/LittlerootTown/scripts.pory"
# 1512 "data/maps/LittlerootTown/scripts.pory"
	faceplayer
# 1513 "data/maps/LittlerootTown/scripts.pory"
# 874 "data/maps/LittlerootTown/scripts.pory"
# 1514 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 1515 "data/maps/LittlerootTown/scripts.pory"
# 875 "data/maps/LittlerootTown/scripts.pory"
# 1516 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetHomeDoorCoordsMale
# 1517 "data/maps/LittlerootTown/scripts.pory"
# 876 "data/maps/LittlerootTown/scripts.pory"
# 1518 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_SetHomeDoorCoordsFemale
# 1519 "data/maps/LittlerootTown/scripts.pory"
# 877 "data/maps/LittlerootTown/scripts.pory"
# 1520 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GiveRunningShoes
# 1521 "data/maps/LittlerootTown/scripts.pory"
# 878 "data/maps/LittlerootTown/scripts.pory"
# 1522 "data/maps/LittlerootTown/scripts.pory"
# 879 "data/maps/LittlerootTown/scripts.pory"
# 1523 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1524 "data/maps/LittlerootTown/scripts.pory"
# 880 "data/maps/LittlerootTown/scripts.pory"
# 1525 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1526 "data/maps/LittlerootTown/scripts.pory"
# 881 "data/maps/LittlerootTown/scripts.pory"
# 1527 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1528 "data/maps/LittlerootTown/scripts.pory"
# 882 "data/maps/LittlerootTown/scripts.pory"
# 1529 "data/maps/LittlerootTown/scripts.pory"
# 883 "data/maps/LittlerootTown/scripts.pory"
# 1530 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1531 "data/maps/LittlerootTown/scripts.pory"
# 884 "data/maps/LittlerootTown/scripts.pory"
# 1532 "data/maps/LittlerootTown/scripts.pory"
# 885 "data/maps/LittlerootTown/scripts.pory"
# 1533 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1534 "data/maps/LittlerootTown/scripts.pory"
# 886 "data/maps/LittlerootTown/scripts.pory"
# 1535 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1536 "data/maps/LittlerootTown/scripts.pory"
# 887 "data/maps/LittlerootTown/scripts.pory"
# 1537 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_SetReceivedRunningShoes
# 1538 "data/maps/LittlerootTown/scripts.pory"
# 888 "data/maps/LittlerootTown/scripts.pory"
# 1539 "data/maps/LittlerootTown/scripts.pory"
	end
# 1540 "data/maps/LittlerootTown/scripts.pory"
# 889 "data/maps/LittlerootTown/scripts.pory"
# 1541 "data/maps/LittlerootTown/scripts.pory"

# 1542 "data/maps/LittlerootTown/scripts.pory"
# 890 "data/maps/LittlerootTown/scripts.pory"
# 1543 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetReceivedRunningShoes::
# 1544 "data/maps/LittlerootTown/scripts.pory"
# 891 "data/maps/LittlerootTown/scripts.pory"
# 1545 "data/maps/LittlerootTown/scripts.pory"
# 892 "data/maps/LittlerootTown/scripts.pory"
# 1546 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_SYS_B_DASH
# 1547 "data/maps/LittlerootTown/scripts.pory"
# 893 "data/maps/LittlerootTown/scripts.pory"
# 1548 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_TOWN_STATE, 4
# 1549 "data/maps/LittlerootTown/scripts.pory"
# 894 "data/maps/LittlerootTown/scripts.pory"
# 1550 "data/maps/LittlerootTown/scripts.pory"
	release
# 1551 "data/maps/LittlerootTown/scripts.pory"
# 895 "data/maps/LittlerootTown/scripts.pory"
# 1552 "data/maps/LittlerootTown/scripts.pory"
	end
# 1553 "data/maps/LittlerootTown/scripts.pory"
# 896 "data/maps/LittlerootTown/scripts.pory"
# 1554 "data/maps/LittlerootTown/scripts.pory"

# 1555 "data/maps/LittlerootTown/scripts.pory"
# 897 "data/maps/LittlerootTown/scripts.pory"
# 1556 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoes::
# 1557 "data/maps/LittlerootTown/scripts.pory"
# 898 "data/maps/LittlerootTown/scripts.pory"
# 1558 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_WearTheseRunningShoes, MSGBOX_DEFAULT
# 1559 "data/maps/LittlerootTown/scripts.pory"
# 899 "data/maps/LittlerootTown/scripts.pory"
# 1560 "data/maps/LittlerootTown/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1561 "data/maps/LittlerootTown/scripts.pory"
# 900 "data/maps/LittlerootTown/scripts.pory"
# 1562 "data/maps/LittlerootTown/scripts.pory"
	message LittlerootTown_Text_SwitchShoesWithRunningShoes
# 1563 "data/maps/LittlerootTown/scripts.pory"
# 901 "data/maps/LittlerootTown/scripts.pory"
# 1564 "data/maps/LittlerootTown/scripts.pory"
	waitfanfare
# 1565 "data/maps/LittlerootTown/scripts.pory"
# 902 "data/maps/LittlerootTown/scripts.pory"
# 1566 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_RECEIVED_RUNNING_SHOES
# 1567 "data/maps/LittlerootTown/scripts.pory"
# 903 "data/maps/LittlerootTown/scripts.pory"
# 1568 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ExplainRunningShoes, MSGBOX_DEFAULT
# 1569 "data/maps/LittlerootTown/scripts.pory"
# 904 "data/maps/LittlerootTown/scripts.pory"
# 1570 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ComeHomeIfAnythingHappens, MSGBOX_DEFAULT
# 1571 "data/maps/LittlerootTown/scripts.pory"
# 905 "data/maps/LittlerootTown/scripts.pory"
# 1572 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 1573 "data/maps/LittlerootTown/scripts.pory"
# 906 "data/maps/LittlerootTown/scripts.pory"
# 1574 "data/maps/LittlerootTown/scripts.pory"
	delay 30
# 1575 "data/maps/LittlerootTown/scripts.pory"
# 907 "data/maps/LittlerootTown/scripts.pory"
# 1576 "data/maps/LittlerootTown/scripts.pory"
	return
# 1577 "data/maps/LittlerootTown/scripts.pory"
# 908 "data/maps/LittlerootTown/scripts.pory"
# 1578 "data/maps/LittlerootTown/scripts.pory"

# 1579 "data/maps/LittlerootTown/scripts.pory"
# 909 "data/maps/LittlerootTown/scripts.pory"
# 1580 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_OurNewHomeLetsGoInside:
# 1581 "data/maps/LittlerootTown/scripts.pory"
# 910 "data/maps/LittlerootTown/scripts.pory"
# 1582 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: {PLAYER}, we're here, honey!\p"
# 1583 "data/maps/LittlerootTown/scripts.pory"
# 911 "data/maps/LittlerootTown/scripts.pory"
# 1584 "data/maps/LittlerootTown/scripts.pory"
	.string "It must be tiring riding with our things\n"
# 1585 "data/maps/LittlerootTown/scripts.pory"
# 912 "data/maps/LittlerootTown/scripts.pory"
# 1586 "data/maps/LittlerootTown/scripts.pory"
	.string "in the moving truck.\p"
# 1587 "data/maps/LittlerootTown/scripts.pory"
# 913 "data/maps/LittlerootTown/scripts.pory"
# 1588 "data/maps/LittlerootTown/scripts.pory"
	.string "Well, this is LITTLEROOT TOWN.\p"
# 1589 "data/maps/LittlerootTown/scripts.pory"
# 914 "data/maps/LittlerootTown/scripts.pory"
# 1590 "data/maps/LittlerootTown/scripts.pory"
	.string "How do you like it?\n"
# 1591 "data/maps/LittlerootTown/scripts.pory"
# 915 "data/maps/LittlerootTown/scripts.pory"
# 1592 "data/maps/LittlerootTown/scripts.pory"
	.string "This is our new home!\p"
# 1593 "data/maps/LittlerootTown/scripts.pory"
# 916 "data/maps/LittlerootTown/scripts.pory"
# 1594 "data/maps/LittlerootTown/scripts.pory"
	.string "It has a quaint feel, but it seems to be\n"
# 1595 "data/maps/LittlerootTown/scripts.pory"
# 917 "data/maps/LittlerootTown/scripts.pory"
# 1596 "data/maps/LittlerootTown/scripts.pory"
	.string "an easy place to live, don't you think?\p"
# 1597 "data/maps/LittlerootTown/scripts.pory"
# 918 "data/maps/LittlerootTown/scripts.pory"
# 1598 "data/maps/LittlerootTown/scripts.pory"
	.string "And, you get your own room, {PLAYER}!\n"
# 1599 "data/maps/LittlerootTown/scripts.pory"
# 919 "data/maps/LittlerootTown/scripts.pory"
# 1600 "data/maps/LittlerootTown/scripts.pory"
	.string "Let's go inside.$"
# 1601 "data/maps/LittlerootTown/scripts.pory"
# 920 "data/maps/LittlerootTown/scripts.pory"
# 1602 "data/maps/LittlerootTown/scripts.pory"

# 1603 "data/maps/LittlerootTown/scripts.pory"
# 921 "data/maps/LittlerootTown/scripts.pory"
# 1604 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_WaitPlayer:
# 1605 "data/maps/LittlerootTown/scripts.pory"
# 922 "data/maps/LittlerootTown/scripts.pory"
# 1606 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: Wait, {PLAYER}!$"
# 1607 "data/maps/LittlerootTown/scripts.pory"
# 923 "data/maps/LittlerootTown/scripts.pory"
# 1608 "data/maps/LittlerootTown/scripts.pory"

# 1609 "data/maps/LittlerootTown/scripts.pory"
# 924 "data/maps/LittlerootTown/scripts.pory"
# 1610 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_WearTheseRunningShoes:
# 1611 "data/maps/LittlerootTown/scripts.pory"
# 925 "data/maps/LittlerootTown/scripts.pory"
# 1612 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: {PLAYER}! {PLAYER}! Did you\n"
# 1613 "data/maps/LittlerootTown/scripts.pory"
# 926 "data/maps/LittlerootTown/scripts.pory"
# 1614 "data/maps/LittlerootTown/scripts.pory"
	.string "introduce yourself to PROF. BIRCH?\p"
# 1615 "data/maps/LittlerootTown/scripts.pory"
# 927 "data/maps/LittlerootTown/scripts.pory"
# 1616 "data/maps/LittlerootTown/scripts.pory"
	.string "Oh! What an adorable POKéMON!\n"
# 1617 "data/maps/LittlerootTown/scripts.pory"
# 928 "data/maps/LittlerootTown/scripts.pory"
# 1618 "data/maps/LittlerootTown/scripts.pory"
	.string "You got it from PROF. BIRCH. How nice!\p"
# 1619 "data/maps/LittlerootTown/scripts.pory"
# 929 "data/maps/LittlerootTown/scripts.pory"
# 1620 "data/maps/LittlerootTown/scripts.pory"
	.string "You're your father's child, all right.\n"
# 1621 "data/maps/LittlerootTown/scripts.pory"
# 930 "data/maps/LittlerootTown/scripts.pory"
# 1622 "data/maps/LittlerootTown/scripts.pory"
	.string "You look good together with POKéMON!\p"
# 1623 "data/maps/LittlerootTown/scripts.pory"
# 931 "data/maps/LittlerootTown/scripts.pory"
# 1624 "data/maps/LittlerootTown/scripts.pory"
	.string "Here, honey! If you're going out on an\n"
# 1625 "data/maps/LittlerootTown/scripts.pory"
# 932 "data/maps/LittlerootTown/scripts.pory"
# 1626 "data/maps/LittlerootTown/scripts.pory"
	.string "adventure, wear these RUNNING SHOES.\p"
# 1627 "data/maps/LittlerootTown/scripts.pory"
# 933 "data/maps/LittlerootTown/scripts.pory"
# 1628 "data/maps/LittlerootTown/scripts.pory"
	.string "They'll put a zip in your step!$"
# 1629 "data/maps/LittlerootTown/scripts.pory"
# 934 "data/maps/LittlerootTown/scripts.pory"
# 1630 "data/maps/LittlerootTown/scripts.pory"

# 1631 "data/maps/LittlerootTown/scripts.pory"
# 935 "data/maps/LittlerootTown/scripts.pory"
# 1632 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_SwitchShoesWithRunningShoes:
# 1633 "data/maps/LittlerootTown/scripts.pory"
# 936 "data/maps/LittlerootTown/scripts.pory"
# 1634 "data/maps/LittlerootTown/scripts.pory"
	.string "{PLAYER} switched shoes with the\n"
# 1635 "data/maps/LittlerootTown/scripts.pory"
# 937 "data/maps/LittlerootTown/scripts.pory"
# 1636 "data/maps/LittlerootTown/scripts.pory"
	.string "RUNNING SHOES.$"
# 1637 "data/maps/LittlerootTown/scripts.pory"
# 938 "data/maps/LittlerootTown/scripts.pory"
# 1638 "data/maps/LittlerootTown/scripts.pory"

# 1639 "data/maps/LittlerootTown/scripts.pory"
# 939 "data/maps/LittlerootTown/scripts.pory"
# 1640 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ExplainRunningShoes:
# 1641 "data/maps/LittlerootTown/scripts.pory"
# 940 "data/maps/LittlerootTown/scripts.pory"
# 1642 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: {PLAYER}, those shoes came with\n"
# 1643 "data/maps/LittlerootTown/scripts.pory"
# 941 "data/maps/LittlerootTown/scripts.pory"
# 1644 "data/maps/LittlerootTown/scripts.pory"
	.string "instructions.\p"
# 1645 "data/maps/LittlerootTown/scripts.pory"
# 942 "data/maps/LittlerootTown/scripts.pory"
# 1646 "data/maps/LittlerootTown/scripts.pory"
	.string "“Press the B Button while wearing these\n"
# 1647 "data/maps/LittlerootTown/scripts.pory"
# 943 "data/maps/LittlerootTown/scripts.pory"
# 1648 "data/maps/LittlerootTown/scripts.pory"
	.string "RUNNING SHOES to run extra-fast!\p"
# 1649 "data/maps/LittlerootTown/scripts.pory"
# 944 "data/maps/LittlerootTown/scripts.pory"
# 1650 "data/maps/LittlerootTown/scripts.pory"
	.string "“Slip on these RUNNING SHOES and race\n"
# 1651 "data/maps/LittlerootTown/scripts.pory"
# 945 "data/maps/LittlerootTown/scripts.pory"
# 1652 "data/maps/LittlerootTown/scripts.pory"
	.string "in the great outdoors!”$"
# 1653 "data/maps/LittlerootTown/scripts.pory"
# 946 "data/maps/LittlerootTown/scripts.pory"
# 1654 "data/maps/LittlerootTown/scripts.pory"

# 1655 "data/maps/LittlerootTown/scripts.pory"
# 947 "data/maps/LittlerootTown/scripts.pory"
# 1656 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ComeHomeIfAnythingHappens:
# 1657 "data/maps/LittlerootTown/scripts.pory"
# 948 "data/maps/LittlerootTown/scripts.pory"
# 1658 "data/maps/LittlerootTown/scripts.pory"
	.string "… … … … … … … …\n"
# 1659 "data/maps/LittlerootTown/scripts.pory"
# 949 "data/maps/LittlerootTown/scripts.pory"
# 1660 "data/maps/LittlerootTown/scripts.pory"
	.string "… … … … … … … …\p"
# 1661 "data/maps/LittlerootTown/scripts.pory"
# 950 "data/maps/LittlerootTown/scripts.pory"
# 1662 "data/maps/LittlerootTown/scripts.pory"
	.string "To think that you have your very own\n"
# 1663 "data/maps/LittlerootTown/scripts.pory"
# 951 "data/maps/LittlerootTown/scripts.pory"
# 1664 "data/maps/LittlerootTown/scripts.pory"
	.string "POKéMON now…\l"
# 1665 "data/maps/LittlerootTown/scripts.pory"
# 952 "data/maps/LittlerootTown/scripts.pory"
# 1666 "data/maps/LittlerootTown/scripts.pory"
	.string "Your father will be overjoyed.\p"
# 1667 "data/maps/LittlerootTown/scripts.pory"
# 953 "data/maps/LittlerootTown/scripts.pory"
# 1668 "data/maps/LittlerootTown/scripts.pory"
	.string "…But please be careful.\n"
# 1669 "data/maps/LittlerootTown/scripts.pory"
# 954 "data/maps/LittlerootTown/scripts.pory"
# 1670 "data/maps/LittlerootTown/scripts.pory"
	.string "If anything happens, you can come home.\p"
# 1671 "data/maps/LittlerootTown/scripts.pory"
# 955 "data/maps/LittlerootTown/scripts.pory"
# 1672 "data/maps/LittlerootTown/scripts.pory"
	.string "Go on, go get them, honey!$"
# 1673 "data/maps/LittlerootTown/scripts.pory"
# 956 "data/maps/LittlerootTown/scripts.pory"
# 1674 "data/maps/LittlerootTown/scripts.pory"

# 1675 "data/maps/LittlerootTown/scripts.pory"
# 957 "data/maps/LittlerootTown/scripts.pory"
# 1676 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_CanUsePCToStoreItems:
# 1677 "data/maps/LittlerootTown/scripts.pory"
# 958 "data/maps/LittlerootTown/scripts.pory"
# 1678 "data/maps/LittlerootTown/scripts.pory"
	.string "If you use a PC, you can store items\n"
# 1679 "data/maps/LittlerootTown/scripts.pory"
# 959 "data/maps/LittlerootTown/scripts.pory"
# 1680 "data/maps/LittlerootTown/scripts.pory"
	.string "and POKéMON.\p"
# 1681 "data/maps/LittlerootTown/scripts.pory"
# 960 "data/maps/LittlerootTown/scripts.pory"
# 1682 "data/maps/LittlerootTown/scripts.pory"
	.string "The power of science is staggering!$"
# 1683 "data/maps/LittlerootTown/scripts.pory"
# 961 "data/maps/LittlerootTown/scripts.pory"
# 1684 "data/maps/LittlerootTown/scripts.pory"

# 1685 "data/maps/LittlerootTown/scripts.pory"
# 962 "data/maps/LittlerootTown/scripts.pory"
# 1686 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_BirchSpendsDaysInLab:
# 1687 "data/maps/LittlerootTown/scripts.pory"
# 963 "data/maps/LittlerootTown/scripts.pory"
# 1688 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH spends days in his LAB\n"
# 1689 "data/maps/LittlerootTown/scripts.pory"
# 964 "data/maps/LittlerootTown/scripts.pory"
# 1690 "data/maps/LittlerootTown/scripts.pory"
	.string "studying, then he'll suddenly go out in\l"
# 1691 "data/maps/LittlerootTown/scripts.pory"
# 965 "data/maps/LittlerootTown/scripts.pory"
# 1692 "data/maps/LittlerootTown/scripts.pory"
	.string "the wild to do more research…\p"
# 1693 "data/maps/LittlerootTown/scripts.pory"
# 966 "data/maps/LittlerootTown/scripts.pory"
# 1694 "data/maps/LittlerootTown/scripts.pory"
	.string "When does PROF. BIRCH spend time\n"
# 1695 "data/maps/LittlerootTown/scripts.pory"
# 967 "data/maps/LittlerootTown/scripts.pory"
# 1696 "data/maps/LittlerootTown/scripts.pory"
	.string "at home?$"
# 1697 "data/maps/LittlerootTown/scripts.pory"
# 968 "data/maps/LittlerootTown/scripts.pory"
# 1698 "data/maps/LittlerootTown/scripts.pory"

# 1699 "data/maps/LittlerootTown/scripts.pory"
# 969 "data/maps/LittlerootTown/scripts.pory"
# 1700 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut:
# 1701 "data/maps/LittlerootTown/scripts.pory"
# 970 "data/maps/LittlerootTown/scripts.pory"
# 1702 "data/maps/LittlerootTown/scripts.pory"
	.string "Um, um, um!\p"
# 1703 "data/maps/LittlerootTown/scripts.pory"
# 971 "data/maps/LittlerootTown/scripts.pory"
# 1704 "data/maps/LittlerootTown/scripts.pory"
	.string "If you go outside and go in the grass,\n"
# 1705 "data/maps/LittlerootTown/scripts.pory"
# 972 "data/maps/LittlerootTown/scripts.pory"
# 1706 "data/maps/LittlerootTown/scripts.pory"
	.string "wild POKéMON will jump out!$"
# 1707 "data/maps/LittlerootTown/scripts.pory"
# 973 "data/maps/LittlerootTown/scripts.pory"
# 1708 "data/maps/LittlerootTown/scripts.pory"

# 1709 "data/maps/LittlerootTown/scripts.pory"
# 974 "data/maps/LittlerootTown/scripts.pory"
# 1710 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_DangerousIfYouDontHavePokemon:
# 1711 "data/maps/LittlerootTown/scripts.pory"
# 975 "data/maps/LittlerootTown/scripts.pory"
# 1712 "data/maps/LittlerootTown/scripts.pory"
	.string "It's dangerous if you don't have\n"
# 1713 "data/maps/LittlerootTown/scripts.pory"
# 976 "data/maps/LittlerootTown/scripts.pory"
# 1714 "data/maps/LittlerootTown/scripts.pory"
	.string "your own POKéMON.$"
# 1715 "data/maps/LittlerootTown/scripts.pory"
# 977 "data/maps/LittlerootTown/scripts.pory"
# 1716 "data/maps/LittlerootTown/scripts.pory"

# 1717 "data/maps/LittlerootTown/scripts.pory"
# 978 "data/maps/LittlerootTown/scripts.pory"
# 1718 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_CanYouGoSeeWhatsHappening:
# 1719 "data/maps/LittlerootTown/scripts.pory"
# 979 "data/maps/LittlerootTown/scripts.pory"
# 1720 "data/maps/LittlerootTown/scripts.pory"
	.string "Um, hi!\p"
# 1721 "data/maps/LittlerootTown/scripts.pory"
# 980 "data/maps/LittlerootTown/scripts.pory"
# 1722 "data/maps/LittlerootTown/scripts.pory"
	.string "There are scary POKéMON outside!\n"
# 1723 "data/maps/LittlerootTown/scripts.pory"
# 981 "data/maps/LittlerootTown/scripts.pory"
# 1724 "data/maps/LittlerootTown/scripts.pory"
	.string "I can hear their cries!\p"
# 1725 "data/maps/LittlerootTown/scripts.pory"
# 982 "data/maps/LittlerootTown/scripts.pory"
# 1726 "data/maps/LittlerootTown/scripts.pory"
	.string "I want to go see what's going on,\n"
# 1727 "data/maps/LittlerootTown/scripts.pory"
# 983 "data/maps/LittlerootTown/scripts.pory"
# 1728 "data/maps/LittlerootTown/scripts.pory"
	.string "but I don't have any POKéMON…\p"
# 1729 "data/maps/LittlerootTown/scripts.pory"
# 984 "data/maps/LittlerootTown/scripts.pory"
# 1730 "data/maps/LittlerootTown/scripts.pory"
	.string "Can you go see what's happening\n"
# 1731 "data/maps/LittlerootTown/scripts.pory"
# 985 "data/maps/LittlerootTown/scripts.pory"
# 1732 "data/maps/LittlerootTown/scripts.pory"
	.string "for me?$"
# 1733 "data/maps/LittlerootTown/scripts.pory"
# 986 "data/maps/LittlerootTown/scripts.pory"
# 1734 "data/maps/LittlerootTown/scripts.pory"

# 1735 "data/maps/LittlerootTown/scripts.pory"
# 987 "data/maps/LittlerootTown/scripts.pory"
# 1736 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_YouSavedBirch:
# 1737 "data/maps/LittlerootTown/scripts.pory"
# 988 "data/maps/LittlerootTown/scripts.pory"
# 1738 "data/maps/LittlerootTown/scripts.pory"
	.string "You saved PROF. BIRCH!\n"
# 1739 "data/maps/LittlerootTown/scripts.pory"
# 989 "data/maps/LittlerootTown/scripts.pory"
# 1740 "data/maps/LittlerootTown/scripts.pory"
	.string "I'm so glad!$"
# 1741 "data/maps/LittlerootTown/scripts.pory"
# 990 "data/maps/LittlerootTown/scripts.pory"
# 1742 "data/maps/LittlerootTown/scripts.pory"

# 1743 "data/maps/LittlerootTown/scripts.pory"
# 991 "data/maps/LittlerootTown/scripts.pory"
# 1744 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_GoodLuckCatchingPokemon:
# 1745 "data/maps/LittlerootTown/scripts.pory"
# 992 "data/maps/LittlerootTown/scripts.pory"
# 1746 "data/maps/LittlerootTown/scripts.pory"
	.string "Are you going to catch POKéMON?\n"
# 1747 "data/maps/LittlerootTown/scripts.pory"
# 993 "data/maps/LittlerootTown/scripts.pory"
# 1748 "data/maps/LittlerootTown/scripts.pory"
	.string "Good luck!$"
# 1749 "data/maps/LittlerootTown/scripts.pory"
# 994 "data/maps/LittlerootTown/scripts.pory"
# 1750 "data/maps/LittlerootTown/scripts.pory"

# 1751 "data/maps/LittlerootTown/scripts.pory"
# 995 "data/maps/LittlerootTown/scripts.pory"
# 1752 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_TownSign:
# 1753 "data/maps/LittlerootTown/scripts.pory"
# 996 "data/maps/LittlerootTown/scripts.pory"
# 1754 "data/maps/LittlerootTown/scripts.pory"
	.string "LITTLEROOT TOWN\n"
# 1755 "data/maps/LittlerootTown/scripts.pory"
# 997 "data/maps/LittlerootTown/scripts.pory"
# 1756 "data/maps/LittlerootTown/scripts.pory"
	.string "“A town that can't be shaded any hue.”$"
# 1757 "data/maps/LittlerootTown/scripts.pory"
# 998 "data/maps/LittlerootTown/scripts.pory"
# 1758 "data/maps/LittlerootTown/scripts.pory"

# 1759 "data/maps/LittlerootTown/scripts.pory"
# 999 "data/maps/LittlerootTown/scripts.pory"
# 1760 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ProfBirchsLab:
# 1761 "data/maps/LittlerootTown/scripts.pory"
# 1000 "data/maps/LittlerootTown/scripts.pory"
# 1762 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH'S POKéMON LAB$"
# 1763 "data/maps/LittlerootTown/scripts.pory"
# 1001 "data/maps/LittlerootTown/scripts.pory"
# 1764 "data/maps/LittlerootTown/scripts.pory"

# 1765 "data/maps/LittlerootTown/scripts.pory"
# 1002 "data/maps/LittlerootTown/scripts.pory"
# 1766 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_PlayersHouse:
# 1767 "data/maps/LittlerootTown/scripts.pory"
# 1003 "data/maps/LittlerootTown/scripts.pory"
# 1768 "data/maps/LittlerootTown/scripts.pory"
	.string "{PLAYER}'s house.$"
# 1769 "data/maps/LittlerootTown/scripts.pory"
# 1004 "data/maps/LittlerootTown/scripts.pory"
# 1770 "data/maps/LittlerootTown/scripts.pory"

# 1771 "data/maps/LittlerootTown/scripts.pory"
# 1005 "data/maps/LittlerootTown/scripts.pory"
# 1772 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ProfBirchsHouse:
# 1773 "data/maps/LittlerootTown/scripts.pory"
# 1006 "data/maps/LittlerootTown/scripts.pory"
# 1774 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH'S HOUSE$"
# 1775 "data/maps/LittlerootTown/scripts.pory"
# 1007 "data/maps/LittlerootTown/scripts.pory"
# 1776 "data/maps/LittlerootTown/scripts.pory"

# 1777 "data/maps/LittlerootTown/scripts.pory"
# 1008 "data/maps/LittlerootTown/scripts.pory"
# 1778 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_BirchSomethingToShowYouAtLab:
# 1779 "data/maps/LittlerootTown/scripts.pory"
# 1009 "data/maps/LittlerootTown/scripts.pory"
# 1780 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH: Well, well, {PLAYER}{KUN}!\n"
# 1781 "data/maps/LittlerootTown/scripts.pory"
# 1010 "data/maps/LittlerootTown/scripts.pory"
# 1782 "data/maps/LittlerootTown/scripts.pory"
	.string "That was good work out there!\p"
# 1783 "data/maps/LittlerootTown/scripts.pory"
# 1011 "data/maps/LittlerootTown/scripts.pory"
# 1784 "data/maps/LittlerootTown/scripts.pory"
	.string "I knew there was something special\n"
# 1785 "data/maps/LittlerootTown/scripts.pory"
# 1012 "data/maps/LittlerootTown/scripts.pory"
# 1786 "data/maps/LittlerootTown/scripts.pory"
	.string "about you when I first saw you,\l"
# 1787 "data/maps/LittlerootTown/scripts.pory"
# 1013 "data/maps/LittlerootTown/scripts.pory"
# 1788 "data/maps/LittlerootTown/scripts.pory"
	.string "but I never expected this.\p"
# 1789 "data/maps/LittlerootTown/scripts.pory"
# 1014 "data/maps/LittlerootTown/scripts.pory"
# 1790 "data/maps/LittlerootTown/scripts.pory"
	.string "Oh, yes. Do you still have the POKéDEX\n"
# 1791 "data/maps/LittlerootTown/scripts.pory"
# 1015 "data/maps/LittlerootTown/scripts.pory"
# 1792 "data/maps/LittlerootTown/scripts.pory"
	.string "I gave you?\p"
# 1793 "data/maps/LittlerootTown/scripts.pory"
# 1016 "data/maps/LittlerootTown/scripts.pory"
# 1794 "data/maps/LittlerootTown/scripts.pory"
	.string "I have something to show you.\n"
# 1795 "data/maps/LittlerootTown/scripts.pory"
# 1017 "data/maps/LittlerootTown/scripts.pory"
# 1796 "data/maps/LittlerootTown/scripts.pory"
	.string "Let's go to my LAB.$"

LittlerootTown_MapScripts::
# 1823 "data/maps/LittlerootTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, NoRain
	.byte 0


NoRain::
# 1828 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 4
	goto_if_gt NoRain_1
	return

NoRain_1:
# 1829 "data/maps/LittlerootTown/scripts.pory"
	setweather WEATHER_SHADE
	return


FatGuyExclMark::
# 1836 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset Donutquestaccepted, FatGuyExclMark_4
FatGuyExclMark_3:
# 1842 "data/maps/LittlerootTown/scripts.pory"
	release
FatGuyExclMark_1:
# 1843 "data/maps/LittlerootTown/scripts.pory"
endfatguyexlmarkscript:
# 1844 "data/maps/LittlerootTown/scripts.pory"
	release
	return

FatGuyExclMark_2:
# 1838 "data/maps/LittlerootTown/scripts.pory"
	applymovement 3, FatGuyExclMark_Movement_0
# 1839 "data/maps/LittlerootTown/scripts.pory"
	setflag fatguyseesplayerleavelittl
# 1840 "data/maps/LittlerootTown/scripts.pory"
	goto endfatguyexlmarkscript
	goto FatGuyExclMark_1

FatGuyExclMark_4:
# 1836 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset fatguyseesplayerleavelittl, FatGuyExclMark_2
	goto FatGuyExclMark_3


Littleroot_Techguy_Talk::
# 1848 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1849 "data/maps/LittlerootTown/scripts.pory"
	applymovement 3, Littleroot_Techguy_Talk_Movement_0
# 1850 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 3
	goto_if_eq Littleroot_Techguy_Talk_2
Littleroot_Techguy_Talk_1:
# 1858 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 5
	goto_if_eq Littleroot_Techguy_Talk_6
Littleroot_Techguy_Talk_4:
# 1865 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 5
	goto_if_eq Littleroot_Techguy_Talk_11
Littleroot_Techguy_Talk_9:
# 1905 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set donutquestcomplete, Littleroot_Techguy_Talk_15
# 1909 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Techguy_Talk_Text_11
Littleroot_Techguy_Talk_14:
# 1912 "data/maps/LittlerootTown/scripts.pory"
endlitlfatguy:
# 1913 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return

Littleroot_Techguy_Talk_2:
# 1851 "data/maps/LittlerootTown/scripts.pory"
	bufferleadmonspeciesname STR_VAR_1
# 1853 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Techguy_Talk_Text_0
# 1855 "data/maps/LittlerootTown/scripts.pory"
	goto endlitlfatguy
	goto Littleroot_Techguy_Talk_1

Littleroot_Techguy_Talk_5:
# 1859 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Techguy_Talk_Text_1
# 1863 "data/maps/LittlerootTown/scripts.pory"
	setflag Donutquestaccepted
# 1864 "data/maps/LittlerootTown/scripts.pory"
	goto endlitlfatguy
	goto Littleroot_Techguy_Talk_4

Littleroot_Techguy_Talk_6:
# 1858 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset Donutquestaccepted, Littleroot_Techguy_Talk_5
	goto Littleroot_Techguy_Talk_4

Littleroot_Techguy_Talk_10:
# 1866 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset donutquestcomplete, Littleroot_Techguy_Talk_18
	goto Littleroot_Techguy_Talk_9

Littleroot_Techguy_Talk_11:
# 1865 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set Donutquestaccepted, Littleroot_Techguy_Talk_10
	goto Littleroot_Techguy_Talk_9

Littleroot_Techguy_Talk_15:
# 1906 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Techguy_Talk_Text_10
	goto Littleroot_Techguy_Talk_14

Littleroot_Techguy_Talk_18:
	checkitem ITEM_SHALOUR_SABLE
# 0 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq Littleroot_Techguy_Talk_20
# 1877 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Techguy_Talk_Text_3
# 1879 "data/maps/LittlerootTown/scripts.pory"
	dynmultichoice 0, 0, TRUE, 3, 0, DYN_MULTICHOICE_CB_NONE, Littleroot_Techguy_Talk_Text_4, Littleroot_Techguy_Talk_Text_5
# 1881 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, 0
	goto_if_eq Littleroot_Techguy_Talk_24
Littleroot_Techguy_Talk_23:
# 1898 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, 1
	goto_if_eq Littleroot_Techguy_Talk_26
	goto Littleroot_Techguy_Talk_9

Littleroot_Techguy_Talk_20:
# 1871 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Techguy_Talk_Text_2
# 1875 "data/maps/LittlerootTown/scripts.pory"
	goto endlitlfatguy
	goto Littleroot_Techguy_Talk_9

Littleroot_Techguy_Talk_24:
# 1882 "data/maps/LittlerootTown/scripts.pory"
	removeitem ITEM_SHALOUR_SABLE, 1
# 1883 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Techguy_Talk_Text_6
# 1884 "data/maps/LittlerootTown/scripts.pory"
	playse SE_M_BITE
# 1885 "data/maps/LittlerootTown/scripts.pory"
	waitse
# 1886 "data/maps/LittlerootTown/scripts.pory"
	playse SE_M_BITE
# 1887 "data/maps/LittlerootTown/scripts.pory"
	waitse
# 1888 "data/maps/LittlerootTown/scripts.pory"
	playse SE_M_SCRATCH
# 1889 "data/maps/LittlerootTown/scripts.pory"
	waitse
# 1890 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Techguy_Talk_Text_7
# 1892 "data/maps/LittlerootTown/scripts.pory"
	giveitem ITEM_PARK_BALL, 5
# 1893 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Techguy_Talk_Text_8
# 1894 "data/maps/LittlerootTown/scripts.pory"
	setflag donutquestcomplete
# 1895 "data/maps/LittlerootTown/scripts.pory"
	goto endlitlfatguy
	goto Littleroot_Techguy_Talk_23

Littleroot_Techguy_Talk_26:
# 1899 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Techguy_Talk_Text_9
# 1900 "data/maps/LittlerootTown/scripts.pory"
	goto endlitlfatguy
	goto Littleroot_Techguy_Talk_9


SamanthaDontgotoRivals::
# 1918 "data/maps/LittlerootTown/scripts.pory"
	lock
# 1919 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_NPC_FOLLOWER, FatGuyExclMark_Movement_0
# 1920 "data/maps/LittlerootTown/scripts.pory"
	playse SE_PIN
# 1921 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_SAMANTHA ]
# 1922 "data/maps/LittlerootTown/scripts.pory"
	msgbox SamanthaDontgotoRivals_Text_0
# 1924 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 1925 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, MALE
	goto_if_eq SamanthaDontgotoRivals_2
SamanthaDontgotoRivals_1:
# 1930 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, FEMALE
	goto_if_eq SamanthaDontgotoRivals_5
SamanthaDontgotoRivals_4:
# 1934 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SamanthaDontgotoRivals_Movement_0
# 1935 "data/maps/LittlerootTown/scripts.pory"
	waitmovement OBJ_EVENT_ID_PLAYER
# 1937 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return

SamanthaDontgotoRivals_2:
# 1926 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_SAMANTHA ]
# 1927 "data/maps/LittlerootTown/scripts.pory"
	msgbox SamanthaDontgotoRivals_Text_1
	goto SamanthaDontgotoRivals_1

SamanthaDontgotoRivals_5:
# 1931 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_SAMANTHA ]
# 1932 "data/maps/LittlerootTown/scripts.pory"
	msgbox SamanthaDontgotoRivals_Text_2
	goto SamanthaDontgotoRivals_4


SamanthaDontgotoPlayers::
# 1941 "data/maps/LittlerootTown/scripts.pory"
	lock
# 1942 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_NPC_FOLLOWER, FatGuyExclMark_Movement_0
# 1943 "data/maps/LittlerootTown/scripts.pory"
	playse SE_PIN
# 1944 "data/maps/LittlerootTown/scripts.pory"
	msgbox SamanthaDontgotoPlayers_Text_0
# 1946 "data/maps/LittlerootTown/scripts.pory"
	msgbox SamanthaDontgotoPlayers_Text_1
# 1949 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SamanthaDontgotoRivals_Movement_0
# 1950 "data/maps/LittlerootTown/scripts.pory"
	waitmovement OBJ_EVENT_ID_PLAYER
# 1952 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_Player_Mailbox::
# 1957 "data/maps/LittlerootTown/scripts.pory"
	lock
# 1958 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset FLAG_ITEM_LITTLEROOT_MAILBOX, Littleroot_Player_Mailbox_2
Littleroot_Player_Mailbox_1:
# 1968 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set sentdemomysterygift, Littleroot_Player_Mailbox_7
Littleroot_Player_Mailbox_6:
# 1977 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Player_Mailbox_Text_3
Littleroot_Player_Mailbox_4:
# 1978 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return

Littleroot_Player_Mailbox_2:
# 1959 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Player_Mailbox_Text_0
# 1962 "data/maps/LittlerootTown/scripts.pory"
	playse MUS_OBTAIN_ITEM
# 1963 "data/maps/LittlerootTown/scripts.pory"
	giveitem ITEM_BOTTLE_CAP
# 1964 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_ITEM_LITTLEROOT_MAILBOX
	goto Littleroot_Player_Mailbox_1

Littleroot_Player_Mailbox_5:
# 1969 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Player_Mailbox_Text_1
# 1971 "data/maps/LittlerootTown/scripts.pory"
	playfanfare MUS_OBTAIN_SYMBOL
# 1972 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Player_Mailbox_Text_2
# 1973 "data/maps/LittlerootTown/scripts.pory"
	givemon SPECIES_SNOVER, 10, ITEM_MIRACLE_SEED, ITEM_CHERISH_BALL, NATURE_QUIRKY, 1, MALE, 0, 0, 0, 0, 0, 0, 31, 31, 31, 31, 31, 31, MOVE_ICE_SHARD, MOVE_SPLASH, MOVE_MOONLIGHT, MOVE_SPARK
# 1974 "data/maps/LittlerootTown/scripts.pory"
	setflag receiveddemomysterygift
	goto Littleroot_Player_Mailbox_4

Littleroot_Player_Mailbox_7:
# 1968 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset receiveddemomysterygift, Littleroot_Player_Mailbox_5
	goto Littleroot_Player_Mailbox_6


Littleroot_Rival_Mailbox::
# 1982 "data/maps/LittlerootTown/scripts.pory"
	lock
# 1983 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Player_Mailbox_Text_3
# 1984 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_PlayerHouseSign::
# 1988 "data/maps/LittlerootTown/scripts.pory"
	lock
# 1989 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_PlayerHouseSign_Text_0
# 1990 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_RivalHouseSign::
# 1995 "data/maps/LittlerootTown/scripts.pory"
	lock
# 1996 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_RivalHouseSign_Text_0
# 1997 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_LabSign::
# 2001 "data/maps/LittlerootTown/scripts.pory"
	lock
# 2002 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_LabSign_Text_0
# 2003 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_CemeterySign::
# 2007 "data/maps/LittlerootTown/scripts.pory"
	lock
# 2008 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_CemeterySign_Text_0
# 2009 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_TownSign::
# 2013 "data/maps/LittlerootTown/scripts.pory"
	lock
# 2014 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_TownSign_Text_0
# 2016 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


LittlerootTown_Trigger_Blocknopokes::
# 2020 "data/maps/LittlerootTown/scripts.pory"
	lock
# 2021 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_Blocknopokes_Text_0
# 2022 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SamanthaDontgotoRivals_Movement_0
# 2023 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 2024 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


LittlerootTown_Trigger_Blockgorival::
# 2028 "data/maps/LittlerootTown/scripts.pory"
	lock
# 2029 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_Blockgorival_Text_0
# 2030 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SamanthaDontgotoRivals_Movement_0
# 2031 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 2032 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


LittlerootTown_Trigger_Blocknopokesnocemetery::
# 2036 "data/maps/LittlerootTown/scripts.pory"
	lock
# 2037 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_Blocknopokesnocemetery_Text_0
# 2038 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, LittlerootTown_Trigger_Blocknopokesnocemetery_Movement_0
# 2039 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 2040 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


LittlerootTown_Trigger_Blockgorivalnocemetery::
# 2044 "data/maps/LittlerootTown/scripts.pory"
	lock
# 2045 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_Blockgorival_Text_0
# 2046 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, LittlerootTown_Trigger_Blocknopokesnocemetery_Movement_0
# 2047 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 2048 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


LittlerootTown_Trigger_NoEnterRival1::
# 2052 "data/maps/LittlerootTown/scripts.pory"
	lock
# 2053 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_NoEnterRival1_Text_0
# 2057 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_RIVAL ]
# 2058 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_NoEnterRival1_Text_1
# 2060 "data/maps/LittlerootTown/scripts.pory"
	waitbuttonpress
# 2061 "data/maps/LittlerootTown/scripts.pory"
	call RivalShake
# 2062 "data/maps/LittlerootTown/scripts.pory"
	playse SE_BANG
# 2066 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_RIVAL ]
# 2067 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_NoEnterRival1_Text_2
# 2069 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ NULL ]
# 2070 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_NoEnterRival1_Text_3
# 2071 "data/maps/LittlerootTown/scripts.pory"
	waitmessage
# 2072 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SamanthaDontgotoRivals_Movement_0
# 2073 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 2074 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


RivalShake::
# 2078 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8004, 2
# 2079 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8005, 6
# 2080 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8006, 4
# 2081 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8007, 4
# 2082 "data/maps/LittlerootTown/scripts.pory"
	special ShakeCamera
	return


Littleroot_Idletalk_Oldman::
# 2088 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_MAUSOLEUM_HEXGIRL, 3
	goto_if_eq Littleroot_Idletalk_Oldman_1
# 2130 "data/maps/LittlerootTown/scripts.pory"
	lock
# 2131 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, Littleroot_Techguy_Talk_Movement_0
# 2132 "data/maps/LittlerootTown/scripts.pory"
	createfieldmugshot MUGSHOT_BIRCH, EMOTE_NORMAL
# 2133 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2134 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 0
	goto_if_eq Littleroot_Idletalk_Oldman_9
Littleroot_Idletalk_Oldman_7:
# 2139 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 0
	goto_if_eq Littleroot_Idletalk_Oldman_19
Littleroot_Idletalk_Oldman_17:
# 2141 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 3
	goto_if_eq Littleroot_Idletalk_Oldman_27
Littleroot_Idletalk_Oldman_25:
# 2145 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 5
	goto_if_eq Littleroot_Idletalk_Oldman_32
Littleroot_Idletalk_Oldman_30:
# 2154 "data/maps/LittlerootTown/scripts.pory"
endfirstgreeting:
# 2156 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 5
	goto_if_eq Littleroot_Idletalk_Oldman_37
Littleroot_Idletalk_Oldman_35:
# 2161 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 7
	goto_if_eq Littleroot_Idletalk_Oldman_44
Littleroot_Idletalk_Oldman_43:
# 2166 "data/maps/LittlerootTown/scripts.pory"
endofbirchscript:
# 2167 "data/maps/LittlerootTown/scripts.pory"
	removefieldmugshot
# 2168 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return

Littleroot_Idletalk_Oldman_1:
# 2089 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset SamanthaBirchInteraction, Littleroot_Idletalk_Oldman_5
Littleroot_Idletalk_Oldman_4:
# 2118 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set SamanthaBirchInteraction, Littleroot_Idletalk_Oldman_12
	return

Littleroot_Idletalk_Oldman_5:
# 2090 "data/maps/LittlerootTown/scripts.pory"
	createfieldmugshot MUGSHOT_BIRCH, EMOTE_NORMAL
# 2091 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2092 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_0
# 2093 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_FOLLOWER, Littleroot_Techguy_Talk_Movement_0
# 2094 "data/maps/LittlerootTown/scripts.pory"
	removefieldmugshot
# 2095 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_SAMANTHA ]
# 2096 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_1
# 2097 "data/maps/LittlerootTown/scripts.pory"
	setflag SamanthaBirchInteraction
# 2098 "data/maps/LittlerootTown/scripts.pory"
	createfieldmugshot MUGSHOT_BIRCH, EMOTE_NORMAL
# 2099 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2100 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 2101 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, MALE
	goto_if_eq Littleroot_Idletalk_Oldman_15
Littleroot_Idletalk_Oldman_14:
# 2108 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, FEMALE
	goto_if_eq Littleroot_Idletalk_Oldman_23
Littleroot_Idletalk_Oldman_22:
# 2114 "data/maps/LittlerootTown/scripts.pory"
	goto endofbirchscript
	goto Littleroot_Idletalk_Oldman_4

Littleroot_Idletalk_Oldman_8:
# 2135 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_8
# 2137 "data/maps/LittlerootTown/scripts.pory"
	setflag Birchafter1stgreeting
# 2138 "data/maps/LittlerootTown/scripts.pory"
	goto endfirstgreeting
	goto Littleroot_Idletalk_Oldman_7

Littleroot_Idletalk_Oldman_9:
# 2134 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset Birchafter1stgreeting, Littleroot_Idletalk_Oldman_8
	goto Littleroot_Idletalk_Oldman_7

Littleroot_Idletalk_Oldman_12:
# 2119 "data/maps/LittlerootTown/scripts.pory"
	createfieldmugshot MUGSHOT_BIRCH, EMOTE_NORMAL
# 2120 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2121 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_6
# 2122 "data/maps/LittlerootTown/scripts.pory"
	createfieldmugshot MUGSHOT_BIRCH, EMOTE_NORMAL
# 2123 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2124 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_7
# 2125 "data/maps/LittlerootTown/scripts.pory"
	goto endofbirchscript
	return

Littleroot_Idletalk_Oldman_15:
# 2102 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_2
# 2103 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_SAMANTHA ]
# 2104 "data/maps/LittlerootTown/scripts.pory"
	removefieldmugshot
# 2105 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_3
	goto Littleroot_Idletalk_Oldman_14

Littleroot_Idletalk_Oldman_18:
# 2140 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_9
	goto Littleroot_Idletalk_Oldman_17

Littleroot_Idletalk_Oldman_19:
# 2139 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set Birchafter1stgreeting, Littleroot_Idletalk_Oldman_18
	goto Littleroot_Idletalk_Oldman_17

Littleroot_Idletalk_Oldman_23:
# 2109 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_4
# 2110 "data/maps/LittlerootTown/scripts.pory"
	removefieldmugshot
# 2111 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_SAMANTHA ]
# 2112 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_5
	goto Littleroot_Idletalk_Oldman_22

Littleroot_Idletalk_Oldman_26:
# 2142 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_10
	goto Littleroot_Idletalk_Oldman_25

Littleroot_Idletalk_Oldman_27:
# 2141 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set checkonrival, Littleroot_Idletalk_Oldman_26
	goto Littleroot_Idletalk_Oldman_25

Littleroot_Idletalk_Oldman_31:
# 2147 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 2148 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, MALE
	goto_if_eq Littleroot_Idletalk_Oldman_40
# 2152 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_12
	goto Littleroot_Idletalk_Oldman_30

Littleroot_Idletalk_Oldman_32:
# 2145 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset FLAG_HIDDEN_ITEM_ROUTE_101_VOLTORB_SHARD, Littleroot_Idletalk_Oldman_31
	goto Littleroot_Idletalk_Oldman_30

Littleroot_Idletalk_Oldman_36:
# 2157 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_13
	goto Littleroot_Idletalk_Oldman_35

Littleroot_Idletalk_Oldman_37:
# 2156 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE_101_VOLTORB_SHARD, Littleroot_Idletalk_Oldman_36
	goto Littleroot_Idletalk_Oldman_35

Littleroot_Idletalk_Oldman_40:
# 2149 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_11
	goto Littleroot_Idletalk_Oldman_30

Littleroot_Idletalk_Oldman_44:
# 2162 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_14
	goto Littleroot_Idletalk_Oldman_43


LittlerootTown_Eventscript_Oldmanasking::
# 2173 "data/maps/LittlerootTown/scripts.pory"
	lock
# 2174 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_SAFE_FOLLOWER_MOVEMENT
# 2175 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset checkonrival, LittlerootTown_Eventscript_Oldmanasking_2
# 2213 "data/maps/LittlerootTown/scripts.pory"
	setflag checkonrival
LittlerootTown_Eventscript_Oldmanasking_1:
# 2214 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return

LittlerootTown_Eventscript_Oldmanasking_2:
# 2176 "data/maps/LittlerootTown/scripts.pory"
	playse SE_PIN
# 2177 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, LittlerootTown_Eventscript_Oldmanasking_Movement_0
# 2178 "data/maps/LittlerootTown/scripts.pory"
	createfieldmugshot MUGSHOT_BIRCH, EMOTE_NORMAL
# 2179 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2180 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Eventscript_Oldmanasking_Text_0
# 2181 "data/maps/LittlerootTown/scripts.pory"
	removefieldmugshot
# 2182 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, LittlerootTown_Eventscript_Oldmanasking_Movement_1
# 2183 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, LittlerootTown_Eventscript_Oldmanasking_Movement_2
# 2184 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 2185 "data/maps/LittlerootTown/scripts.pory"
	createfieldmugshot MUGSHOT_BIRCH, EMOTE_NORMAL
# 2186 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2187 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset GOTSTARTER3, LittlerootTown_Eventscript_Oldmanasking_6
# 2194 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Eventscript_Oldmanasking_Text_2
LittlerootTown_Eventscript_Oldmanasking_5:
# 2197 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2198 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 2199 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, MALE
	goto_if_eq LittlerootTown_Eventscript_Oldmanasking_10
# 2205 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Eventscript_Oldmanasking_Text_4
LittlerootTown_Eventscript_Oldmanasking_9:
# 2209 "data/maps/LittlerootTown/scripts.pory"
	removefieldmugshot
# 2210 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, LittlerootTown_Eventscript_Oldmanasking_Movement_3
# 2211 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 2212 "data/maps/LittlerootTown/scripts.pory"
	setflag checkonrival
	goto LittlerootTown_Eventscript_Oldmanasking_1

LittlerootTown_Eventscript_Oldmanasking_6:
# 2189 "data/maps/LittlerootTown/scripts.pory"
	bufferleadmonspeciesname STR_VAR_1
# 2190 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Eventscript_Oldmanasking_Text_1
	goto LittlerootTown_Eventscript_Oldmanasking_5

LittlerootTown_Eventscript_Oldmanasking_10:
# 2200 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Eventscript_Oldmanasking_Text_3
	goto LittlerootTown_Eventscript_Oldmanasking_9


OldManThanks::
# 2219 "data/maps/LittlerootTown/scripts.pory"
	lock
# 2220 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_SAFE_FOLLOWER_MOVEMENT
# 2221 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Eventscript_Oldmanasking_Text_0
# 2222 "data/maps/LittlerootTown/scripts.pory"
	removefieldmugshot
# 2223 "data/maps/LittlerootTown/scripts.pory"
	setobjectxy 1, 14, 16
# 2224 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, OldManThanks_Movement_0
# 2225 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 2226 "data/maps/LittlerootTown/scripts.pory"
	createfieldmugshot MUGSHOT_BIRCH, EMOTE_NORMAL
# 2227 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2228 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 2229 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, MALE
	goto_if_eq OldManThanks_2
OldManThanks_1:
# 2233 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, FEMALE
	goto_if_eq OldManThanks_5
OldManThanks_4:
# 2237 "data/maps/LittlerootTown/scripts.pory"
	removefieldmugshot
# 2238 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ NULL ]
# 2239 "data/maps/LittlerootTown/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 2240 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_SYS_B_DASH
# 2241 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 2242 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, MALE
	goto_if_eq OldManThanks_8
# 2250 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_4
# 2251 "data/maps/LittlerootTown/scripts.pory"
	waitmessage
# 2252 "data/maps/LittlerootTown/scripts.pory"
	createfieldmugshot MUGSHOT_BIRCH, EMOTE_NORMAL
# 2253 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2254 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_5
OldManThanks_7:
# 2256 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2257 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_6
# 2258 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2259 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, LittlerootTown_Eventscript_Oldmanasking_Movement_2
# 2260 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_7
# 2261 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2262 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, OldManThanks_Movement_1
# 2263 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_8
# 2265 "data/maps/LittlerootTown/scripts.pory"
	removefieldmugshot
# 2266 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 2267 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, OldManThanks_Movement_2
# 2268 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 1
# 2269 "data/maps/LittlerootTown/scripts.pory"
	removeobject 1
# 2270 "data/maps/LittlerootTown/scripts.pory"
	setobjectxy 1, 4, 17
# 2271 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_PHASE, 5
# 2272 "data/maps/LittlerootTown/scripts.pory"
	setweather WEATHER_SHADE
# 2273 "data/maps/LittlerootTown/scripts.pory"
	doweather
# 2276 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return

OldManThanks_2:
# 2230 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_0
	goto OldManThanks_1

OldManThanks_5:
# 2234 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_1
	goto OldManThanks_4

OldManThanks_8:
# 2243 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_2
# 2244 "data/maps/LittlerootTown/scripts.pory"
	waitmessage
# 2245 "data/maps/LittlerootTown/scripts.pory"
	createfieldmugshot MUGSHOT_BIRCH, EMOTE_NORMAL
# 2246 "data/maps/LittlerootTown/scripts.pory"
	setspeaker [ SP_NAME_BIRCH ]
# 2247 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_3
	goto OldManThanks_7


Respawnatplayerbed::
# 2279 "data/maps/LittlerootTown/scripts.pory"
	setrespawn HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F
	end


# 1838 "data/maps/LittlerootTown/scripts.pory"
FatGuyExclMark_Movement_0:
# 1838 "data/maps/LittlerootTown/scripts.pory"
	face_player
# 1838 "data/maps/LittlerootTown/scripts.pory"
	emote_exclamation_mark
	step_end

# 1849 "data/maps/LittlerootTown/scripts.pory"
Littleroot_Techguy_Talk_Movement_0:
# 1849 "data/maps/LittlerootTown/scripts.pory"
	face_player
	step_end

# 1934 "data/maps/LittlerootTown/scripts.pory"
SamanthaDontgotoRivals_Movement_0:
# 1934 "data/maps/LittlerootTown/scripts.pory"
	walk_down
	step_end

# 2038 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Trigger_Blocknopokesnocemetery_Movement_0:
# 2038 "data/maps/LittlerootTown/scripts.pory"
	walk_left
	step_end

# 2177 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Eventscript_Oldmanasking_Movement_0:
# 2177 "data/maps/LittlerootTown/scripts.pory"
	emote_exclamation_mark
	step_end

# 2182 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Eventscript_Oldmanasking_Movement_1:
# 2182 "data/maps/LittlerootTown/scripts.pory"
	face_down
# 2182 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2182 "data/maps/LittlerootTown/scripts.pory"
	face_left
	step_end

# 2183 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Eventscript_Oldmanasking_Movement_2:
# 2183 "data/maps/LittlerootTown/scripts.pory"
	face_right
	step_end

# 2210 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Eventscript_Oldmanasking_Movement_3:
# 2210 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 2210 "data/maps/LittlerootTown/scripts.pory"
	face_down
	step_end

# 2224 "data/maps/LittlerootTown/scripts.pory"
OldManThanks_Movement_0:
# 2224 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 2224 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 2224 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 2224 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 2224 "data/maps/LittlerootTown/scripts.pory"
	walk_up
	step_end

# 2262 "data/maps/LittlerootTown/scripts.pory"
OldManThanks_Movement_1:
# 2262 "data/maps/LittlerootTown/scripts.pory"
	face_up
	step_end

# 2267 "data/maps/LittlerootTown/scripts.pory"
OldManThanks_Movement_2:
# 2267 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2267 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2267 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2267 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2267 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2267 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2267 "data/maps/LittlerootTown/scripts.pory"
	walk_down
	step_end

Littleroot_Techguy_Talk_Text_0:
# 1853 "data/maps/LittlerootTown/scripts.pory"
	.string "Wait, did Balsam give you that\n"
	.string "{STR_VAR_1}!?\p"
	.string "Last time I asked her for one, she gave\n"
	.string "me a Digglett instead...$"

Littleroot_Techguy_Talk_Text_1:
# 1859 "data/maps/LittlerootTown/scripts.pory"
	.string "Oh, {PLAYER}! I've heard you're going\n"
	.string "to Oldale Town.\p"
	.string "If you have time, would you mind getting\n"
	.string "me a {COLOR RED}Crater Donut{COLOR DARK_GRAY}? They're to die for...\p"
	.string "If you take a left on Route 101, you'll\n"
	.string "arrive at the {COLOR GREEN}Great Crater{COLOR DARK_GRAY}. There's a\l"
	.string "guy that sells them there.\p"
	.string "Do me the favour, and I'll give you some\n"
	.string "{COLOR RED}Pokéballs{COLOR DARK_GRAY}. Fair deal, right?$"

Littleroot_Techguy_Talk_Text_2:
# 1871 "data/maps/LittlerootTown/scripts.pory"
	.string "SO, {PLAYER}... it's okay if you don't\n"
	.string "have time, but...\p"
	.string "I'd really like a taste of those {COLOR RED}Crater\n"
	.string "Donuts{COLOR DARK_GRAY}.\p"
	.string "I'd go myself, but my Digglet is weak,\n"
	.string "and I got robbed by a {COLOR RED}Rebel{COLOR DARK_GRAY} last time I\l"
	.string "left town.\p"
	.string "But you're a former soldier, right? They\n"
	.string "won't mess with you!$"

Littleroot_Techguy_Talk_Text_3:
# 1877 "data/maps/LittlerootTown/scripts.pory"
	.string "I-I can smell it from your bag - that's a\n"
	.string "{COLOR RED}Crater Donut{COLOR DARK_GRAY}!\p"
	.string "My mouth is already watering...$"

Littleroot_Techguy_Talk_Text_4:
# 1879 "data/maps/LittlerootTown/scripts.pory"
	.string "Give Crater Donut$"

Littleroot_Techguy_Talk_Text_5:
# 1879 "data/maps/LittlerootTown/scripts.pory"
	.string "Don't give Crater Donut$"

Littleroot_Techguy_Talk_Text_6:
# 1883 "data/maps/LittlerootTown/scripts.pory"
	.string "Thank you! Well, as they say in Kalos...\n"
	.string "bon appétit!$"

Littleroot_Techguy_Talk_Text_7:
# 1890 "data/maps/LittlerootTown/scripts.pory"
	.string "Hmm - delicious...\p"
	.string "O-oh, I'm sorry... a deal is a deal. Here\n"
	.string "are your Pokéballs!$"

Littleroot_Techguy_Talk_Text_8:
# 1893 "data/maps/LittlerootTown/scripts.pory"
	.string "I know they're a bit busted, but they\n"
	.string "still work. Go try them out!$"

Littleroot_Techguy_Talk_Text_9:
# 1899 "data/maps/LittlerootTown/scripts.pory"
	.string "O-oh, so that one is for you? I see...$"

Littleroot_Techguy_Talk_Text_10:
# 1906 "data/maps/LittlerootTown/scripts.pory"
	.string "I find lots of those old balls laying\n"
	.string "around, from the time of the war.\p"
	.string "Next time I get a craving for donuts, we\n"
	.string "could make the same deal!$"

Littleroot_Techguy_Talk_Text_11:
# 1909 "data/maps/LittlerootTown/scripts.pory"
	.string "To think that Pokémon can be altered\n"
	.string "and made 'safer' to be around humans...\p"
	.string "Technology is amazing, but it can be\n"
	.string "scary too.$"

SamanthaDontgotoRivals_Text_0:
# 1922 "data/maps/LittlerootTown/scripts.pory"
	.string "O-oh, {PLAYER}... this is...\n"
	.string "{RIVAL}'s house, right?$"

SamanthaDontgotoRivals_Text_1:
# 1927 "data/maps/LittlerootTown/scripts.pory"
	.string "She comes to the graveyard sometimes...\p"
	.string "I think we shouldn't intrude, she is a\n"
	.string "bit scary...$"

SamanthaDontgotoRivals_Text_2:
# 1932 "data/maps/LittlerootTown/scripts.pory"
	.string "He comes to the graveyard sometimes...\p"
	.string "I think we shouldn't intrude, he is a bit\n"
	.string "scary...$"

SamanthaDontgotoPlayers_Text_0:
# 1944 "data/maps/LittlerootTown/scripts.pory"
	.string "O-oh, {PLAYER}... this is... your house,\n"
	.string "right? Your name is on the sign...$"

SamanthaDontgotoPlayers_Text_1:
# 1946 "data/maps/LittlerootTown/scripts.pory"
	.string "I-I appreciate it, but... I can't take\n"
	.string "your food!\p"
	.string "I have saved money for mine. So let's go\n"
	.string "to Oldale to get it.$"

Littleroot_Player_Mailbox_Text_0:
# 1959 "data/maps/LittlerootTown/scripts.pory"
	.string "There's a package inside the mailbox. A\n"
	.string "letter is attached to it.\p"
	.string "For your invaluable service to the\n"
	.string "region, please accept this token of\l"
	.string "recognition, courtesy of Devon Co.$"

Littleroot_Player_Mailbox_Text_1:
# 1969 "data/maps/LittlerootTown/scripts.pory"
	.string "There's a pretty gift box on the\n"
	.string "mailbox, with a note attached... 'May it\l"
	.string "brighten your Christmas! - Dystopian'.$"

Littleroot_Player_Mailbox_Text_2:
# 1972 "data/maps/LittlerootTown/scripts.pory"
	.string "Obtained a gift Pokémon - Snover!$"

Littleroot_Player_Mailbox_Text_3:
# 1977 "data/maps/LittlerootTown/scripts.pory"
	.string "The mailbox is empty.$"

Littleroot_PlayerHouseSign_Text_0:
# 1989 "data/maps/LittlerootTown/scripts.pory"
	.string "{PLAYER}'s house.$"

Littleroot_RivalHouseSign_Text_0:
# 1996 "data/maps/LittlerootTown/scripts.pory"
	.string "{RIVAL}'s house.$"

Littleroot_LabSign_Text_0:
# 2002 "data/maps/LittlerootTown/scripts.pory"
	.string "Littleroot's Pokémon Lab.$"

Littleroot_CemeterySign_Text_0:
# 2008 "data/maps/LittlerootTown/scripts.pory"
	.string "East - Littleroot Cemetery.$"

Littleroot_TownSign_Text_0:
# 2014 "data/maps/LittlerootTown/scripts.pory"
	.string "{COLOR LIGHT_GRAY}{SHADOW WHITE}Littleroot Town\p"
	.string "A t-wn t-at -an't be sh--ed -ny -ue.'\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The elements have faded most of the\n"
	.string "writing.$"

LittlerootTown_Trigger_Blocknopokes_Text_0:
# 2021 "data/maps/LittlerootTown/scripts.pory"
	.string "Professor Balsam is waiting at the lab...$"

LittlerootTown_Trigger_Blockgorival_Text_0:
# 2029 "data/maps/LittlerootTown/scripts.pory"
	.string "I should check on {RIVAL}...$"

LittlerootTown_Trigger_Blocknopokesnocemetery_Text_0:
# 2037 "data/maps/LittlerootTown/scripts.pory"
	.string "I better go to the lab first...$"

LittlerootTown_Trigger_NoEnterRival1_Text_0:
# 2053 "data/maps/LittlerootTown/scripts.pory"
	.string "Someone is yelling inside...$"

LittlerootTown_Trigger_NoEnterRival1_Text_1:
# 2058 "data/maps/LittlerootTown/scripts.pory"
	.string "DAMN YOU, KANTONIANS! You will NOT TAKE\n"
	.string "HOENN FROM US!\p"
	.string "Take this...$"

LittlerootTown_Trigger_NoEnterRival1_Text_2:
# 2067 "data/maps/LittlerootTown/scripts.pory"
	.string "ORYAAAAAAAAHH!$"

LittlerootTown_Trigger_NoEnterRival1_Text_3:
# 2070 "data/maps/LittlerootTown/scripts.pory"
	.string "Whatever is happening inside, it does\n"
	.string "not look like a good time to visit...$"

Littleroot_Idletalk_Oldman_Text_0:
# 2092 "data/maps/LittlerootTown/scripts.pory"
	.string "Hello, {PLAYER} - and hello to you too!\n"
	.string "What's your name?$"

Littleroot_Idletalk_Oldman_Text_1:
# 2096 "data/maps/LittlerootTown/scripts.pory"
	.string "I-I'm Samantha... nice to meet you, sir.$"

Littleroot_Idletalk_Oldman_Text_2:
# 2102 "data/maps/LittlerootTown/scripts.pory"
	.string "It's nice to meet you too. Thanks for\n"
	.string "taking care of my grandson.$"

Littleroot_Idletalk_Oldman_Text_3:
# 2105 "data/maps/LittlerootTown/scripts.pory"
	.string "O-oh, i-it's actually the... other way\n"
	.string "a-... n-nevermind!$"

Littleroot_Idletalk_Oldman_Text_4:
# 2109 "data/maps/LittlerootTown/scripts.pory"
	.string "It's nice to meet you too. Thanks for\n"
	.string "being friends with my granddaughter.$"

Littleroot_Idletalk_Oldman_Text_5:
# 2112 "data/maps/LittlerootTown/scripts.pory"
	.string "F-friends...? W-well... o-of course!$"

Littleroot_Idletalk_Oldman_Text_6:
# 2121 "data/maps/LittlerootTown/scripts.pory"
	.string "Why don't you come in? Balsam could use\n"
	.string "a distraction.$"

Littleroot_Idletalk_Oldman_Text_7:
# 2124 "data/maps/LittlerootTown/scripts.pory"
	.string "She may complain, but that's just how\n"
	.string "she talks. Don't take it personal.$"

Littleroot_Idletalk_Oldman_Text_8:
# 2135 "data/maps/LittlerootTown/scripts.pory"
	.string "Ah, {PLAYER}! You're finally outside!\n"
	.string "I'm so glad to see you.\p"
	.string "Please, go inside - Professor Balsam is\n"
	.string "waiting for you.\p"
	.string "I've retired, you see, and left her in\n"
	.string "charge of things.$"

Littleroot_Idletalk_Oldman_Text_9:
# 2140 "data/maps/LittlerootTown/scripts.pory"
	.string "Take some shelter, {PLAYER}. Balsam\n"
	.string "has many things she wants to tell you\l"
	.string "about.$"

Littleroot_Idletalk_Oldman_Text_10:
# 2142 "data/maps/LittlerootTown/scripts.pory"
	.string "Have you paid {RIVAL} a visit yet?\p"
	.string "Please... it would lift a weight off my\n"
	.string "old shoulders.\p"
	.string "I tried checking on them myself, but\n"
	.string "they wouldn't open the door.\p"
	.string "Perhaps they will 'open up' to you - no\n"
	.string "pun intended! Ho-ho-ho!$"

Littleroot_Idletalk_Oldman_Text_11:
# 2149 "data/maps/LittlerootTown/scripts.pory"
	.string "How are the new crutches treating you,\n"
	.string "{PLAYER}?\p"
	.string "The war left the terrain in a bad state,\n"
	.string "so watch your footing.$"

Littleroot_Idletalk_Oldman_Text_12:
# 2152 "data/maps/LittlerootTown/scripts.pory"
	.string "How is the new arm sling treating you,\n"
	.string "{PLAYER}?\p"
	.string "The war left the terrain in a bad state,\n"
	.string "so watch your footing.$"

Littleroot_Idletalk_Oldman_Text_13:
# 2157 "data/maps/LittlerootTown/scripts.pory"
	.string "Oh, is that a Voltorb Shard? You should\n"
	.string "take that to Balsam's Aide at once.$"

Littleroot_Idletalk_Oldman_Text_14:
# 2162 "data/maps/LittlerootTown/scripts.pory"
	.string "I know Professor Balsam and her Aide\n"
	.string "may seem eccentric sometimes...\p"
	.string "But they only have the best in mind for\n"
	.string "the future of Hoenn.\p"
	.string "I hope you can find it in you to support\n"
	.string "them.$"

LittlerootTown_Eventscript_Oldmanasking_Text_0:
# 2180 "data/maps/LittlerootTown/scripts.pory"
	.string "Ah, {PLAYER}!$"

LittlerootTown_Eventscript_Oldmanasking_Text_1:
# 2190 "data/maps/LittlerootTown/scripts.pory"
	.string "Such a cute {STR_VAR_1}! you have\n"
	.string "there!\p"
	.string "You see, I was wondering...$"

LittlerootTown_Eventscript_Oldmanasking_Text_2:
# 2194 "data/maps/LittlerootTown/scripts.pory"
	.string "Such a cute Pur-...\p"
	.string "Wait, isn't that Balsam's Purachu?\p"
	.string "Well, nevermind. I was wondering...$"

LittlerootTown_Eventscript_Oldmanasking_Text_3:
# 2200 "data/maps/LittlerootTown/scripts.pory"
	.string "Would you mind paying {RIVAL} a\n"
	.string "visit? You remember {RIVAL}, right?\l"
	.string "You went to the front together. Her\l"
	.string "house was destroyed during the war, so\l"
	.string "I let her stay in mine.\p"
	.string "She has been making quite a ruckus\n"
	.string "lately...\p"
	.string "It's as if she is reliving things that\n"
	.string "happened during the war.\p"
	.string "You must know what she's going\n"
	.string "through... Perhaps you can calm her\l"
	.string "down.$"

LittlerootTown_Eventscript_Oldmanasking_Text_4:
# 2205 "data/maps/LittlerootTown/scripts.pory"
	.string "Would you mind paying {RIVAL} a\n"
	.string "visit? You remember {RIVAL}, right?\l"
	.string "You went to the front together. His\l"
	.string "house was destroyed during the war, so\l"
	.string "I let him stay in mine.\p"
	.string "He has been making quite a ruckus\n"
	.string "lately...\p"
	.string "It's as if he is reliving things that\n"
	.string "happened during the war.\p"
	.string "You must know what he's going through...\n"
	.string "Perhaps you can calm him down.$"

OldManThanks_Text_0:
# 2230 "data/maps/LittlerootTown/scripts.pory"
	.string "I saw {RIVAL} storming out like a\n"
	.string "frenzied Linoone! What got into her?\p"
	.string "Well, at least you got her to leave the\n"
	.string "house. That may do her some good.\p"
	.string "Thank you for checking on her. Here,\n"
	.string "take this as a form of thanks.$"

OldManThanks_Text_1:
# 2234 "data/maps/LittlerootTown/scripts.pory"
	.string "I saw {RIVAL} storming out like a\n"
	.string "frenzied Linoone! What got into her?\p"
	.string "Well, at least you got him to leave the\n"
	.string "house. That may do him some good.\p"
	.string "Thank you for checking on him. Here,\n"
	.string "take this as a form of thanks.$"

OldManThanks_Text_2:
# 2243 "data/maps/LittlerootTown/scripts.pory"
	.string "Obtained the Better Crutches!$"

OldManThanks_Text_3:
# 2247 "data/maps/LittlerootTown/scripts.pory"
	.string "These are some old crutches of mine.\p"
	.string "I noticed yours were not in the best\n"
	.string "shape - these should help you move\l"
	.string "around better.$"

OldManThanks_Text_4:
# 2250 "data/maps/LittlerootTown/scripts.pory"
	.string "Obtained the Better Arm Sling!$"

OldManThanks_Text_5:
# 2254 "data/maps/LittlerootTown/scripts.pory"
	.string "This is an old arm sling of mine.\p"
	.string "I noticed yours is not in the best\n"
	.string "shape - this one should secure your arm\l"
	.string "better, so you can move around more\l"
	.string "easily.$"

OldManThanks_Text_6:
# 2257 "data/maps/LittlerootTown/scripts.pory"
	.string "Look at you. You have gone through so\n"
	.string "much, but you are still standing.$"

OldManThanks_Text_7:
# 2260 "data/maps/LittlerootTown/scripts.pory"
	.string "Your parents would be proud. You came\n"
	.string "out tough, just like them.$"

OldManThanks_Text_8:
# 2263 "data/maps/LittlerootTown/scripts.pory"
	.string "Well, off you go now! Please, take care\n"
	.string "out there.\p"
	.string "Despite Devon's claims, Hoenn is far\n"
	.string "from a 'safe' place these days...\p"
	.string "But have faith in your Pokémon, and you\n"
	.string "will be fine. Good bye!$"
