# 1 "data/maps/LittlerootTown/scripts.pory"

# 2 "data/maps/LittlerootTown/scripts.pory"

# 3 "data/maps/LittlerootTown/scripts.pory"
# 1 "data/maps/LittlerootTown/scripts.pory"
# 4 "data/maps/LittlerootTown/scripts.pory"

# 5 "data/maps/LittlerootTown/scripts.pory"
# 2 "data/maps/LittlerootTown/scripts.pory"
# 6 "data/maps/LittlerootTown/scripts.pory"

# 7 "data/maps/LittlerootTown/scripts.pory"
# 3 "data/maps/LittlerootTown/scripts.pory"
# 8 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_MapScripts::
# 9 "data/maps/LittlerootTown/scripts.pory"
# 4 "data/maps/LittlerootTown/scripts.pory"
# 10 "data/maps/LittlerootTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LittlerootTown_OnTransition
# 11 "data/maps/LittlerootTown/scripts.pory"
# 5 "data/maps/LittlerootTown/scripts.pory"
# 12 "data/maps/LittlerootTown/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, LittlerootTown_OnFrame
# 13 "data/maps/LittlerootTown/scripts.pory"
# 6 "data/maps/LittlerootTown/scripts.pory"
# 14 "data/maps/LittlerootTown/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, LittlerootTown_OnWarp
# 15 "data/maps/LittlerootTown/scripts.pory"
# 7 "data/maps/LittlerootTown/scripts.pory"
# 16 "data/maps/LittlerootTown/scripts.pory"
	.byte 0
# 17 "data/maps/LittlerootTown/scripts.pory"
# 8 "data/maps/LittlerootTown/scripts.pory"
# 18 "data/maps/LittlerootTown/scripts.pory"

# 19 "data/maps/LittlerootTown/scripts.pory"
# 9 "data/maps/LittlerootTown/scripts.pory"
# 20 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_TOWN_STATE
# 21 "data/maps/LittlerootTown/scripts.pory"
# 10 "data/maps/LittlerootTown/scripts.pory"
# 22 "data/maps/LittlerootTown/scripts.pory"
	@ 1: Met Rival
# 23 "data/maps/LittlerootTown/scripts.pory"
# 11 "data/maps/LittlerootTown/scripts.pory"
# 24 "data/maps/LittlerootTown/scripts.pory"
	@ 2: Saving Birch
# 25 "data/maps/LittlerootTown/scripts.pory"
# 12 "data/maps/LittlerootTown/scripts.pory"
# 26 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Received Pokedex
# 27 "data/maps/LittlerootTown/scripts.pory"
# 13 "data/maps/LittlerootTown/scripts.pory"
# 28 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Received Running Shoes
# 29 "data/maps/LittlerootTown/scripts.pory"
# 14 "data/maps/LittlerootTown/scripts.pory"
# 30 "data/maps/LittlerootTown/scripts.pory"

# 31 "data/maps/LittlerootTown/scripts.pory"
# 15 "data/maps/LittlerootTown/scripts.pory"
# 32 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_INTRO_STATE
# 33 "data/maps/LittlerootTown/scripts.pory"
# 16 "data/maps/LittlerootTown/scripts.pory"
# 34 "data/maps/LittlerootTown/scripts.pory"
	@ 1: In truck male
# 35 "data/maps/LittlerootTown/scripts.pory"
# 17 "data/maps/LittlerootTown/scripts.pory"
# 36 "data/maps/LittlerootTown/scripts.pory"
	@ 2: In truck female
# 37 "data/maps/LittlerootTown/scripts.pory"
# 18 "data/maps/LittlerootTown/scripts.pory"
# 38 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Entered house
# 39 "data/maps/LittlerootTown/scripts.pory"
# 19 "data/maps/LittlerootTown/scripts.pory"
# 40 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Told to go set clock
# 41 "data/maps/LittlerootTown/scripts.pory"
# 20 "data/maps/LittlerootTown/scripts.pory"
# 42 "data/maps/LittlerootTown/scripts.pory"
	@ 5: Entered 2F to set clock
# 43 "data/maps/LittlerootTown/scripts.pory"
# 21 "data/maps/LittlerootTown/scripts.pory"
# 44 "data/maps/LittlerootTown/scripts.pory"
	@ 6: Set clock
# 45 "data/maps/LittlerootTown/scripts.pory"
# 22 "data/maps/LittlerootTown/scripts.pory"
# 46 "data/maps/LittlerootTown/scripts.pory"
	@ 7: Told to go meet rival
# 47 "data/maps/LittlerootTown/scripts.pory"
# 23 "data/maps/LittlerootTown/scripts.pory"
# 48 "data/maps/LittlerootTown/scripts.pory"

# 49 "data/maps/LittlerootTown/scripts.pory"
# 24 "data/maps/LittlerootTown/scripts.pory"
# 50 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_HOUSES_STATE_MAY
# 51 "data/maps/LittlerootTown/scripts.pory"
# 25 "data/maps/LittlerootTown/scripts.pory"
# 52 "data/maps/LittlerootTown/scripts.pory"
	@                    and VAR_LITTLEROOT_HOUSES_STATE_BRENDAN
# 53 "data/maps/LittlerootTown/scripts.pory"
# 26 "data/maps/LittlerootTown/scripts.pory"
# 54 "data/maps/LittlerootTown/scripts.pory"
	@ 1: On Truck (and is corresponding gender)
# 55 "data/maps/LittlerootTown/scripts.pory"
# 27 "data/maps/LittlerootTown/scripts.pory"
# 56 "data/maps/LittlerootTown/scripts.pory"
	@ 2: Met Rival's Mom (and is corresponding gender)
# 57 "data/maps/LittlerootTown/scripts.pory"
# 28 "data/maps/LittlerootTown/scripts.pory"
# 58 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Entered Hall of Fame
# 59 "data/maps/LittlerootTown/scripts.pory"
# 29 "data/maps/LittlerootTown/scripts.pory"
# 60 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Completed Lati TV / SS Ticket event
# 61 "data/maps/LittlerootTown/scripts.pory"
# 30 "data/maps/LittlerootTown/scripts.pory"
# 62 "data/maps/LittlerootTown/scripts.pory"
	@ 5: Exited house after above event
# 63 "data/maps/LittlerootTown/scripts.pory"
# 31 "data/maps/LittlerootTown/scripts.pory"
# 64 "data/maps/LittlerootTown/scripts.pory"

# 65 "data/maps/LittlerootTown/scripts.pory"
# 32 "data/maps/LittlerootTown/scripts.pory"
# 66 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_RIVAL_STATE
# 67 "data/maps/LittlerootTown/scripts.pory"
# 33 "data/maps/LittlerootTown/scripts.pory"
# 68 "data/maps/LittlerootTown/scripts.pory"
	@ 1: Never occurs
# 69 "data/maps/LittlerootTown/scripts.pory"
# 34 "data/maps/LittlerootTown/scripts.pory"
# 70 "data/maps/LittlerootTown/scripts.pory"
	@ 2: Entered Rival's bedroom
# 71 "data/maps/LittlerootTown/scripts.pory"
# 35 "data/maps/LittlerootTown/scripts.pory"
# 72 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Met Rival
# 73 "data/maps/LittlerootTown/scripts.pory"
# 36 "data/maps/LittlerootTown/scripts.pory"
# 74 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Received Pokedex
# 75 "data/maps/LittlerootTown/scripts.pory"
# 37 "data/maps/LittlerootTown/scripts.pory"
# 76 "data/maps/LittlerootTown/scripts.pory"

# 77 "data/maps/LittlerootTown/scripts.pory"
# 38 "data/maps/LittlerootTown/scripts.pory"
# 78 "data/maps/LittlerootTown/scripts.pory"

# 79 "data/maps/LittlerootTown/scripts.pory"
# 39 "data/maps/LittlerootTown/scripts.pory"
# 80 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_OnTransition:
# 81 "data/maps/LittlerootTown/scripts.pory"
# 40 "data/maps/LittlerootTown/scripts.pory"
# 82 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_VISITED_LITTLEROOT_TOWN
# 83 "data/maps/LittlerootTown/scripts.pory"
# 41 "data/maps/LittlerootTown/scripts.pory"
# 84 "data/maps/LittlerootTown/scripts.pory"
	call Common_EventScript_SetupRivalGfxId
# 85 "data/maps/LittlerootTown/scripts.pory"
# 42 "data/maps/LittlerootTown/scripts.pory"
# 86 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_INTRO_STATE, 2, LittlerootTown_EventScript_MoveMomToMaysDoor
# 87 "data/maps/LittlerootTown/scripts.pory"
# 43 "data/maps/LittlerootTown/scripts.pory"
# 88 "data/maps/LittlerootTown/scripts.pory"
	call_if_unset FLAG_RESCUED_BIRCH, LittlerootTown_EventScript_SetTwinPos
# 89 "data/maps/LittlerootTown/scripts.pory"
# 44 "data/maps/LittlerootTown/scripts.pory"
# 90 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_TOWN_STATE, 3, LittlerootTown_EventScript_SetMomStandingInFrontOfDoorPos
# 91 "data/maps/LittlerootTown/scripts.pory"
# 45 "data/maps/LittlerootTown/scripts.pory"
# 92 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_HOUSES_STATE_MAY, 4, LittlerootTown_EventScript_SetExitedHouseAfterLatiSSTicketEvent
# 93 "data/maps/LittlerootTown/scripts.pory"
# 46 "data/maps/LittlerootTown/scripts.pory"
# 94 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_HOUSES_STATE_BRENDAN, 4, LittlerootTown_EventScript_SetExitedHouseAfterLatiSSTicketEvent
# 95 "data/maps/LittlerootTown/scripts.pory"
# 47 "data/maps/LittlerootTown/scripts.pory"
# 96 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_OLDALE_RIVAL_STATE, 1, LittlerootTown_EventScript_MoveRivalFromOldale
# 97 "data/maps/LittlerootTown/scripts.pory"
# 48 "data/maps/LittlerootTown/scripts.pory"
# 98 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_RIVAL_STATE, 3, LittlerootTown_EventScript_SetRivalLeftForRoute103
# 99 "data/maps/LittlerootTown/scripts.pory"
# 49 "data/maps/LittlerootTown/scripts.pory"
# 100 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 1, LittlerootTown_EventScript_HideMapNamePopup
# 101 "data/maps/LittlerootTown/scripts.pory"
# 50 "data/maps/LittlerootTown/scripts.pory"
# 102 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 2, LittlerootTown_EventScript_LeftLabAfterDexUpgrade
# 103 "data/maps/LittlerootTown/scripts.pory"
# 51 "data/maps/LittlerootTown/scripts.pory"
# 104 "data/maps/LittlerootTown/scripts.pory"
	end
# 105 "data/maps/LittlerootTown/scripts.pory"
# 52 "data/maps/LittlerootTown/scripts.pory"
# 106 "data/maps/LittlerootTown/scripts.pory"

# 107 "data/maps/LittlerootTown/scripts.pory"
# 53 "data/maps/LittlerootTown/scripts.pory"
# 108 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_LeftLabAfterDexUpgrade::
# 109 "data/maps/LittlerootTown/scripts.pory"
# 54 "data/maps/LittlerootTown/scripts.pory"
# 110 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 3
# 111 "data/maps/LittlerootTown/scripts.pory"
# 55 "data/maps/LittlerootTown/scripts.pory"
# 112 "data/maps/LittlerootTown/scripts.pory"
	return
# 113 "data/maps/LittlerootTown/scripts.pory"
# 56 "data/maps/LittlerootTown/scripts.pory"
# 114 "data/maps/LittlerootTown/scripts.pory"

# 115 "data/maps/LittlerootTown/scripts.pory"
# 57 "data/maps/LittlerootTown/scripts.pory"
# 116 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_HideMapNamePopup::
# 117 "data/maps/LittlerootTown/scripts.pory"
# 58 "data/maps/LittlerootTown/scripts.pory"
# 118 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_MAP_NAME_POPUP
# 119 "data/maps/LittlerootTown/scripts.pory"
# 59 "data/maps/LittlerootTown/scripts.pory"
# 120 "data/maps/LittlerootTown/scripts.pory"
	return
# 121 "data/maps/LittlerootTown/scripts.pory"
# 60 "data/maps/LittlerootTown/scripts.pory"
# 122 "data/maps/LittlerootTown/scripts.pory"

# 123 "data/maps/LittlerootTown/scripts.pory"
# 61 "data/maps/LittlerootTown/scripts.pory"
# 124 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalLeftForRoute103::
# 125 "data/maps/LittlerootTown/scripts.pory"
# 62 "data/maps/LittlerootTown/scripts.pory"
# 126 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_RIVAL_LEFT_FOR_ROUTE103
# 127 "data/maps/LittlerootTown/scripts.pory"
# 63 "data/maps/LittlerootTown/scripts.pory"
# 128 "data/maps/LittlerootTown/scripts.pory"
	return
# 129 "data/maps/LittlerootTown/scripts.pory"
# 64 "data/maps/LittlerootTown/scripts.pory"
# 130 "data/maps/LittlerootTown/scripts.pory"

# 131 "data/maps/LittlerootTown/scripts.pory"
# 65 "data/maps/LittlerootTown/scripts.pory"
# 132 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MoveRivalFromOldale::
# 133 "data/maps/LittlerootTown/scripts.pory"
# 66 "data/maps/LittlerootTown/scripts.pory"
# 134 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_OLDALE_RIVAL_STATE, 2
# 135 "data/maps/LittlerootTown/scripts.pory"
# 67 "data/maps/LittlerootTown/scripts.pory"
# 136 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_OLDALE_TOWN_RIVAL
# 137 "data/maps/LittlerootTown/scripts.pory"
# 68 "data/maps/LittlerootTown/scripts.pory"
# 138 "data/maps/LittlerootTown/scripts.pory"
	return
# 139 "data/maps/LittlerootTown/scripts.pory"
# 69 "data/maps/LittlerootTown/scripts.pory"
# 140 "data/maps/LittlerootTown/scripts.pory"

# 141 "data/maps/LittlerootTown/scripts.pory"
# 70 "data/maps/LittlerootTown/scripts.pory"
# 142 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetExitedHouseAfterLatiSSTicketEvent::
# 143 "data/maps/LittlerootTown/scripts.pory"
# 71 "data/maps/LittlerootTown/scripts.pory"
# 144 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_HOUSES_STATE_MAY, 5
# 145 "data/maps/LittlerootTown/scripts.pory"
# 72 "data/maps/LittlerootTown/scripts.pory"
# 146 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_HOUSES_STATE_BRENDAN, 5
# 147 "data/maps/LittlerootTown/scripts.pory"
# 73 "data/maps/LittlerootTown/scripts.pory"
# 148 "data/maps/LittlerootTown/scripts.pory"
	return
# 149 "data/maps/LittlerootTown/scripts.pory"
# 74 "data/maps/LittlerootTown/scripts.pory"
# 150 "data/maps/LittlerootTown/scripts.pory"

# 151 "data/maps/LittlerootTown/scripts.pory"
# 75 "data/maps/LittlerootTown/scripts.pory"
# 152 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MoveMomToMaysDoor::
# 153 "data/maps/LittlerootTown/scripts.pory"
	return
# 154 "data/maps/LittlerootTown/scripts.pory"
# 78 "data/maps/LittlerootTown/scripts.pory"
# 155 "data/maps/LittlerootTown/scripts.pory"

# 156 "data/maps/LittlerootTown/scripts.pory"
# 79 "data/maps/LittlerootTown/scripts.pory"
# 157 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetTwinPos::
# 158 "data/maps/LittlerootTown/scripts.pory"
# 80 "data/maps/LittlerootTown/scripts.pory"
# 159 "data/maps/LittlerootTown/scripts.pory"
	goto_if_eq VAR_LITTLEROOT_TOWN_STATE, 0, LittlerootTown_EventScript_SetTwinGuardingRoutePos
# 160 "data/maps/LittlerootTown/scripts.pory"
	return
# 161 "data/maps/LittlerootTown/scripts.pory"
# 84 "data/maps/LittlerootTown/scripts.pory"
# 162 "data/maps/LittlerootTown/scripts.pory"

# 163 "data/maps/LittlerootTown/scripts.pory"
# 85 "data/maps/LittlerootTown/scripts.pory"
# 164 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetTwinGuardingRoutePos::
# 165 "data/maps/LittlerootTown/scripts.pory"
	return
# 166 "data/maps/LittlerootTown/scripts.pory"
# 89 "data/maps/LittlerootTown/scripts.pory"
# 167 "data/maps/LittlerootTown/scripts.pory"

# 168 "data/maps/LittlerootTown/scripts.pory"
# 90 "data/maps/LittlerootTown/scripts.pory"
# 169 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetMomStandingInFrontOfDoorPos::
# 170 "data/maps/LittlerootTown/scripts.pory"
# 91 "data/maps/LittlerootTown/scripts.pory"
# 171 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE
# 172 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 173 "data/maps/LittlerootTown/scripts.pory"
# 94 "data/maps/LittlerootTown/scripts.pory"
# 174 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetMomInFrontOfDoorMale
# 175 "data/maps/LittlerootTown/scripts.pory"
# 95 "data/maps/LittlerootTown/scripts.pory"
# 176 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_SetMomInFrontOfDoorFemale
# 177 "data/maps/LittlerootTown/scripts.pory"
# 96 "data/maps/LittlerootTown/scripts.pory"
# 178 "data/maps/LittlerootTown/scripts.pory"
	return
# 179 "data/maps/LittlerootTown/scripts.pory"
# 97 "data/maps/LittlerootTown/scripts.pory"
# 180 "data/maps/LittlerootTown/scripts.pory"

# 181 "data/maps/LittlerootTown/scripts.pory"
# 98 "data/maps/LittlerootTown/scripts.pory"
# 182 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetMomInFrontOfDoorMale::
# 183 "data/maps/LittlerootTown/scripts.pory"
	return
# 184 "data/maps/LittlerootTown/scripts.pory"
# 101 "data/maps/LittlerootTown/scripts.pory"
# 185 "data/maps/LittlerootTown/scripts.pory"

# 186 "data/maps/LittlerootTown/scripts.pory"
# 102 "data/maps/LittlerootTown/scripts.pory"
# 187 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetMomInFrontOfDoorFemale::
# 188 "data/maps/LittlerootTown/scripts.pory"
	return
# 189 "data/maps/LittlerootTown/scripts.pory"
# 105 "data/maps/LittlerootTown/scripts.pory"
# 190 "data/maps/LittlerootTown/scripts.pory"

# 191 "data/maps/LittlerootTown/scripts.pory"
# 106 "data/maps/LittlerootTown/scripts.pory"
# 192 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_OnFrame:
# 193 "data/maps/LittlerootTown/scripts.pory"
# 107 "data/maps/LittlerootTown/scripts.pory"
# 194 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_LITTLEROOT_INTRO_STATE, 1, LittlerootTown_EventScript_StepOffTruckMale
# 195 "data/maps/LittlerootTown/scripts.pory"
# 108 "data/maps/LittlerootTown/scripts.pory"
# 196 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_LITTLEROOT_INTRO_STATE, 2, LittlerootTown_EventScript_StepOffTruckFemale
# 197 "data/maps/LittlerootTown/scripts.pory"
# 109 "data/maps/LittlerootTown/scripts.pory"
# 198 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 1, LittlerootTown_EventScript_BeginDexUpgradeScene
# 199 "data/maps/LittlerootTown/scripts.pory"
# 110 "data/maps/LittlerootTown/scripts.pory"
# 200 "data/maps/LittlerootTown/scripts.pory"
	.2byte 0
# 201 "data/maps/LittlerootTown/scripts.pory"
# 111 "data/maps/LittlerootTown/scripts.pory"
# 202 "data/maps/LittlerootTown/scripts.pory"

# 203 "data/maps/LittlerootTown/scripts.pory"
# 112 "data/maps/LittlerootTown/scripts.pory"
# 204 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_StepOffTruckMale::
# 205 "data/maps/LittlerootTown/scripts.pory"
# 113 "data/maps/LittlerootTown/scripts.pory"
# 206 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 207 "data/maps/LittlerootTown/scripts.pory"
# 114 "data/maps/LittlerootTown/scripts.pory"
# 208 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8004, 5
# 209 "data/maps/LittlerootTown/scripts.pory"
# 115 "data/maps/LittlerootTown/scripts.pory"
# 210 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8005, 8
# 211 "data/maps/LittlerootTown/scripts.pory"
# 116 "data/maps/LittlerootTown/scripts.pory"
# 212 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GoInsideWithMom
# 213 "data/maps/LittlerootTown/scripts.pory"
# 117 "data/maps/LittlerootTown/scripts.pory"
# 214 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_TRUCK
# 215 "data/maps/LittlerootTown/scripts.pory"
# 118 "data/maps/LittlerootTown/scripts.pory"
# 216 "data/maps/LittlerootTown/scripts.pory"
	warpsilent MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F, 8, 8
# 217 "data/maps/LittlerootTown/scripts.pory"
# 119 "data/maps/LittlerootTown/scripts.pory"
# 218 "data/maps/LittlerootTown/scripts.pory"
	waitstate
# 219 "data/maps/LittlerootTown/scripts.pory"
# 120 "data/maps/LittlerootTown/scripts.pory"
# 220 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 221 "data/maps/LittlerootTown/scripts.pory"
# 121 "data/maps/LittlerootTown/scripts.pory"
# 222 "data/maps/LittlerootTown/scripts.pory"
	end
# 223 "data/maps/LittlerootTown/scripts.pory"
# 122 "data/maps/LittlerootTown/scripts.pory"
# 224 "data/maps/LittlerootTown/scripts.pory"

# 225 "data/maps/LittlerootTown/scripts.pory"
# 123 "data/maps/LittlerootTown/scripts.pory"
# 226 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_StepOffTruckFemale::
# 227 "data/maps/LittlerootTown/scripts.pory"
# 124 "data/maps/LittlerootTown/scripts.pory"
# 228 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 229 "data/maps/LittlerootTown/scripts.pory"
# 125 "data/maps/LittlerootTown/scripts.pory"
# 230 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8004, 14
# 231 "data/maps/LittlerootTown/scripts.pory"
# 126 "data/maps/LittlerootTown/scripts.pory"
# 232 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8005, 8
# 233 "data/maps/LittlerootTown/scripts.pory"
# 127 "data/maps/LittlerootTown/scripts.pory"
# 234 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GoInsideWithMom
# 235 "data/maps/LittlerootTown/scripts.pory"
# 128 "data/maps/LittlerootTown/scripts.pory"
# 236 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_TRUCK
# 237 "data/maps/LittlerootTown/scripts.pory"
# 129 "data/maps/LittlerootTown/scripts.pory"
# 238 "data/maps/LittlerootTown/scripts.pory"
	warpsilent MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F, 2, 8
# 239 "data/maps/LittlerootTown/scripts.pory"
# 130 "data/maps/LittlerootTown/scripts.pory"
# 240 "data/maps/LittlerootTown/scripts.pory"
	waitstate
# 241 "data/maps/LittlerootTown/scripts.pory"
# 131 "data/maps/LittlerootTown/scripts.pory"
# 242 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 243 "data/maps/LittlerootTown/scripts.pory"
# 132 "data/maps/LittlerootTown/scripts.pory"
# 244 "data/maps/LittlerootTown/scripts.pory"
	end
# 245 "data/maps/LittlerootTown/scripts.pory"
# 133 "data/maps/LittlerootTown/scripts.pory"
# 246 "data/maps/LittlerootTown/scripts.pory"

# 247 "data/maps/LittlerootTown/scripts.pory"
# 134 "data/maps/LittlerootTown/scripts.pory"
# 248 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoInsideWithMom::
# 249 "data/maps/LittlerootTown/scripts.pory"
# 135 "data/maps/LittlerootTown/scripts.pory"
# 250 "data/maps/LittlerootTown/scripts.pory"
	delay 15
# 251 "data/maps/LittlerootTown/scripts.pory"
# 136 "data/maps/LittlerootTown/scripts.pory"
# 252 "data/maps/LittlerootTown/scripts.pory"
	playse SE_LEDGE
# 253 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, LittlerootTown_Movement_PlayerStepOffTruck
# 254 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 255 "data/maps/LittlerootTown/scripts.pory"
# 139 "data/maps/LittlerootTown/scripts.pory"
# 256 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8004, VAR_0x8005
# 257 "data/maps/LittlerootTown/scripts.pory"
# 140 "data/maps/LittlerootTown/scripts.pory"
# 258 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 259 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 260 "data/maps/LittlerootTown/scripts.pory"
# 144 "data/maps/LittlerootTown/scripts.pory"
# 261 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8004, VAR_0x8005
# 262 "data/maps/LittlerootTown/scripts.pory"
# 145 "data/maps/LittlerootTown/scripts.pory"
# 263 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 264 "data/maps/LittlerootTown/scripts.pory"
# 146 "data/maps/LittlerootTown/scripts.pory"
# 265 "data/maps/LittlerootTown/scripts.pory"
	delay 10
# 266 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 267 "data/maps/LittlerootTown/scripts.pory"
# 149 "data/maps/LittlerootTown/scripts.pory"
# 268 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_OurNewHomeLetsGoInside, MSGBOX_DEFAULT
# 269 "data/maps/LittlerootTown/scripts.pory"
# 150 "data/maps/LittlerootTown/scripts.pory"
# 270 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 271 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, LittlerootTown_Movement_PlayerApproachDoor
# 272 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 273 "data/maps/LittlerootTown/scripts.pory"
# 154 "data/maps/LittlerootTown/scripts.pory"
# 274 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8004, VAR_0x8005
# 275 "data/maps/LittlerootTown/scripts.pory"
# 155 "data/maps/LittlerootTown/scripts.pory"
# 276 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 277 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, LittlerootTown_Movement_PlayerEnterHouse
# 278 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 279 "data/maps/LittlerootTown/scripts.pory"
# 159 "data/maps/LittlerootTown/scripts.pory"
# 280 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE
# 281 "data/maps/LittlerootTown/scripts.pory"
# 160 "data/maps/LittlerootTown/scripts.pory"
# 282 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_INTRO_STATE, 3
# 283 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat LOCALID_PLAYER, MAP_LITTLEROOT_TOWN
# 284 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8004, VAR_0x8005
# 285 "data/maps/LittlerootTown/scripts.pory"
# 163 "data/maps/LittlerootTown/scripts.pory"
# 286 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 287 "data/maps/LittlerootTown/scripts.pory"
# 164 "data/maps/LittlerootTown/scripts.pory"
# 288 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_FAT_MAN
# 289 "data/maps/LittlerootTown/scripts.pory"
# 165 "data/maps/LittlerootTown/scripts.pory"
# 290 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_MAP_NAME_POPUP
# 291 "data/maps/LittlerootTown/scripts.pory"
# 166 "data/maps/LittlerootTown/scripts.pory"
# 292 "data/maps/LittlerootTown/scripts.pory"
	return
# 293 "data/maps/LittlerootTown/scripts.pory"
# 167 "data/maps/LittlerootTown/scripts.pory"
# 294 "data/maps/LittlerootTown/scripts.pory"

# 295 "data/maps/LittlerootTown/scripts.pory"
# 168 "data/maps/LittlerootTown/scripts.pory"
# 296 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomExitHouse:
# 297 "data/maps/LittlerootTown/scripts.pory"
# 169 "data/maps/LittlerootTown/scripts.pory"
# 298 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 299 "data/maps/LittlerootTown/scripts.pory"
# 170 "data/maps/LittlerootTown/scripts.pory"
# 300 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 301 "data/maps/LittlerootTown/scripts.pory"
# 171 "data/maps/LittlerootTown/scripts.pory"
# 302 "data/maps/LittlerootTown/scripts.pory"

# 303 "data/maps/LittlerootTown/scripts.pory"
# 172 "data/maps/LittlerootTown/scripts.pory"
# 304 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerAtTruck:
# 305 "data/maps/LittlerootTown/scripts.pory"
# 173 "data/maps/LittlerootTown/scripts.pory"
# 306 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 307 "data/maps/LittlerootTown/scripts.pory"
# 174 "data/maps/LittlerootTown/scripts.pory"
# 308 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_left
# 309 "data/maps/LittlerootTown/scripts.pory"
# 175 "data/maps/LittlerootTown/scripts.pory"
# 310 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 311 "data/maps/LittlerootTown/scripts.pory"
# 176 "data/maps/LittlerootTown/scripts.pory"
# 312 "data/maps/LittlerootTown/scripts.pory"

# 313 "data/maps/LittlerootTown/scripts.pory"
# 177 "data/maps/LittlerootTown/scripts.pory"
# 314 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachDoor:
# 315 "data/maps/LittlerootTown/scripts.pory"
# 178 "data/maps/LittlerootTown/scripts.pory"
# 316 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 317 "data/maps/LittlerootTown/scripts.pory"
# 179 "data/maps/LittlerootTown/scripts.pory"
# 318 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 319 "data/maps/LittlerootTown/scripts.pory"
# 180 "data/maps/LittlerootTown/scripts.pory"
# 320 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 321 "data/maps/LittlerootTown/scripts.pory"
# 181 "data/maps/LittlerootTown/scripts.pory"
# 322 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 323 "data/maps/LittlerootTown/scripts.pory"
# 182 "data/maps/LittlerootTown/scripts.pory"
# 324 "data/maps/LittlerootTown/scripts.pory"

# 325 "data/maps/LittlerootTown/scripts.pory"
# 183 "data/maps/LittlerootTown/scripts.pory"
# 326 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomEnterHouse:
# 327 "data/maps/LittlerootTown/scripts.pory"
# 184 "data/maps/LittlerootTown/scripts.pory"
# 328 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 329 "data/maps/LittlerootTown/scripts.pory"
# 185 "data/maps/LittlerootTown/scripts.pory"
# 330 "data/maps/LittlerootTown/scripts.pory"
	set_invisible
# 331 "data/maps/LittlerootTown/scripts.pory"
# 186 "data/maps/LittlerootTown/scripts.pory"
# 332 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 333 "data/maps/LittlerootTown/scripts.pory"
# 187 "data/maps/LittlerootTown/scripts.pory"
# 334 "data/maps/LittlerootTown/scripts.pory"

# 335 "data/maps/LittlerootTown/scripts.pory"
# 188 "data/maps/LittlerootTown/scripts.pory"
# 336 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PlayerApproachDoor:
# 337 "data/maps/LittlerootTown/scripts.pory"
# 189 "data/maps/LittlerootTown/scripts.pory"
# 338 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 339 "data/maps/LittlerootTown/scripts.pory"
# 190 "data/maps/LittlerootTown/scripts.pory"
# 340 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 341 "data/maps/LittlerootTown/scripts.pory"
# 191 "data/maps/LittlerootTown/scripts.pory"
# 342 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 343 "data/maps/LittlerootTown/scripts.pory"
# 192 "data/maps/LittlerootTown/scripts.pory"
# 344 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 345 "data/maps/LittlerootTown/scripts.pory"
# 193 "data/maps/LittlerootTown/scripts.pory"
# 346 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 347 "data/maps/LittlerootTown/scripts.pory"
# 194 "data/maps/LittlerootTown/scripts.pory"
# 348 "data/maps/LittlerootTown/scripts.pory"

# 349 "data/maps/LittlerootTown/scripts.pory"
# 195 "data/maps/LittlerootTown/scripts.pory"
# 350 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PlayerEnterHouse:
# 351 "data/maps/LittlerootTown/scripts.pory"
# 196 "data/maps/LittlerootTown/scripts.pory"
# 352 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 353 "data/maps/LittlerootTown/scripts.pory"
# 197 "data/maps/LittlerootTown/scripts.pory"
# 354 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 355 "data/maps/LittlerootTown/scripts.pory"
# 198 "data/maps/LittlerootTown/scripts.pory"
# 356 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 357 "data/maps/LittlerootTown/scripts.pory"
# 199 "data/maps/LittlerootTown/scripts.pory"
# 358 "data/maps/LittlerootTown/scripts.pory"

# 359 "data/maps/LittlerootTown/scripts.pory"
# 200 "data/maps/LittlerootTown/scripts.pory"
# 360 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PlayerStepOffTruck:
# 361 "data/maps/LittlerootTown/scripts.pory"
# 201 "data/maps/LittlerootTown/scripts.pory"
# 362 "data/maps/LittlerootTown/scripts.pory"
	jump_right
# 363 "data/maps/LittlerootTown/scripts.pory"
# 202 "data/maps/LittlerootTown/scripts.pory"
# 364 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 365 "data/maps/LittlerootTown/scripts.pory"
# 203 "data/maps/LittlerootTown/scripts.pory"
# 366 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 367 "data/maps/LittlerootTown/scripts.pory"
# 204 "data/maps/LittlerootTown/scripts.pory"
# 368 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 369 "data/maps/LittlerootTown/scripts.pory"
# 205 "data/maps/LittlerootTown/scripts.pory"
# 370 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 371 "data/maps/LittlerootTown/scripts.pory"
# 206 "data/maps/LittlerootTown/scripts.pory"
# 372 "data/maps/LittlerootTown/scripts.pory"

# 373 "data/maps/LittlerootTown/scripts.pory"
# 207 "data/maps/LittlerootTown/scripts.pory"
# 374 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BeginDexUpgradeScene::
# 375 "data/maps/LittlerootTown/scripts.pory"
# 208 "data/maps/LittlerootTown/scripts.pory"
# 376 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 377 "data/maps/LittlerootTown/scripts.pory"
# 209 "data/maps/LittlerootTown/scripts.pory"
# 378 "data/maps/LittlerootTown/scripts.pory"
	playse SE_PIN
# 379 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 380 "data/maps/LittlerootTown/scripts.pory"
# 212 "data/maps/LittlerootTown/scripts.pory"
# 381 "data/maps/LittlerootTown/scripts.pory"
	delay 80
# 382 "data/maps/LittlerootTown/scripts.pory"
# 213 "data/maps/LittlerootTown/scripts.pory"
# 383 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_BirchSomethingToShowYouAtLab, MSGBOX_DEFAULT
# 384 "data/maps/LittlerootTown/scripts.pory"
# 214 "data/maps/LittlerootTown/scripts.pory"
# 385 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 386 "data/maps/LittlerootTown/scripts.pory"
# 215 "data/maps/LittlerootTown/scripts.pory"
# 387 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_RIVAL
# 388 "data/maps/LittlerootTown/scripts.pory"
# 216 "data/maps/LittlerootTown/scripts.pory"
# 389 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCH
# 390 "data/maps/LittlerootTown/scripts.pory"
# 217 "data/maps/LittlerootTown/scripts.pory"
# 391 "data/maps/LittlerootTown/scripts.pory"
	delay 20
# 392 "data/maps/LittlerootTown/scripts.pory"
# 218 "data/maps/LittlerootTown/scripts.pory"
# 393 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_MAP_NAME_POPUP
# 394 "data/maps/LittlerootTown/scripts.pory"
# 219 "data/maps/LittlerootTown/scripts.pory"
# 395 "data/maps/LittlerootTown/scripts.pory"
	warp MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB, 6, 5
# 396 "data/maps/LittlerootTown/scripts.pory"
# 220 "data/maps/LittlerootTown/scripts.pory"
# 397 "data/maps/LittlerootTown/scripts.pory"
	waitstate
# 398 "data/maps/LittlerootTown/scripts.pory"
# 221 "data/maps/LittlerootTown/scripts.pory"
# 399 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 400 "data/maps/LittlerootTown/scripts.pory"
# 222 "data/maps/LittlerootTown/scripts.pory"
# 401 "data/maps/LittlerootTown/scripts.pory"
	end
# 402 "data/maps/LittlerootTown/scripts.pory"
# 223 "data/maps/LittlerootTown/scripts.pory"
# 403 "data/maps/LittlerootTown/scripts.pory"

# 404 "data/maps/LittlerootTown/scripts.pory"
# 224 "data/maps/LittlerootTown/scripts.pory"
# 405 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_OnWarp:
# 406 "data/maps/LittlerootTown/scripts.pory"
# 225 "data/maps/LittlerootTown/scripts.pory"
# 407 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 1, LittlerootTown_EventScript_SetRivalBirchPosForDexUpgrade
# 408 "data/maps/LittlerootTown/scripts.pory"
# 226 "data/maps/LittlerootTown/scripts.pory"
# 409 "data/maps/LittlerootTown/scripts.pory"
	.2byte 0
# 410 "data/maps/LittlerootTown/scripts.pory"
# 227 "data/maps/LittlerootTown/scripts.pory"
# 411 "data/maps/LittlerootTown/scripts.pory"

# 412 "data/maps/LittlerootTown/scripts.pory"
# 228 "data/maps/LittlerootTown/scripts.pory"
# 413 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalBirchPosForDexUpgrade::
# 414 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 415 "data/maps/LittlerootTown/scripts.pory"
# 232 "data/maps/LittlerootTown/scripts.pory"
# 416 "data/maps/LittlerootTown/scripts.pory"
	goto_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeMale
# 417 "data/maps/LittlerootTown/scripts.pory"
# 233 "data/maps/LittlerootTown/scripts.pory"
# 418 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeFemale
# 419 "data/maps/LittlerootTown/scripts.pory"
# 234 "data/maps/LittlerootTown/scripts.pory"
# 420 "data/maps/LittlerootTown/scripts.pory"
	end
# 421 "data/maps/LittlerootTown/scripts.pory"
# 235 "data/maps/LittlerootTown/scripts.pory"
# 422 "data/maps/LittlerootTown/scripts.pory"

# 423 "data/maps/LittlerootTown/scripts.pory"
# 236 "data/maps/LittlerootTown/scripts.pory"
# 424 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeMale::
# 425 "data/maps/LittlerootTown/scripts.pory"
	end
# 426 "data/maps/LittlerootTown/scripts.pory"
# 240 "data/maps/LittlerootTown/scripts.pory"
# 427 "data/maps/LittlerootTown/scripts.pory"

# 428 "data/maps/LittlerootTown/scripts.pory"
# 241 "data/maps/LittlerootTown/scripts.pory"
# 429 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeFemale::
# 430 "data/maps/LittlerootTown/scripts.pory"
	end
# 431 "data/maps/LittlerootTown/scripts.pory"
# 245 "data/maps/LittlerootTown/scripts.pory"
# 432 "data/maps/LittlerootTown/scripts.pory"

# 433 "data/maps/LittlerootTown/scripts.pory"
# 246 "data/maps/LittlerootTown/scripts.pory"
# 434 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_FatMan::
# 435 "data/maps/LittlerootTown/scripts.pory"
# 247 "data/maps/LittlerootTown/scripts.pory"
# 436 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_CanUsePCToStoreItems, MSGBOX_NPC
# 437 "data/maps/LittlerootTown/scripts.pory"
# 248 "data/maps/LittlerootTown/scripts.pory"
# 438 "data/maps/LittlerootTown/scripts.pory"
	end
# 439 "data/maps/LittlerootTown/scripts.pory"
# 249 "data/maps/LittlerootTown/scripts.pory"
# 440 "data/maps/LittlerootTown/scripts.pory"

# 441 "data/maps/LittlerootTown/scripts.pory"
# 250 "data/maps/LittlerootTown/scripts.pory"
# 442 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_Boy::
# 443 "data/maps/LittlerootTown/scripts.pory"
# 251 "data/maps/LittlerootTown/scripts.pory"
# 444 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_BirchSpendsDaysInLab, MSGBOX_NPC
# 445 "data/maps/LittlerootTown/scripts.pory"
# 252 "data/maps/LittlerootTown/scripts.pory"
# 446 "data/maps/LittlerootTown/scripts.pory"
	end
# 447 "data/maps/LittlerootTown/scripts.pory"
# 253 "data/maps/LittlerootTown/scripts.pory"
# 448 "data/maps/LittlerootTown/scripts.pory"

# 449 "data/maps/LittlerootTown/scripts.pory"
# 254 "data/maps/LittlerootTown/scripts.pory"
# 450 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_Twin::
# 451 "data/maps/LittlerootTown/scripts.pory"
# 255 "data/maps/LittlerootTown/scripts.pory"
# 452 "data/maps/LittlerootTown/scripts.pory"
	lock
# 453 "data/maps/LittlerootTown/scripts.pory"
# 256 "data/maps/LittlerootTown/scripts.pory"
# 454 "data/maps/LittlerootTown/scripts.pory"
	faceplayer
# 455 "data/maps/LittlerootTown/scripts.pory"
# 257 "data/maps/LittlerootTown/scripts.pory"
# 456 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set FLAG_ADVENTURE_STARTED, LittlerootTown_EventScript_GoodLuck
# 457 "data/maps/LittlerootTown/scripts.pory"
# 258 "data/maps/LittlerootTown/scripts.pory"
# 458 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set FLAG_RESCUED_BIRCH, LittlerootTown_EventScript_YouSavedBirch
# 459 "data/maps/LittlerootTown/scripts.pory"
# 259 "data/maps/LittlerootTown/scripts.pory"
# 460 "data/maps/LittlerootTown/scripts.pory"
	goto_if_ne VAR_LITTLEROOT_TOWN_STATE, 0, LittlerootTown_EventScript_GoSaveBirch
# 461 "data/maps/LittlerootTown/scripts.pory"
# 260 "data/maps/LittlerootTown/scripts.pory"
# 462 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut, MSGBOX_DEFAULT
# 463 "data/maps/LittlerootTown/scripts.pory"
# 261 "data/maps/LittlerootTown/scripts.pory"
# 464 "data/maps/LittlerootTown/scripts.pory"
	release
# 465 "data/maps/LittlerootTown/scripts.pory"
# 262 "data/maps/LittlerootTown/scripts.pory"
# 466 "data/maps/LittlerootTown/scripts.pory"
	end
# 467 "data/maps/LittlerootTown/scripts.pory"
# 263 "data/maps/LittlerootTown/scripts.pory"
# 468 "data/maps/LittlerootTown/scripts.pory"

# 469 "data/maps/LittlerootTown/scripts.pory"
# 264 "data/maps/LittlerootTown/scripts.pory"
# 470 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoSaveBirch::
# 471 "data/maps/LittlerootTown/scripts.pory"
# 265 "data/maps/LittlerootTown/scripts.pory"
# 472 "data/maps/LittlerootTown/scripts.pory"
	special GetPlayerBigGuyGirlString
# 473 "data/maps/LittlerootTown/scripts.pory"
# 266 "data/maps/LittlerootTown/scripts.pory"
# 474 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_CanYouGoSeeWhatsHappening, MSGBOX_DEFAULT
# 475 "data/maps/LittlerootTown/scripts.pory"
# 267 "data/maps/LittlerootTown/scripts.pory"
# 476 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 477 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 478 "data/maps/LittlerootTown/scripts.pory"
# 270 "data/maps/LittlerootTown/scripts.pory"
# 479 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_TOWN_STATE, 2
# 480 "data/maps/LittlerootTown/scripts.pory"
# 271 "data/maps/LittlerootTown/scripts.pory"
# 481 "data/maps/LittlerootTown/scripts.pory"
	release
# 482 "data/maps/LittlerootTown/scripts.pory"
# 272 "data/maps/LittlerootTown/scripts.pory"
# 483 "data/maps/LittlerootTown/scripts.pory"
	end
# 484 "data/maps/LittlerootTown/scripts.pory"
# 273 "data/maps/LittlerootTown/scripts.pory"
# 485 "data/maps/LittlerootTown/scripts.pory"

# 486 "data/maps/LittlerootTown/scripts.pory"
# 274 "data/maps/LittlerootTown/scripts.pory"
# 487 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_YouSavedBirch::
# 488 "data/maps/LittlerootTown/scripts.pory"
# 275 "data/maps/LittlerootTown/scripts.pory"
# 489 "data/maps/LittlerootTown/scripts.pory"
	special GetPlayerBigGuyGirlString
# 490 "data/maps/LittlerootTown/scripts.pory"
# 276 "data/maps/LittlerootTown/scripts.pory"
# 491 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_YouSavedBirch, MSGBOX_DEFAULT
# 492 "data/maps/LittlerootTown/scripts.pory"
# 277 "data/maps/LittlerootTown/scripts.pory"
# 493 "data/maps/LittlerootTown/scripts.pory"
	release
# 494 "data/maps/LittlerootTown/scripts.pory"
# 278 "data/maps/LittlerootTown/scripts.pory"
# 495 "data/maps/LittlerootTown/scripts.pory"
	end
# 496 "data/maps/LittlerootTown/scripts.pory"
# 279 "data/maps/LittlerootTown/scripts.pory"
# 497 "data/maps/LittlerootTown/scripts.pory"

# 498 "data/maps/LittlerootTown/scripts.pory"
# 280 "data/maps/LittlerootTown/scripts.pory"
# 499 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoodLuck::
# 500 "data/maps/LittlerootTown/scripts.pory"
# 281 "data/maps/LittlerootTown/scripts.pory"
# 501 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_GoodLuckCatchingPokemon, MSGBOX_DEFAULT
# 502 "data/maps/LittlerootTown/scripts.pory"
# 282 "data/maps/LittlerootTown/scripts.pory"
# 503 "data/maps/LittlerootTown/scripts.pory"
	release
# 504 "data/maps/LittlerootTown/scripts.pory"
# 283 "data/maps/LittlerootTown/scripts.pory"
# 505 "data/maps/LittlerootTown/scripts.pory"
	end
# 506 "data/maps/LittlerootTown/scripts.pory"
# 284 "data/maps/LittlerootTown/scripts.pory"
# 507 "data/maps/LittlerootTown/scripts.pory"

# 508 "data/maps/LittlerootTown/scripts.pory"
# 285 "data/maps/LittlerootTown/scripts.pory"
# 509 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_NeedPokemonTriggerLeft::
# 510 "data/maps/LittlerootTown/scripts.pory"
# 286 "data/maps/LittlerootTown/scripts.pory"
# 511 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 512 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 513 "data/maps/LittlerootTown/scripts.pory"
# 289 "data/maps/LittlerootTown/scripts.pory"
# 514 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_DangerousWithoutPokemon
# 515 "data/maps/LittlerootTown/scripts.pory"
# 290 "data/maps/LittlerootTown/scripts.pory"
# 516 "data/maps/LittlerootTown/scripts.pory"
# 291 "data/maps/LittlerootTown/scripts.pory"
# 517 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 518 "data/maps/LittlerootTown/scripts.pory"
# 292 "data/maps/LittlerootTown/scripts.pory"
# 519 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 520 "data/maps/LittlerootTown/scripts.pory"
# 293 "data/maps/LittlerootTown/scripts.pory"
# 521 "data/maps/LittlerootTown/scripts.pory"
	end
# 522 "data/maps/LittlerootTown/scripts.pory"
# 294 "data/maps/LittlerootTown/scripts.pory"
# 523 "data/maps/LittlerootTown/scripts.pory"

# 524 "data/maps/LittlerootTown/scripts.pory"
# 295 "data/maps/LittlerootTown/scripts.pory"
# 525 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_DangerousWithoutPokemon::
# 526 "data/maps/LittlerootTown/scripts.pory"
# 296 "data/maps/LittlerootTown/scripts.pory"
# 527 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut, MSGBOX_DEFAULT
# 528 "data/maps/LittlerootTown/scripts.pory"
# 297 "data/maps/LittlerootTown/scripts.pory"
# 529 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 530 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, LittlerootTown_Movement_PushPlayerBackFromRoute
# 531 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 532 "data/maps/LittlerootTown/scripts.pory"
# 301 "data/maps/LittlerootTown/scripts.pory"
# 533 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_DangerousIfYouDontHavePokemon, MSGBOX_DEFAULT
# 534 "data/maps/LittlerootTown/scripts.pory"
# 302 "data/maps/LittlerootTown/scripts.pory"
# 535 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 536 "data/maps/LittlerootTown/scripts.pory"
# 303 "data/maps/LittlerootTown/scripts.pory"
# 537 "data/maps/LittlerootTown/scripts.pory"
	return
# 538 "data/maps/LittlerootTown/scripts.pory"
# 304 "data/maps/LittlerootTown/scripts.pory"
# 539 "data/maps/LittlerootTown/scripts.pory"

# 540 "data/maps/LittlerootTown/scripts.pory"
# 305 "data/maps/LittlerootTown/scripts.pory"
# 541 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinApproachPlayerLeft:
# 542 "data/maps/LittlerootTown/scripts.pory"
# 306 "data/maps/LittlerootTown/scripts.pory"
# 543 "data/maps/LittlerootTown/scripts.pory"
	face_right
# 544 "data/maps/LittlerootTown/scripts.pory"
# 307 "data/maps/LittlerootTown/scripts.pory"
# 545 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 546 "data/maps/LittlerootTown/scripts.pory"
# 308 "data/maps/LittlerootTown/scripts.pory"
# 547 "data/maps/LittlerootTown/scripts.pory"
	disable_jump_landing_ground_effect
# 548 "data/maps/LittlerootTown/scripts.pory"
# 309 "data/maps/LittlerootTown/scripts.pory"
# 549 "data/maps/LittlerootTown/scripts.pory"
	jump_in_place_right
# 550 "data/maps/LittlerootTown/scripts.pory"
# 310 "data/maps/LittlerootTown/scripts.pory"
# 551 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 552 "data/maps/LittlerootTown/scripts.pory"
# 311 "data/maps/LittlerootTown/scripts.pory"
# 553 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 554 "data/maps/LittlerootTown/scripts.pory"
# 312 "data/maps/LittlerootTown/scripts.pory"
# 555 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 556 "data/maps/LittlerootTown/scripts.pory"
# 313 "data/maps/LittlerootTown/scripts.pory"
# 557 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 558 "data/maps/LittlerootTown/scripts.pory"
# 314 "data/maps/LittlerootTown/scripts.pory"
# 559 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 560 "data/maps/LittlerootTown/scripts.pory"
# 315 "data/maps/LittlerootTown/scripts.pory"
# 561 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 562 "data/maps/LittlerootTown/scripts.pory"
# 316 "data/maps/LittlerootTown/scripts.pory"
# 563 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 564 "data/maps/LittlerootTown/scripts.pory"
# 317 "data/maps/LittlerootTown/scripts.pory"
# 565 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_left
# 566 "data/maps/LittlerootTown/scripts.pory"
# 318 "data/maps/LittlerootTown/scripts.pory"
# 567 "data/maps/LittlerootTown/scripts.pory"
	face_down
# 568 "data/maps/LittlerootTown/scripts.pory"
# 319 "data/maps/LittlerootTown/scripts.pory"
# 569 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 570 "data/maps/LittlerootTown/scripts.pory"
# 320 "data/maps/LittlerootTown/scripts.pory"
# 571 "data/maps/LittlerootTown/scripts.pory"

# 572 "data/maps/LittlerootTown/scripts.pory"
# 321 "data/maps/LittlerootTown/scripts.pory"
# 573 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinPushPlayerFromRoute:
# 574 "data/maps/LittlerootTown/scripts.pory"
# 322 "data/maps/LittlerootTown/scripts.pory"
# 575 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 576 "data/maps/LittlerootTown/scripts.pory"
# 323 "data/maps/LittlerootTown/scripts.pory"
# 577 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 578 "data/maps/LittlerootTown/scripts.pory"
# 324 "data/maps/LittlerootTown/scripts.pory"
# 579 "data/maps/LittlerootTown/scripts.pory"

# 580 "data/maps/LittlerootTown/scripts.pory"
# 325 "data/maps/LittlerootTown/scripts.pory"
# 581 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinReturnLeft:
# 582 "data/maps/LittlerootTown/scripts.pory"
# 326 "data/maps/LittlerootTown/scripts.pory"
# 583 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 584 "data/maps/LittlerootTown/scripts.pory"
# 327 "data/maps/LittlerootTown/scripts.pory"
# 585 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 586 "data/maps/LittlerootTown/scripts.pory"
# 328 "data/maps/LittlerootTown/scripts.pory"
# 587 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 588 "data/maps/LittlerootTown/scripts.pory"
# 329 "data/maps/LittlerootTown/scripts.pory"
# 589 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 590 "data/maps/LittlerootTown/scripts.pory"
# 330 "data/maps/LittlerootTown/scripts.pory"
# 591 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 592 "data/maps/LittlerootTown/scripts.pory"
# 331 "data/maps/LittlerootTown/scripts.pory"
# 593 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 594 "data/maps/LittlerootTown/scripts.pory"
# 332 "data/maps/LittlerootTown/scripts.pory"
# 595 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 596 "data/maps/LittlerootTown/scripts.pory"
# 333 "data/maps/LittlerootTown/scripts.pory"
# 597 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 598 "data/maps/LittlerootTown/scripts.pory"
# 334 "data/maps/LittlerootTown/scripts.pory"
# 599 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_down
# 600 "data/maps/LittlerootTown/scripts.pory"
# 335 "data/maps/LittlerootTown/scripts.pory"
# 601 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 602 "data/maps/LittlerootTown/scripts.pory"
# 336 "data/maps/LittlerootTown/scripts.pory"
# 603 "data/maps/LittlerootTown/scripts.pory"

# 604 "data/maps/LittlerootTown/scripts.pory"
# 337 "data/maps/LittlerootTown/scripts.pory"
# 605 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PushPlayerBackFromRoute:
# 606 "data/maps/LittlerootTown/scripts.pory"
# 338 "data/maps/LittlerootTown/scripts.pory"
# 607 "data/maps/LittlerootTown/scripts.pory"
	lock_facing_direction
# 608 "data/maps/LittlerootTown/scripts.pory"
# 339 "data/maps/LittlerootTown/scripts.pory"
# 609 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 610 "data/maps/LittlerootTown/scripts.pory"
# 340 "data/maps/LittlerootTown/scripts.pory"
# 611 "data/maps/LittlerootTown/scripts.pory"
	unlock_facing_direction
# 612 "data/maps/LittlerootTown/scripts.pory"
# 341 "data/maps/LittlerootTown/scripts.pory"
# 613 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 614 "data/maps/LittlerootTown/scripts.pory"
# 342 "data/maps/LittlerootTown/scripts.pory"
# 615 "data/maps/LittlerootTown/scripts.pory"

# 616 "data/maps/LittlerootTown/scripts.pory"
# 343 "data/maps/LittlerootTown/scripts.pory"
# 617 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_NeedPokemonTriggerRight::
# 618 "data/maps/LittlerootTown/scripts.pory"
# 344 "data/maps/LittlerootTown/scripts.pory"
# 619 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 620 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 621 "data/maps/LittlerootTown/scripts.pory"
# 347 "data/maps/LittlerootTown/scripts.pory"
# 622 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_DangerousWithoutPokemon
# 623 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 624 "data/maps/LittlerootTown/scripts.pory"
# 350 "data/maps/LittlerootTown/scripts.pory"
# 625 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 626 "data/maps/LittlerootTown/scripts.pory"
# 351 "data/maps/LittlerootTown/scripts.pory"
# 627 "data/maps/LittlerootTown/scripts.pory"
	end
# 628 "data/maps/LittlerootTown/scripts.pory"
# 352 "data/maps/LittlerootTown/scripts.pory"
# 629 "data/maps/LittlerootTown/scripts.pory"

# 630 "data/maps/LittlerootTown/scripts.pory"
# 353 "data/maps/LittlerootTown/scripts.pory"
# 631 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinApproachPlayerRight:
# 632 "data/maps/LittlerootTown/scripts.pory"
# 354 "data/maps/LittlerootTown/scripts.pory"
# 633 "data/maps/LittlerootTown/scripts.pory"
	face_right
# 634 "data/maps/LittlerootTown/scripts.pory"
# 355 "data/maps/LittlerootTown/scripts.pory"
# 635 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 636 "data/maps/LittlerootTown/scripts.pory"
# 356 "data/maps/LittlerootTown/scripts.pory"
# 637 "data/maps/LittlerootTown/scripts.pory"
	disable_jump_landing_ground_effect
# 638 "data/maps/LittlerootTown/scripts.pory"
# 357 "data/maps/LittlerootTown/scripts.pory"
# 639 "data/maps/LittlerootTown/scripts.pory"
	jump_in_place_right
# 640 "data/maps/LittlerootTown/scripts.pory"
# 358 "data/maps/LittlerootTown/scripts.pory"
# 641 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 642 "data/maps/LittlerootTown/scripts.pory"
# 359 "data/maps/LittlerootTown/scripts.pory"
# 643 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 644 "data/maps/LittlerootTown/scripts.pory"
# 360 "data/maps/LittlerootTown/scripts.pory"
# 645 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 646 "data/maps/LittlerootTown/scripts.pory"
# 361 "data/maps/LittlerootTown/scripts.pory"
# 647 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 648 "data/maps/LittlerootTown/scripts.pory"
# 362 "data/maps/LittlerootTown/scripts.pory"
# 649 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 650 "data/maps/LittlerootTown/scripts.pory"
# 363 "data/maps/LittlerootTown/scripts.pory"
# 651 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 652 "data/maps/LittlerootTown/scripts.pory"
# 364 "data/maps/LittlerootTown/scripts.pory"
# 653 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 654 "data/maps/LittlerootTown/scripts.pory"
# 365 "data/maps/LittlerootTown/scripts.pory"
# 655 "data/maps/LittlerootTown/scripts.pory"
	face_down
# 656 "data/maps/LittlerootTown/scripts.pory"
# 366 "data/maps/LittlerootTown/scripts.pory"
# 657 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 658 "data/maps/LittlerootTown/scripts.pory"
# 367 "data/maps/LittlerootTown/scripts.pory"
# 659 "data/maps/LittlerootTown/scripts.pory"

# 660 "data/maps/LittlerootTown/scripts.pory"
# 368 "data/maps/LittlerootTown/scripts.pory"
# 661 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinReturnRight:
# 662 "data/maps/LittlerootTown/scripts.pory"
# 369 "data/maps/LittlerootTown/scripts.pory"
# 663 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 664 "data/maps/LittlerootTown/scripts.pory"
# 370 "data/maps/LittlerootTown/scripts.pory"
# 665 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 666 "data/maps/LittlerootTown/scripts.pory"
# 371 "data/maps/LittlerootTown/scripts.pory"
# 667 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 668 "data/maps/LittlerootTown/scripts.pory"
# 372 "data/maps/LittlerootTown/scripts.pory"
# 669 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 670 "data/maps/LittlerootTown/scripts.pory"
# 373 "data/maps/LittlerootTown/scripts.pory"
# 671 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 672 "data/maps/LittlerootTown/scripts.pory"
# 374 "data/maps/LittlerootTown/scripts.pory"
# 673 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_down
# 674 "data/maps/LittlerootTown/scripts.pory"
# 375 "data/maps/LittlerootTown/scripts.pory"
# 675 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 676 "data/maps/LittlerootTown/scripts.pory"
# 376 "data/maps/LittlerootTown/scripts.pory"
# 677 "data/maps/LittlerootTown/scripts.pory"

# 678 "data/maps/LittlerootTown/scripts.pory"
# 377 "data/maps/LittlerootTown/scripts.pory"
# 679 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoSaveBirchTrigger::
# 680 "data/maps/LittlerootTown/scripts.pory"
# 378 "data/maps/LittlerootTown/scripts.pory"
# 681 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 682 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 683 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 684 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 685 "data/maps/LittlerootTown/scripts.pory"
# 383 "data/maps/LittlerootTown/scripts.pory"
# 686 "data/maps/LittlerootTown/scripts.pory"
	special GetPlayerBigGuyGirlString
# 687 "data/maps/LittlerootTown/scripts.pory"
# 384 "data/maps/LittlerootTown/scripts.pory"
# 688 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_CanYouGoSeeWhatsHappening, MSGBOX_DEFAULT
# 689 "data/maps/LittlerootTown/scripts.pory"
# 385 "data/maps/LittlerootTown/scripts.pory"
# 690 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 691 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 692 "data/maps/LittlerootTown/scripts.pory"
# 388 "data/maps/LittlerootTown/scripts.pory"
# 693 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_TOWN_STATE, 2
# 694 "data/maps/LittlerootTown/scripts.pory"
# 389 "data/maps/LittlerootTown/scripts.pory"
# 695 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 696 "data/maps/LittlerootTown/scripts.pory"
# 390 "data/maps/LittlerootTown/scripts.pory"
# 697 "data/maps/LittlerootTown/scripts.pory"
	end
# 698 "data/maps/LittlerootTown/scripts.pory"
# 391 "data/maps/LittlerootTown/scripts.pory"
# 699 "data/maps/LittlerootTown/scripts.pory"

# 700 "data/maps/LittlerootTown/scripts.pory"
# 392 "data/maps/LittlerootTown/scripts.pory"
# 701 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_TownSign::
# 702 "data/maps/LittlerootTown/scripts.pory"
# 393 "data/maps/LittlerootTown/scripts.pory"
# 703 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_TownSign, MSGBOX_SIGN
# 704 "data/maps/LittlerootTown/scripts.pory"
# 394 "data/maps/LittlerootTown/scripts.pory"
# 705 "data/maps/LittlerootTown/scripts.pory"
	end
# 706 "data/maps/LittlerootTown/scripts.pory"
# 395 "data/maps/LittlerootTown/scripts.pory"
# 707 "data/maps/LittlerootTown/scripts.pory"

# 708 "data/maps/LittlerootTown/scripts.pory"
# 396 "data/maps/LittlerootTown/scripts.pory"
# 709 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BirchsLabSign::
# 710 "data/maps/LittlerootTown/scripts.pory"
# 397 "data/maps/LittlerootTown/scripts.pory"
# 711 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ProfBirchsLab, MSGBOX_SIGN
# 712 "data/maps/LittlerootTown/scripts.pory"
# 398 "data/maps/LittlerootTown/scripts.pory"
# 713 "data/maps/LittlerootTown/scripts.pory"
	end
# 714 "data/maps/LittlerootTown/scripts.pory"
# 399 "data/maps/LittlerootTown/scripts.pory"
# 715 "data/maps/LittlerootTown/scripts.pory"

# 716 "data/maps/LittlerootTown/scripts.pory"
# 400 "data/maps/LittlerootTown/scripts.pory"
# 717 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BrendansHouseSign::
# 718 "data/maps/LittlerootTown/scripts.pory"
# 401 "data/maps/LittlerootTown/scripts.pory"
# 719 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 720 "data/maps/LittlerootTown/scripts.pory"
# 402 "data/maps/LittlerootTown/scripts.pory"
# 721 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 722 "data/maps/LittlerootTown/scripts.pory"
# 403 "data/maps/LittlerootTown/scripts.pory"
# 723 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_PlayersHouseSignMale
# 724 "data/maps/LittlerootTown/scripts.pory"
# 404 "data/maps/LittlerootTown/scripts.pory"
# 725 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_BirchsHouseSignFemale
# 726 "data/maps/LittlerootTown/scripts.pory"
# 405 "data/maps/LittlerootTown/scripts.pory"
# 727 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 728 "data/maps/LittlerootTown/scripts.pory"
# 406 "data/maps/LittlerootTown/scripts.pory"
# 729 "data/maps/LittlerootTown/scripts.pory"
	end
# 730 "data/maps/LittlerootTown/scripts.pory"
# 407 "data/maps/LittlerootTown/scripts.pory"
# 731 "data/maps/LittlerootTown/scripts.pory"

# 732 "data/maps/LittlerootTown/scripts.pory"
# 408 "data/maps/LittlerootTown/scripts.pory"
# 733 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_PlayersHouseSignMale::
# 734 "data/maps/LittlerootTown/scripts.pory"
# 409 "data/maps/LittlerootTown/scripts.pory"
# 735 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_PlayersHouse, MSGBOX_DEFAULT
# 736 "data/maps/LittlerootTown/scripts.pory"
# 410 "data/maps/LittlerootTown/scripts.pory"
# 737 "data/maps/LittlerootTown/scripts.pory"
	return
# 738 "data/maps/LittlerootTown/scripts.pory"
# 411 "data/maps/LittlerootTown/scripts.pory"
# 739 "data/maps/LittlerootTown/scripts.pory"

# 740 "data/maps/LittlerootTown/scripts.pory"
# 412 "data/maps/LittlerootTown/scripts.pory"
# 741 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BirchsHouseSignFemale::
# 742 "data/maps/LittlerootTown/scripts.pory"
# 413 "data/maps/LittlerootTown/scripts.pory"
# 743 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ProfBirchsHouse, MSGBOX_DEFAULT
# 744 "data/maps/LittlerootTown/scripts.pory"
# 414 "data/maps/LittlerootTown/scripts.pory"
# 745 "data/maps/LittlerootTown/scripts.pory"
	return
# 746 "data/maps/LittlerootTown/scripts.pory"
# 415 "data/maps/LittlerootTown/scripts.pory"
# 747 "data/maps/LittlerootTown/scripts.pory"

# 748 "data/maps/LittlerootTown/scripts.pory"
# 416 "data/maps/LittlerootTown/scripts.pory"
# 749 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MaysHouseSign::
# 750 "data/maps/LittlerootTown/scripts.pory"
# 417 "data/maps/LittlerootTown/scripts.pory"
# 751 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 752 "data/maps/LittlerootTown/scripts.pory"
# 418 "data/maps/LittlerootTown/scripts.pory"
# 753 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 754 "data/maps/LittlerootTown/scripts.pory"
# 419 "data/maps/LittlerootTown/scripts.pory"
# 755 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_BirchsHouseSignMale
# 756 "data/maps/LittlerootTown/scripts.pory"
# 420 "data/maps/LittlerootTown/scripts.pory"
# 757 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_PlayersHouseSignFemale
# 758 "data/maps/LittlerootTown/scripts.pory"
# 421 "data/maps/LittlerootTown/scripts.pory"
# 759 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 760 "data/maps/LittlerootTown/scripts.pory"
# 422 "data/maps/LittlerootTown/scripts.pory"
# 761 "data/maps/LittlerootTown/scripts.pory"
	end
# 762 "data/maps/LittlerootTown/scripts.pory"
# 423 "data/maps/LittlerootTown/scripts.pory"
# 763 "data/maps/LittlerootTown/scripts.pory"

# 764 "data/maps/LittlerootTown/scripts.pory"
# 424 "data/maps/LittlerootTown/scripts.pory"
# 765 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BirchsHouseSignMale::
# 766 "data/maps/LittlerootTown/scripts.pory"
# 425 "data/maps/LittlerootTown/scripts.pory"
# 767 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ProfBirchsHouse, MSGBOX_DEFAULT
# 768 "data/maps/LittlerootTown/scripts.pory"
# 426 "data/maps/LittlerootTown/scripts.pory"
# 769 "data/maps/LittlerootTown/scripts.pory"
	return
# 770 "data/maps/LittlerootTown/scripts.pory"
# 427 "data/maps/LittlerootTown/scripts.pory"
# 771 "data/maps/LittlerootTown/scripts.pory"

# 772 "data/maps/LittlerootTown/scripts.pory"
# 428 "data/maps/LittlerootTown/scripts.pory"
# 773 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_PlayersHouseSignFemale::
# 774 "data/maps/LittlerootTown/scripts.pory"
# 429 "data/maps/LittlerootTown/scripts.pory"
# 775 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_PlayersHouse, MSGBOX_DEFAULT
# 776 "data/maps/LittlerootTown/scripts.pory"
# 430 "data/maps/LittlerootTown/scripts.pory"
# 777 "data/maps/LittlerootTown/scripts.pory"
	return
# 778 "data/maps/LittlerootTown/scripts.pory"
# 431 "data/maps/LittlerootTown/scripts.pory"
# 779 "data/maps/LittlerootTown/scripts.pory"

# 780 "data/maps/LittlerootTown/scripts.pory"
# 432 "data/maps/LittlerootTown/scripts.pory"
# 781 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger0::
# 782 "data/maps/LittlerootTown/scripts.pory"
# 433 "data/maps/LittlerootTown/scripts.pory"
# 783 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 784 "data/maps/LittlerootTown/scripts.pory"
# 434 "data/maps/LittlerootTown/scripts.pory"
# 785 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 0
# 786 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 787 "data/maps/LittlerootTown/scripts.pory"
# 437 "data/maps/LittlerootTown/scripts.pory"
# 788 "data/maps/LittlerootTown/scripts.pory"
	end
# 789 "data/maps/LittlerootTown/scripts.pory"
# 438 "data/maps/LittlerootTown/scripts.pory"
# 790 "data/maps/LittlerootTown/scripts.pory"

# 791 "data/maps/LittlerootTown/scripts.pory"
# 439 "data/maps/LittlerootTown/scripts.pory"
# 792 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger1::
# 793 "data/maps/LittlerootTown/scripts.pory"
# 440 "data/maps/LittlerootTown/scripts.pory"
# 794 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 795 "data/maps/LittlerootTown/scripts.pory"
# 441 "data/maps/LittlerootTown/scripts.pory"
# 796 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 1
# 797 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 798 "data/maps/LittlerootTown/scripts.pory"
# 444 "data/maps/LittlerootTown/scripts.pory"
# 799 "data/maps/LittlerootTown/scripts.pory"
	end
# 800 "data/maps/LittlerootTown/scripts.pory"
# 445 "data/maps/LittlerootTown/scripts.pory"
# 801 "data/maps/LittlerootTown/scripts.pory"

# 802 "data/maps/LittlerootTown/scripts.pory"
# 446 "data/maps/LittlerootTown/scripts.pory"
# 803 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger2::
# 804 "data/maps/LittlerootTown/scripts.pory"
# 447 "data/maps/LittlerootTown/scripts.pory"
# 805 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 806 "data/maps/LittlerootTown/scripts.pory"
# 448 "data/maps/LittlerootTown/scripts.pory"
# 807 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 2
# 808 "data/maps/LittlerootTown/scripts.pory"
# 449 "data/maps/LittlerootTown/scripts.pory"
# 809 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 810 "data/maps/LittlerootTown/scripts.pory"
# 450 "data/maps/LittlerootTown/scripts.pory"
# 811 "data/maps/LittlerootTown/scripts.pory"
	end
# 812 "data/maps/LittlerootTown/scripts.pory"
# 451 "data/maps/LittlerootTown/scripts.pory"
# 813 "data/maps/LittlerootTown/scripts.pory"

# 814 "data/maps/LittlerootTown/scripts.pory"
# 452 "data/maps/LittlerootTown/scripts.pory"
# 815 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger3::
# 816 "data/maps/LittlerootTown/scripts.pory"
# 453 "data/maps/LittlerootTown/scripts.pory"
# 817 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 818 "data/maps/LittlerootTown/scripts.pory"
# 454 "data/maps/LittlerootTown/scripts.pory"
# 819 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 3
# 820 "data/maps/LittlerootTown/scripts.pory"
# 455 "data/maps/LittlerootTown/scripts.pory"
# 821 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 822 "data/maps/LittlerootTown/scripts.pory"
# 456 "data/maps/LittlerootTown/scripts.pory"
# 823 "data/maps/LittlerootTown/scripts.pory"
	end
# 824 "data/maps/LittlerootTown/scripts.pory"
# 457 "data/maps/LittlerootTown/scripts.pory"
# 825 "data/maps/LittlerootTown/scripts.pory"

# 826 "data/maps/LittlerootTown/scripts.pory"
# 458 "data/maps/LittlerootTown/scripts.pory"
# 827 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger4::
# 828 "data/maps/LittlerootTown/scripts.pory"
# 459 "data/maps/LittlerootTown/scripts.pory"
# 829 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 830 "data/maps/LittlerootTown/scripts.pory"
# 460 "data/maps/LittlerootTown/scripts.pory"
# 831 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 4
# 832 "data/maps/LittlerootTown/scripts.pory"
# 461 "data/maps/LittlerootTown/scripts.pory"
# 833 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 834 "data/maps/LittlerootTown/scripts.pory"
# 462 "data/maps/LittlerootTown/scripts.pory"
# 835 "data/maps/LittlerootTown/scripts.pory"
	end
# 836 "data/maps/LittlerootTown/scripts.pory"
# 463 "data/maps/LittlerootTown/scripts.pory"
# 837 "data/maps/LittlerootTown/scripts.pory"

# 838 "data/maps/LittlerootTown/scripts.pory"
# 464 "data/maps/LittlerootTown/scripts.pory"
# 839 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger5::
# 840 "data/maps/LittlerootTown/scripts.pory"
# 465 "data/maps/LittlerootTown/scripts.pory"
# 841 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 842 "data/maps/LittlerootTown/scripts.pory"
# 466 "data/maps/LittlerootTown/scripts.pory"
# 843 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 5
# 844 "data/maps/LittlerootTown/scripts.pory"
# 467 "data/maps/LittlerootTown/scripts.pory"
# 845 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 846 "data/maps/LittlerootTown/scripts.pory"
# 468 "data/maps/LittlerootTown/scripts.pory"
# 847 "data/maps/LittlerootTown/scripts.pory"
	end
# 848 "data/maps/LittlerootTown/scripts.pory"
# 469 "data/maps/LittlerootTown/scripts.pory"
# 849 "data/maps/LittlerootTown/scripts.pory"

# 850 "data/maps/LittlerootTown/scripts.pory"
# 470 "data/maps/LittlerootTown/scripts.pory"
# 851 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger::
# 852 "data/maps/LittlerootTown/scripts.pory"
# 471 "data/maps/LittlerootTown/scripts.pory"
# 853 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 854 "data/maps/LittlerootTown/scripts.pory"
# 472 "data/maps/LittlerootTown/scripts.pory"
# 855 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_MomNoticePlayerMale
# 856 "data/maps/LittlerootTown/scripts.pory"
# 473 "data/maps/LittlerootTown/scripts.pory"
# 857 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_MomNoticePlayerFemale
# 858 "data/maps/LittlerootTown/scripts.pory"
# 474 "data/maps/LittlerootTown/scripts.pory"
# 859 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 860 "data/maps/LittlerootTown/scripts.pory"
# 475 "data/maps/LittlerootTown/scripts.pory"
# 861 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetHomeDoorCoordsMale
# 862 "data/maps/LittlerootTown/scripts.pory"
# 476 "data/maps/LittlerootTown/scripts.pory"
# 863 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_SetHomeDoorCoordsFemale
# 864 "data/maps/LittlerootTown/scripts.pory"
# 477 "data/maps/LittlerootTown/scripts.pory"
# 865 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_WaitPlayer, MSGBOX_DEFAULT
# 866 "data/maps/LittlerootTown/scripts.pory"
# 478 "data/maps/LittlerootTown/scripts.pory"
# 867 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 868 "data/maps/LittlerootTown/scripts.pory"
# 479 "data/maps/LittlerootTown/scripts.pory"
# 869 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 870 "data/maps/LittlerootTown/scripts.pory"
# 480 "data/maps/LittlerootTown/scripts.pory"
# 871 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_MomApproachPlayerMale
# 872 "data/maps/LittlerootTown/scripts.pory"
# 481 "data/maps/LittlerootTown/scripts.pory"
# 873 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_MomApproachPlayerFemale
# 874 "data/maps/LittlerootTown/scripts.pory"
# 482 "data/maps/LittlerootTown/scripts.pory"
# 875 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GiveRunningShoes
# 876 "data/maps/LittlerootTown/scripts.pory"
# 483 "data/maps/LittlerootTown/scripts.pory"
# 877 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 878 "data/maps/LittlerootTown/scripts.pory"
# 484 "data/maps/LittlerootTown/scripts.pory"
# 879 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_MomReturnHomeMale
# 880 "data/maps/LittlerootTown/scripts.pory"
# 485 "data/maps/LittlerootTown/scripts.pory"
# 881 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_MomReturnHomeFemale
# 882 "data/maps/LittlerootTown/scripts.pory"
# 486 "data/maps/LittlerootTown/scripts.pory"
# 883 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_SetReceivedRunningShoes
# 884 "data/maps/LittlerootTown/scripts.pory"
# 487 "data/maps/LittlerootTown/scripts.pory"
# 885 "data/maps/LittlerootTown/scripts.pory"
	end
# 886 "data/maps/LittlerootTown/scripts.pory"
# 488 "data/maps/LittlerootTown/scripts.pory"
# 887 "data/maps/LittlerootTown/scripts.pory"

# 888 "data/maps/LittlerootTown/scripts.pory"
# 489 "data/maps/LittlerootTown/scripts.pory"
# 889 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetHomeDoorCoordsMale::
# 890 "data/maps/LittlerootTown/scripts.pory"
# 490 "data/maps/LittlerootTown/scripts.pory"
# 891 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8009, 5
# 892 "data/maps/LittlerootTown/scripts.pory"
# 491 "data/maps/LittlerootTown/scripts.pory"
# 893 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x800A, 8
# 894 "data/maps/LittlerootTown/scripts.pory"
# 492 "data/maps/LittlerootTown/scripts.pory"
# 895 "data/maps/LittlerootTown/scripts.pory"
	return
# 896 "data/maps/LittlerootTown/scripts.pory"
# 493 "data/maps/LittlerootTown/scripts.pory"
# 897 "data/maps/LittlerootTown/scripts.pory"

# 898 "data/maps/LittlerootTown/scripts.pory"
# 494 "data/maps/LittlerootTown/scripts.pory"
# 899 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetHomeDoorCoordsFemale::
# 900 "data/maps/LittlerootTown/scripts.pory"
# 495 "data/maps/LittlerootTown/scripts.pory"
# 901 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8009, 14
# 902 "data/maps/LittlerootTown/scripts.pory"
# 496 "data/maps/LittlerootTown/scripts.pory"
# 903 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x800A, 8
# 904 "data/maps/LittlerootTown/scripts.pory"
# 497 "data/maps/LittlerootTown/scripts.pory"
# 905 "data/maps/LittlerootTown/scripts.pory"
	return
# 906 "data/maps/LittlerootTown/scripts.pory"
# 498 "data/maps/LittlerootTown/scripts.pory"
# 907 "data/maps/LittlerootTown/scripts.pory"

# 908 "data/maps/LittlerootTown/scripts.pory"
# 499 "data/maps/LittlerootTown/scripts.pory"
# 909 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomNoticePlayerMale::
# 910 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 911 "data/maps/LittlerootTown/scripts.pory"
# 502 "data/maps/LittlerootTown/scripts.pory"
# 912 "data/maps/LittlerootTown/scripts.pory"
	return
# 913 "data/maps/LittlerootTown/scripts.pory"
# 503 "data/maps/LittlerootTown/scripts.pory"
# 914 "data/maps/LittlerootTown/scripts.pory"

# 915 "data/maps/LittlerootTown/scripts.pory"
# 504 "data/maps/LittlerootTown/scripts.pory"
# 916 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomNoticePlayerFemale::
# 917 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 918 "data/maps/LittlerootTown/scripts.pory"
# 507 "data/maps/LittlerootTown/scripts.pory"
# 919 "data/maps/LittlerootTown/scripts.pory"
	return
# 920 "data/maps/LittlerootTown/scripts.pory"
# 508 "data/maps/LittlerootTown/scripts.pory"
# 921 "data/maps/LittlerootTown/scripts.pory"

# 922 "data/maps/LittlerootTown/scripts.pory"
# 509 "data/maps/LittlerootTown/scripts.pory"
# 923 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale::
# 924 "data/maps/LittlerootTown/scripts.pory"
# 510 "data/maps/LittlerootTown/scripts.pory"
# 925 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomApproachPlayer0
# 926 "data/maps/LittlerootTown/scripts.pory"
# 511 "data/maps/LittlerootTown/scripts.pory"
# 927 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomApproachPlayer1
# 928 "data/maps/LittlerootTown/scripts.pory"
# 512 "data/maps/LittlerootTown/scripts.pory"
# 929 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomApproachPlayerMale2
# 930 "data/maps/LittlerootTown/scripts.pory"
# 513 "data/maps/LittlerootTown/scripts.pory"
# 931 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomApproachPlayerMale3
# 932 "data/maps/LittlerootTown/scripts.pory"
# 514 "data/maps/LittlerootTown/scripts.pory"
# 933 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomApproachPlayerMale4
# 934 "data/maps/LittlerootTown/scripts.pory"
# 515 "data/maps/LittlerootTown/scripts.pory"
# 935 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomApproachPlayerMale5
# 936 "data/maps/LittlerootTown/scripts.pory"
# 516 "data/maps/LittlerootTown/scripts.pory"
# 937 "data/maps/LittlerootTown/scripts.pory"
	return
# 938 "data/maps/LittlerootTown/scripts.pory"
# 517 "data/maps/LittlerootTown/scripts.pory"
# 939 "data/maps/LittlerootTown/scripts.pory"

# 940 "data/maps/LittlerootTown/scripts.pory"
# 518 "data/maps/LittlerootTown/scripts.pory"
# 941 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale::
# 942 "data/maps/LittlerootTown/scripts.pory"
# 519 "data/maps/LittlerootTown/scripts.pory"
# 943 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomApproachPlayer0
# 944 "data/maps/LittlerootTown/scripts.pory"
# 520 "data/maps/LittlerootTown/scripts.pory"
# 945 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomApproachPlayer1
# 946 "data/maps/LittlerootTown/scripts.pory"
# 521 "data/maps/LittlerootTown/scripts.pory"
# 947 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomApproachPlayerFemale2
# 948 "data/maps/LittlerootTown/scripts.pory"
# 522 "data/maps/LittlerootTown/scripts.pory"
# 949 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomApproachPlayerFemale3
# 950 "data/maps/LittlerootTown/scripts.pory"
# 523 "data/maps/LittlerootTown/scripts.pory"
# 951 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomApproachPlayerFemale4
# 952 "data/maps/LittlerootTown/scripts.pory"
# 524 "data/maps/LittlerootTown/scripts.pory"
# 953 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomApproachPlayerFemale5
# 954 "data/maps/LittlerootTown/scripts.pory"
# 525 "data/maps/LittlerootTown/scripts.pory"
# 955 "data/maps/LittlerootTown/scripts.pory"
	return
# 956 "data/maps/LittlerootTown/scripts.pory"
# 526 "data/maps/LittlerootTown/scripts.pory"
# 957 "data/maps/LittlerootTown/scripts.pory"

# 958 "data/maps/LittlerootTown/scripts.pory"
# 527 "data/maps/LittlerootTown/scripts.pory"
# 959 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayer0::
# 960 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterDown
# 961 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 962 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 963 "data/maps/LittlerootTown/scripts.pory"
# 532 "data/maps/LittlerootTown/scripts.pory"
# 964 "data/maps/LittlerootTown/scripts.pory"
	return
# 965 "data/maps/LittlerootTown/scripts.pory"
# 533 "data/maps/LittlerootTown/scripts.pory"
# 966 "data/maps/LittlerootTown/scripts.pory"

# 967 "data/maps/LittlerootTown/scripts.pory"
# 534 "data/maps/LittlerootTown/scripts.pory"
# 968 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayer1::
# 969 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterDown
# 970 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 971 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 972 "data/maps/LittlerootTown/scripts.pory"
# 539 "data/maps/LittlerootTown/scripts.pory"
# 973 "data/maps/LittlerootTown/scripts.pory"
	return
# 974 "data/maps/LittlerootTown/scripts.pory"
# 540 "data/maps/LittlerootTown/scripts.pory"
# 975 "data/maps/LittlerootTown/scripts.pory"

# 976 "data/maps/LittlerootTown/scripts.pory"
# 541 "data/maps/LittlerootTown/scripts.pory"
# 977 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale2::
# 978 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 979 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 980 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 981 "data/maps/LittlerootTown/scripts.pory"
# 546 "data/maps/LittlerootTown/scripts.pory"
# 982 "data/maps/LittlerootTown/scripts.pory"
	return
# 983 "data/maps/LittlerootTown/scripts.pory"
# 547 "data/maps/LittlerootTown/scripts.pory"
# 984 "data/maps/LittlerootTown/scripts.pory"

# 985 "data/maps/LittlerootTown/scripts.pory"
# 548 "data/maps/LittlerootTown/scripts.pory"
# 986 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale3::
# 987 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 988 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 989 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 990 "data/maps/LittlerootTown/scripts.pory"
# 553 "data/maps/LittlerootTown/scripts.pory"
# 991 "data/maps/LittlerootTown/scripts.pory"
	return
# 992 "data/maps/LittlerootTown/scripts.pory"
# 554 "data/maps/LittlerootTown/scripts.pory"
# 993 "data/maps/LittlerootTown/scripts.pory"

# 994 "data/maps/LittlerootTown/scripts.pory"
# 555 "data/maps/LittlerootTown/scripts.pory"
# 995 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale4::
# 996 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 997 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 998 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 999 "data/maps/LittlerootTown/scripts.pory"
# 560 "data/maps/LittlerootTown/scripts.pory"
# 1000 "data/maps/LittlerootTown/scripts.pory"
	return
# 1001 "data/maps/LittlerootTown/scripts.pory"
# 561 "data/maps/LittlerootTown/scripts.pory"
# 1002 "data/maps/LittlerootTown/scripts.pory"

# 1003 "data/maps/LittlerootTown/scripts.pory"
# 562 "data/maps/LittlerootTown/scripts.pory"
# 1004 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale5::
# 1005 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 1006 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1007 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1008 "data/maps/LittlerootTown/scripts.pory"
# 567 "data/maps/LittlerootTown/scripts.pory"
# 1009 "data/maps/LittlerootTown/scripts.pory"
	return
# 1010 "data/maps/LittlerootTown/scripts.pory"
# 568 "data/maps/LittlerootTown/scripts.pory"
# 1011 "data/maps/LittlerootTown/scripts.pory"

# 1012 "data/maps/LittlerootTown/scripts.pory"
# 569 "data/maps/LittlerootTown/scripts.pory"
# 1013 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale2::
# 1014 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1015 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1016 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1017 "data/maps/LittlerootTown/scripts.pory"
# 574 "data/maps/LittlerootTown/scripts.pory"
# 1018 "data/maps/LittlerootTown/scripts.pory"
	return
# 1019 "data/maps/LittlerootTown/scripts.pory"
# 575 "data/maps/LittlerootTown/scripts.pory"
# 1020 "data/maps/LittlerootTown/scripts.pory"

# 1021 "data/maps/LittlerootTown/scripts.pory"
# 576 "data/maps/LittlerootTown/scripts.pory"
# 1022 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale3::
# 1023 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1024 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1025 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1026 "data/maps/LittlerootTown/scripts.pory"
# 581 "data/maps/LittlerootTown/scripts.pory"
# 1027 "data/maps/LittlerootTown/scripts.pory"
	return
# 1028 "data/maps/LittlerootTown/scripts.pory"
# 582 "data/maps/LittlerootTown/scripts.pory"
# 1029 "data/maps/LittlerootTown/scripts.pory"

# 1030 "data/maps/LittlerootTown/scripts.pory"
# 583 "data/maps/LittlerootTown/scripts.pory"
# 1031 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale4::
# 1032 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1033 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1034 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1035 "data/maps/LittlerootTown/scripts.pory"
# 588 "data/maps/LittlerootTown/scripts.pory"
# 1036 "data/maps/LittlerootTown/scripts.pory"
	return
# 1037 "data/maps/LittlerootTown/scripts.pory"
# 589 "data/maps/LittlerootTown/scripts.pory"
# 1038 "data/maps/LittlerootTown/scripts.pory"

# 1039 "data/maps/LittlerootTown/scripts.pory"
# 590 "data/maps/LittlerootTown/scripts.pory"
# 1040 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale5::
# 1041 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1042 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1043 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1044 "data/maps/LittlerootTown/scripts.pory"
# 595 "data/maps/LittlerootTown/scripts.pory"
# 1045 "data/maps/LittlerootTown/scripts.pory"
	return
# 1046 "data/maps/LittlerootTown/scripts.pory"
# 596 "data/maps/LittlerootTown/scripts.pory"
# 1047 "data/maps/LittlerootTown/scripts.pory"

# 1048 "data/maps/LittlerootTown/scripts.pory"
# 597 "data/maps/LittlerootTown/scripts.pory"
# 1049 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale::
# 1050 "data/maps/LittlerootTown/scripts.pory"
# 598 "data/maps/LittlerootTown/scripts.pory"
# 1051 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomReturnHome0
# 1052 "data/maps/LittlerootTown/scripts.pory"
# 599 "data/maps/LittlerootTown/scripts.pory"
# 1053 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomReturnHome1
# 1054 "data/maps/LittlerootTown/scripts.pory"
# 600 "data/maps/LittlerootTown/scripts.pory"
# 1055 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomReturnHomeMale2
# 1056 "data/maps/LittlerootTown/scripts.pory"
# 601 "data/maps/LittlerootTown/scripts.pory"
# 1057 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomReturnHomeMale3
# 1058 "data/maps/LittlerootTown/scripts.pory"
# 602 "data/maps/LittlerootTown/scripts.pory"
# 1059 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomReturnHomeMale4
# 1060 "data/maps/LittlerootTown/scripts.pory"
# 603 "data/maps/LittlerootTown/scripts.pory"
# 1061 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomReturnHomeMale5
# 1062 "data/maps/LittlerootTown/scripts.pory"
# 604 "data/maps/LittlerootTown/scripts.pory"
# 1063 "data/maps/LittlerootTown/scripts.pory"
	return
# 1064 "data/maps/LittlerootTown/scripts.pory"
# 605 "data/maps/LittlerootTown/scripts.pory"
# 1065 "data/maps/LittlerootTown/scripts.pory"

# 1066 "data/maps/LittlerootTown/scripts.pory"
# 606 "data/maps/LittlerootTown/scripts.pory"
# 1067 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale::
# 1068 "data/maps/LittlerootTown/scripts.pory"
# 607 "data/maps/LittlerootTown/scripts.pory"
# 1069 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomReturnHome0
# 1070 "data/maps/LittlerootTown/scripts.pory"
# 608 "data/maps/LittlerootTown/scripts.pory"
# 1071 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomReturnHome1
# 1072 "data/maps/LittlerootTown/scripts.pory"
# 609 "data/maps/LittlerootTown/scripts.pory"
# 1073 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomReturnHomeFemale2
# 1074 "data/maps/LittlerootTown/scripts.pory"
# 610 "data/maps/LittlerootTown/scripts.pory"
# 1075 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomReturnHomeFemale3
# 1076 "data/maps/LittlerootTown/scripts.pory"
# 611 "data/maps/LittlerootTown/scripts.pory"
# 1077 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomReturnHomeFemale4
# 1078 "data/maps/LittlerootTown/scripts.pory"
# 612 "data/maps/LittlerootTown/scripts.pory"
# 1079 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomReturnHomeFemale5
# 1080 "data/maps/LittlerootTown/scripts.pory"
# 613 "data/maps/LittlerootTown/scripts.pory"
# 1081 "data/maps/LittlerootTown/scripts.pory"
	return
# 1082 "data/maps/LittlerootTown/scripts.pory"
# 614 "data/maps/LittlerootTown/scripts.pory"
# 1083 "data/maps/LittlerootTown/scripts.pory"

# 1084 "data/maps/LittlerootTown/scripts.pory"
# 615 "data/maps/LittlerootTown/scripts.pory"
# 1085 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHome0::
# 1086 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1087 "data/maps/LittlerootTown/scripts.pory"
# 618 "data/maps/LittlerootTown/scripts.pory"
# 1088 "data/maps/LittlerootTown/scripts.pory"
	return
# 1089 "data/maps/LittlerootTown/scripts.pory"
# 619 "data/maps/LittlerootTown/scripts.pory"
# 1090 "data/maps/LittlerootTown/scripts.pory"

# 1091 "data/maps/LittlerootTown/scripts.pory"
# 620 "data/maps/LittlerootTown/scripts.pory"
# 1092 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHome1::
# 1093 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1094 "data/maps/LittlerootTown/scripts.pory"
# 623 "data/maps/LittlerootTown/scripts.pory"
# 1095 "data/maps/LittlerootTown/scripts.pory"
	return
# 1096 "data/maps/LittlerootTown/scripts.pory"
# 624 "data/maps/LittlerootTown/scripts.pory"
# 1097 "data/maps/LittlerootTown/scripts.pory"

# 1098 "data/maps/LittlerootTown/scripts.pory"
# 625 "data/maps/LittlerootTown/scripts.pory"
# 1099 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale2::
# 1100 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1101 "data/maps/LittlerootTown/scripts.pory"
# 628 "data/maps/LittlerootTown/scripts.pory"
# 1102 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1103 "data/maps/LittlerootTown/scripts.pory"
# 629 "data/maps/LittlerootTown/scripts.pory"
# 1104 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1105 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1106 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1107 "data/maps/LittlerootTown/scripts.pory"
# 634 "data/maps/LittlerootTown/scripts.pory"
# 1108 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1109 "data/maps/LittlerootTown/scripts.pory"
# 635 "data/maps/LittlerootTown/scripts.pory"
# 1110 "data/maps/LittlerootTown/scripts.pory"
	return
# 1111 "data/maps/LittlerootTown/scripts.pory"
# 636 "data/maps/LittlerootTown/scripts.pory"
# 1112 "data/maps/LittlerootTown/scripts.pory"

# 1113 "data/maps/LittlerootTown/scripts.pory"
# 637 "data/maps/LittlerootTown/scripts.pory"
# 1114 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale3::
# 1115 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1116 "data/maps/LittlerootTown/scripts.pory"
# 640 "data/maps/LittlerootTown/scripts.pory"
# 1117 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1118 "data/maps/LittlerootTown/scripts.pory"
# 641 "data/maps/LittlerootTown/scripts.pory"
# 1119 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1120 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1121 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1122 "data/maps/LittlerootTown/scripts.pory"
# 646 "data/maps/LittlerootTown/scripts.pory"
# 1123 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1124 "data/maps/LittlerootTown/scripts.pory"
# 647 "data/maps/LittlerootTown/scripts.pory"
# 1125 "data/maps/LittlerootTown/scripts.pory"
	return
# 1126 "data/maps/LittlerootTown/scripts.pory"
# 648 "data/maps/LittlerootTown/scripts.pory"
# 1127 "data/maps/LittlerootTown/scripts.pory"

# 1128 "data/maps/LittlerootTown/scripts.pory"
# 649 "data/maps/LittlerootTown/scripts.pory"
# 1129 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale4::
# 1130 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1131 "data/maps/LittlerootTown/scripts.pory"
# 652 "data/maps/LittlerootTown/scripts.pory"
# 1132 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1133 "data/maps/LittlerootTown/scripts.pory"
# 653 "data/maps/LittlerootTown/scripts.pory"
# 1134 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1135 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1136 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1137 "data/maps/LittlerootTown/scripts.pory"
# 658 "data/maps/LittlerootTown/scripts.pory"
# 1138 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1139 "data/maps/LittlerootTown/scripts.pory"
# 659 "data/maps/LittlerootTown/scripts.pory"
# 1140 "data/maps/LittlerootTown/scripts.pory"
	return
# 1141 "data/maps/LittlerootTown/scripts.pory"
# 660 "data/maps/LittlerootTown/scripts.pory"
# 1142 "data/maps/LittlerootTown/scripts.pory"

# 1143 "data/maps/LittlerootTown/scripts.pory"
# 661 "data/maps/LittlerootTown/scripts.pory"
# 1144 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale5::
# 1145 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1146 "data/maps/LittlerootTown/scripts.pory"
# 664 "data/maps/LittlerootTown/scripts.pory"
# 1147 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1148 "data/maps/LittlerootTown/scripts.pory"
# 665 "data/maps/LittlerootTown/scripts.pory"
# 1149 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1150 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1151 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1152 "data/maps/LittlerootTown/scripts.pory"
# 670 "data/maps/LittlerootTown/scripts.pory"
# 1153 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1154 "data/maps/LittlerootTown/scripts.pory"
# 671 "data/maps/LittlerootTown/scripts.pory"
# 1155 "data/maps/LittlerootTown/scripts.pory"
	return
# 1156 "data/maps/LittlerootTown/scripts.pory"
# 672 "data/maps/LittlerootTown/scripts.pory"
# 1157 "data/maps/LittlerootTown/scripts.pory"

# 1158 "data/maps/LittlerootTown/scripts.pory"
# 673 "data/maps/LittlerootTown/scripts.pory"
# 1159 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale2::
# 1160 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1161 "data/maps/LittlerootTown/scripts.pory"
# 676 "data/maps/LittlerootTown/scripts.pory"
# 1162 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1163 "data/maps/LittlerootTown/scripts.pory"
# 677 "data/maps/LittlerootTown/scripts.pory"
# 1164 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1165 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1166 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1167 "data/maps/LittlerootTown/scripts.pory"
# 682 "data/maps/LittlerootTown/scripts.pory"
# 1168 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1169 "data/maps/LittlerootTown/scripts.pory"
# 683 "data/maps/LittlerootTown/scripts.pory"
# 1170 "data/maps/LittlerootTown/scripts.pory"
	return
# 1171 "data/maps/LittlerootTown/scripts.pory"
# 684 "data/maps/LittlerootTown/scripts.pory"
# 1172 "data/maps/LittlerootTown/scripts.pory"

# 1173 "data/maps/LittlerootTown/scripts.pory"
# 685 "data/maps/LittlerootTown/scripts.pory"
# 1174 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale3::
# 1175 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1176 "data/maps/LittlerootTown/scripts.pory"
# 688 "data/maps/LittlerootTown/scripts.pory"
# 1177 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1178 "data/maps/LittlerootTown/scripts.pory"
# 689 "data/maps/LittlerootTown/scripts.pory"
# 1179 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1180 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1181 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1182 "data/maps/LittlerootTown/scripts.pory"
# 694 "data/maps/LittlerootTown/scripts.pory"
# 1183 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1184 "data/maps/LittlerootTown/scripts.pory"
# 695 "data/maps/LittlerootTown/scripts.pory"
# 1185 "data/maps/LittlerootTown/scripts.pory"
	return
# 1186 "data/maps/LittlerootTown/scripts.pory"
# 696 "data/maps/LittlerootTown/scripts.pory"
# 1187 "data/maps/LittlerootTown/scripts.pory"

# 1188 "data/maps/LittlerootTown/scripts.pory"
# 697 "data/maps/LittlerootTown/scripts.pory"
# 1189 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale4::
# 1190 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1191 "data/maps/LittlerootTown/scripts.pory"
# 700 "data/maps/LittlerootTown/scripts.pory"
# 1192 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1193 "data/maps/LittlerootTown/scripts.pory"
# 701 "data/maps/LittlerootTown/scripts.pory"
# 1194 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1195 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1196 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1197 "data/maps/LittlerootTown/scripts.pory"
# 706 "data/maps/LittlerootTown/scripts.pory"
# 1198 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1199 "data/maps/LittlerootTown/scripts.pory"
# 707 "data/maps/LittlerootTown/scripts.pory"
# 1200 "data/maps/LittlerootTown/scripts.pory"
	return
# 1201 "data/maps/LittlerootTown/scripts.pory"
# 708 "data/maps/LittlerootTown/scripts.pory"
# 1202 "data/maps/LittlerootTown/scripts.pory"

# 1203 "data/maps/LittlerootTown/scripts.pory"
# 709 "data/maps/LittlerootTown/scripts.pory"
# 1204 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale5::
# 1205 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1206 "data/maps/LittlerootTown/scripts.pory"
# 712 "data/maps/LittlerootTown/scripts.pory"
# 1207 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1208 "data/maps/LittlerootTown/scripts.pory"
# 713 "data/maps/LittlerootTown/scripts.pory"
# 1209 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1210 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1211 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1212 "data/maps/LittlerootTown/scripts.pory"
# 718 "data/maps/LittlerootTown/scripts.pory"
# 1213 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1214 "data/maps/LittlerootTown/scripts.pory"
# 719 "data/maps/LittlerootTown/scripts.pory"
# 1215 "data/maps/LittlerootTown/scripts.pory"
	return
# 1216 "data/maps/LittlerootTown/scripts.pory"
# 720 "data/maps/LittlerootTown/scripts.pory"
# 1217 "data/maps/LittlerootTown/scripts.pory"

# 1218 "data/maps/LittlerootTown/scripts.pory"
# 721 "data/maps/LittlerootTown/scripts.pory"
# 1219 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayer0:
# 1220 "data/maps/LittlerootTown/scripts.pory"
# 722 "data/maps/LittlerootTown/scripts.pory"
# 1221 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1222 "data/maps/LittlerootTown/scripts.pory"
# 723 "data/maps/LittlerootTown/scripts.pory"
# 1223 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1224 "data/maps/LittlerootTown/scripts.pory"
# 724 "data/maps/LittlerootTown/scripts.pory"
# 1225 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1226 "data/maps/LittlerootTown/scripts.pory"
# 725 "data/maps/LittlerootTown/scripts.pory"
# 1227 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1228 "data/maps/LittlerootTown/scripts.pory"
# 726 "data/maps/LittlerootTown/scripts.pory"
# 1229 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1230 "data/maps/LittlerootTown/scripts.pory"
# 727 "data/maps/LittlerootTown/scripts.pory"
# 1231 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1232 "data/maps/LittlerootTown/scripts.pory"
# 728 "data/maps/LittlerootTown/scripts.pory"
# 1233 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1234 "data/maps/LittlerootTown/scripts.pory"
# 729 "data/maps/LittlerootTown/scripts.pory"
# 1235 "data/maps/LittlerootTown/scripts.pory"

# 1236 "data/maps/LittlerootTown/scripts.pory"
# 730 "data/maps/LittlerootTown/scripts.pory"
# 1237 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayer1:
# 1238 "data/maps/LittlerootTown/scripts.pory"
# 731 "data/maps/LittlerootTown/scripts.pory"
# 1239 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1240 "data/maps/LittlerootTown/scripts.pory"
# 732 "data/maps/LittlerootTown/scripts.pory"
# 1241 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1242 "data/maps/LittlerootTown/scripts.pory"
# 733 "data/maps/LittlerootTown/scripts.pory"
# 1243 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1244 "data/maps/LittlerootTown/scripts.pory"
# 734 "data/maps/LittlerootTown/scripts.pory"
# 1245 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1246 "data/maps/LittlerootTown/scripts.pory"
# 735 "data/maps/LittlerootTown/scripts.pory"
# 1247 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1248 "data/maps/LittlerootTown/scripts.pory"
# 736 "data/maps/LittlerootTown/scripts.pory"
# 1249 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1250 "data/maps/LittlerootTown/scripts.pory"
# 737 "data/maps/LittlerootTown/scripts.pory"
# 1251 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1252 "data/maps/LittlerootTown/scripts.pory"
# 738 "data/maps/LittlerootTown/scripts.pory"
# 1253 "data/maps/LittlerootTown/scripts.pory"

# 1254 "data/maps/LittlerootTown/scripts.pory"
# 739 "data/maps/LittlerootTown/scripts.pory"
# 1255 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale2:
# 1256 "data/maps/LittlerootTown/scripts.pory"
# 740 "data/maps/LittlerootTown/scripts.pory"
# 1257 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1258 "data/maps/LittlerootTown/scripts.pory"
# 741 "data/maps/LittlerootTown/scripts.pory"
# 1259 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1260 "data/maps/LittlerootTown/scripts.pory"
# 742 "data/maps/LittlerootTown/scripts.pory"
# 1261 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1262 "data/maps/LittlerootTown/scripts.pory"
# 743 "data/maps/LittlerootTown/scripts.pory"
# 1263 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1264 "data/maps/LittlerootTown/scripts.pory"
# 744 "data/maps/LittlerootTown/scripts.pory"
# 1265 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1266 "data/maps/LittlerootTown/scripts.pory"
# 745 "data/maps/LittlerootTown/scripts.pory"
# 1267 "data/maps/LittlerootTown/scripts.pory"

# 1268 "data/maps/LittlerootTown/scripts.pory"
# 746 "data/maps/LittlerootTown/scripts.pory"
# 1269 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale3:
# 1270 "data/maps/LittlerootTown/scripts.pory"
# 747 "data/maps/LittlerootTown/scripts.pory"
# 1271 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1272 "data/maps/LittlerootTown/scripts.pory"
# 748 "data/maps/LittlerootTown/scripts.pory"
# 1273 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1274 "data/maps/LittlerootTown/scripts.pory"
# 749 "data/maps/LittlerootTown/scripts.pory"
# 1275 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1276 "data/maps/LittlerootTown/scripts.pory"
# 750 "data/maps/LittlerootTown/scripts.pory"
# 1277 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1278 "data/maps/LittlerootTown/scripts.pory"
# 751 "data/maps/LittlerootTown/scripts.pory"
# 1279 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1280 "data/maps/LittlerootTown/scripts.pory"
# 752 "data/maps/LittlerootTown/scripts.pory"
# 1281 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1282 "data/maps/LittlerootTown/scripts.pory"
# 753 "data/maps/LittlerootTown/scripts.pory"
# 1283 "data/maps/LittlerootTown/scripts.pory"

# 1284 "data/maps/LittlerootTown/scripts.pory"
# 754 "data/maps/LittlerootTown/scripts.pory"
# 1285 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale4:
# 1286 "data/maps/LittlerootTown/scripts.pory"
# 755 "data/maps/LittlerootTown/scripts.pory"
# 1287 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1288 "data/maps/LittlerootTown/scripts.pory"
# 756 "data/maps/LittlerootTown/scripts.pory"
# 1289 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1290 "data/maps/LittlerootTown/scripts.pory"
# 757 "data/maps/LittlerootTown/scripts.pory"
# 1291 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1292 "data/maps/LittlerootTown/scripts.pory"
# 758 "data/maps/LittlerootTown/scripts.pory"
# 1293 "data/maps/LittlerootTown/scripts.pory"

# 1294 "data/maps/LittlerootTown/scripts.pory"
# 759 "data/maps/LittlerootTown/scripts.pory"
# 1295 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale5:
# 1296 "data/maps/LittlerootTown/scripts.pory"
# 760 "data/maps/LittlerootTown/scripts.pory"
# 1297 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1298 "data/maps/LittlerootTown/scripts.pory"
# 761 "data/maps/LittlerootTown/scripts.pory"
# 1299 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1300 "data/maps/LittlerootTown/scripts.pory"
# 762 "data/maps/LittlerootTown/scripts.pory"
# 1301 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1302 "data/maps/LittlerootTown/scripts.pory"
# 763 "data/maps/LittlerootTown/scripts.pory"
# 1303 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1304 "data/maps/LittlerootTown/scripts.pory"
# 764 "data/maps/LittlerootTown/scripts.pory"
# 1305 "data/maps/LittlerootTown/scripts.pory"

# 1306 "data/maps/LittlerootTown/scripts.pory"
# 765 "data/maps/LittlerootTown/scripts.pory"
# 1307 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale2:
# 1308 "data/maps/LittlerootTown/scripts.pory"
# 766 "data/maps/LittlerootTown/scripts.pory"
# 1309 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1310 "data/maps/LittlerootTown/scripts.pory"
# 767 "data/maps/LittlerootTown/scripts.pory"
# 1311 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1312 "data/maps/LittlerootTown/scripts.pory"
# 768 "data/maps/LittlerootTown/scripts.pory"
# 1313 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1314 "data/maps/LittlerootTown/scripts.pory"
# 769 "data/maps/LittlerootTown/scripts.pory"
# 1315 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1316 "data/maps/LittlerootTown/scripts.pory"
# 770 "data/maps/LittlerootTown/scripts.pory"
# 1317 "data/maps/LittlerootTown/scripts.pory"

# 1318 "data/maps/LittlerootTown/scripts.pory"
# 771 "data/maps/LittlerootTown/scripts.pory"
# 1319 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale3:
# 1320 "data/maps/LittlerootTown/scripts.pory"
# 772 "data/maps/LittlerootTown/scripts.pory"
# 1321 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1322 "data/maps/LittlerootTown/scripts.pory"
# 773 "data/maps/LittlerootTown/scripts.pory"
# 1323 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1324 "data/maps/LittlerootTown/scripts.pory"
# 774 "data/maps/LittlerootTown/scripts.pory"
# 1325 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1326 "data/maps/LittlerootTown/scripts.pory"
# 775 "data/maps/LittlerootTown/scripts.pory"
# 1327 "data/maps/LittlerootTown/scripts.pory"

# 1328 "data/maps/LittlerootTown/scripts.pory"
# 776 "data/maps/LittlerootTown/scripts.pory"
# 1329 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale4:
# 1330 "data/maps/LittlerootTown/scripts.pory"
# 777 "data/maps/LittlerootTown/scripts.pory"
# 1331 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1332 "data/maps/LittlerootTown/scripts.pory"
# 778 "data/maps/LittlerootTown/scripts.pory"
# 1333 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1334 "data/maps/LittlerootTown/scripts.pory"
# 779 "data/maps/LittlerootTown/scripts.pory"
# 1335 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1336 "data/maps/LittlerootTown/scripts.pory"
# 780 "data/maps/LittlerootTown/scripts.pory"
# 1337 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1338 "data/maps/LittlerootTown/scripts.pory"
# 781 "data/maps/LittlerootTown/scripts.pory"
# 1339 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1340 "data/maps/LittlerootTown/scripts.pory"
# 782 "data/maps/LittlerootTown/scripts.pory"
# 1341 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1342 "data/maps/LittlerootTown/scripts.pory"
# 783 "data/maps/LittlerootTown/scripts.pory"
# 1343 "data/maps/LittlerootTown/scripts.pory"

# 1344 "data/maps/LittlerootTown/scripts.pory"
# 784 "data/maps/LittlerootTown/scripts.pory"
# 1345 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale5:
# 1346 "data/maps/LittlerootTown/scripts.pory"
# 785 "data/maps/LittlerootTown/scripts.pory"
# 1347 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1348 "data/maps/LittlerootTown/scripts.pory"
# 786 "data/maps/LittlerootTown/scripts.pory"
# 1349 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1350 "data/maps/LittlerootTown/scripts.pory"
# 787 "data/maps/LittlerootTown/scripts.pory"
# 1351 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1352 "data/maps/LittlerootTown/scripts.pory"
# 788 "data/maps/LittlerootTown/scripts.pory"
# 1353 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1354 "data/maps/LittlerootTown/scripts.pory"
# 789 "data/maps/LittlerootTown/scripts.pory"
# 1355 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1356 "data/maps/LittlerootTown/scripts.pory"
# 790 "data/maps/LittlerootTown/scripts.pory"
# 1357 "data/maps/LittlerootTown/scripts.pory"

# 1358 "data/maps/LittlerootTown/scripts.pory"
# 791 "data/maps/LittlerootTown/scripts.pory"
# 1359 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHome0:
# 1360 "data/maps/LittlerootTown/scripts.pory"
# 792 "data/maps/LittlerootTown/scripts.pory"
# 1361 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1362 "data/maps/LittlerootTown/scripts.pory"
# 793 "data/maps/LittlerootTown/scripts.pory"
# 1363 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1364 "data/maps/LittlerootTown/scripts.pory"
# 794 "data/maps/LittlerootTown/scripts.pory"
# 1365 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1366 "data/maps/LittlerootTown/scripts.pory"
# 795 "data/maps/LittlerootTown/scripts.pory"
# 1367 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1368 "data/maps/LittlerootTown/scripts.pory"
# 796 "data/maps/LittlerootTown/scripts.pory"
# 1369 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1370 "data/maps/LittlerootTown/scripts.pory"
# 797 "data/maps/LittlerootTown/scripts.pory"
# 1371 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1372 "data/maps/LittlerootTown/scripts.pory"
# 798 "data/maps/LittlerootTown/scripts.pory"
# 1373 "data/maps/LittlerootTown/scripts.pory"

# 1374 "data/maps/LittlerootTown/scripts.pory"
# 799 "data/maps/LittlerootTown/scripts.pory"
# 1375 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHome1:
# 1376 "data/maps/LittlerootTown/scripts.pory"
# 800 "data/maps/LittlerootTown/scripts.pory"
# 1377 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1378 "data/maps/LittlerootTown/scripts.pory"
# 801 "data/maps/LittlerootTown/scripts.pory"
# 1379 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1380 "data/maps/LittlerootTown/scripts.pory"
# 802 "data/maps/LittlerootTown/scripts.pory"
# 1381 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1382 "data/maps/LittlerootTown/scripts.pory"
# 803 "data/maps/LittlerootTown/scripts.pory"
# 1383 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1384 "data/maps/LittlerootTown/scripts.pory"
# 804 "data/maps/LittlerootTown/scripts.pory"
# 1385 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1386 "data/maps/LittlerootTown/scripts.pory"
# 805 "data/maps/LittlerootTown/scripts.pory"
# 1387 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1388 "data/maps/LittlerootTown/scripts.pory"
# 806 "data/maps/LittlerootTown/scripts.pory"
# 1389 "data/maps/LittlerootTown/scripts.pory"

# 1390 "data/maps/LittlerootTown/scripts.pory"
# 807 "data/maps/LittlerootTown/scripts.pory"
# 1391 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale2:
# 1392 "data/maps/LittlerootTown/scripts.pory"
# 808 "data/maps/LittlerootTown/scripts.pory"
# 1393 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1394 "data/maps/LittlerootTown/scripts.pory"
# 809 "data/maps/LittlerootTown/scripts.pory"
# 1395 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1396 "data/maps/LittlerootTown/scripts.pory"
# 810 "data/maps/LittlerootTown/scripts.pory"
# 1397 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1398 "data/maps/LittlerootTown/scripts.pory"
# 811 "data/maps/LittlerootTown/scripts.pory"
# 1399 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1400 "data/maps/LittlerootTown/scripts.pory"
# 812 "data/maps/LittlerootTown/scripts.pory"
# 1401 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1402 "data/maps/LittlerootTown/scripts.pory"
# 813 "data/maps/LittlerootTown/scripts.pory"
# 1403 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1404 "data/maps/LittlerootTown/scripts.pory"
# 814 "data/maps/LittlerootTown/scripts.pory"
# 1405 "data/maps/LittlerootTown/scripts.pory"

# 1406 "data/maps/LittlerootTown/scripts.pory"
# 815 "data/maps/LittlerootTown/scripts.pory"
# 1407 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale3:
# 1408 "data/maps/LittlerootTown/scripts.pory"
# 816 "data/maps/LittlerootTown/scripts.pory"
# 1409 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1410 "data/maps/LittlerootTown/scripts.pory"
# 817 "data/maps/LittlerootTown/scripts.pory"
# 1411 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1412 "data/maps/LittlerootTown/scripts.pory"
# 818 "data/maps/LittlerootTown/scripts.pory"
# 1413 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1414 "data/maps/LittlerootTown/scripts.pory"
# 819 "data/maps/LittlerootTown/scripts.pory"
# 1415 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1416 "data/maps/LittlerootTown/scripts.pory"
# 820 "data/maps/LittlerootTown/scripts.pory"
# 1417 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1418 "data/maps/LittlerootTown/scripts.pory"
# 821 "data/maps/LittlerootTown/scripts.pory"
# 1419 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1420 "data/maps/LittlerootTown/scripts.pory"
# 822 "data/maps/LittlerootTown/scripts.pory"
# 1421 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1422 "data/maps/LittlerootTown/scripts.pory"
# 823 "data/maps/LittlerootTown/scripts.pory"
# 1423 "data/maps/LittlerootTown/scripts.pory"

# 1424 "data/maps/LittlerootTown/scripts.pory"
# 824 "data/maps/LittlerootTown/scripts.pory"
# 1425 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale4:
# 1426 "data/maps/LittlerootTown/scripts.pory"
# 825 "data/maps/LittlerootTown/scripts.pory"
# 1427 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1428 "data/maps/LittlerootTown/scripts.pory"
# 826 "data/maps/LittlerootTown/scripts.pory"
# 1429 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1430 "data/maps/LittlerootTown/scripts.pory"
# 827 "data/maps/LittlerootTown/scripts.pory"
# 1431 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1432 "data/maps/LittlerootTown/scripts.pory"
# 828 "data/maps/LittlerootTown/scripts.pory"
# 1433 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1434 "data/maps/LittlerootTown/scripts.pory"
# 829 "data/maps/LittlerootTown/scripts.pory"
# 1435 "data/maps/LittlerootTown/scripts.pory"

# 1436 "data/maps/LittlerootTown/scripts.pory"
# 830 "data/maps/LittlerootTown/scripts.pory"
# 1437 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale5:
# 1438 "data/maps/LittlerootTown/scripts.pory"
# 831 "data/maps/LittlerootTown/scripts.pory"
# 1439 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1440 "data/maps/LittlerootTown/scripts.pory"
# 832 "data/maps/LittlerootTown/scripts.pory"
# 1441 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1442 "data/maps/LittlerootTown/scripts.pory"
# 833 "data/maps/LittlerootTown/scripts.pory"
# 1443 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1444 "data/maps/LittlerootTown/scripts.pory"
# 834 "data/maps/LittlerootTown/scripts.pory"
# 1445 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1446 "data/maps/LittlerootTown/scripts.pory"
# 835 "data/maps/LittlerootTown/scripts.pory"
# 1447 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1448 "data/maps/LittlerootTown/scripts.pory"
# 836 "data/maps/LittlerootTown/scripts.pory"
# 1449 "data/maps/LittlerootTown/scripts.pory"

# 1450 "data/maps/LittlerootTown/scripts.pory"
# 837 "data/maps/LittlerootTown/scripts.pory"
# 1451 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale2:
# 1452 "data/maps/LittlerootTown/scripts.pory"
# 838 "data/maps/LittlerootTown/scripts.pory"
# 1453 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1454 "data/maps/LittlerootTown/scripts.pory"
# 839 "data/maps/LittlerootTown/scripts.pory"
# 1455 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1456 "data/maps/LittlerootTown/scripts.pory"
# 840 "data/maps/LittlerootTown/scripts.pory"
# 1457 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1458 "data/maps/LittlerootTown/scripts.pory"
# 841 "data/maps/LittlerootTown/scripts.pory"
# 1459 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1460 "data/maps/LittlerootTown/scripts.pory"
# 842 "data/maps/LittlerootTown/scripts.pory"
# 1461 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1462 "data/maps/LittlerootTown/scripts.pory"
# 843 "data/maps/LittlerootTown/scripts.pory"
# 1463 "data/maps/LittlerootTown/scripts.pory"

# 1464 "data/maps/LittlerootTown/scripts.pory"
# 844 "data/maps/LittlerootTown/scripts.pory"
# 1465 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale3:
# 1466 "data/maps/LittlerootTown/scripts.pory"
# 845 "data/maps/LittlerootTown/scripts.pory"
# 1467 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1468 "data/maps/LittlerootTown/scripts.pory"
# 846 "data/maps/LittlerootTown/scripts.pory"
# 1469 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1470 "data/maps/LittlerootTown/scripts.pory"
# 847 "data/maps/LittlerootTown/scripts.pory"
# 1471 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1472 "data/maps/LittlerootTown/scripts.pory"
# 848 "data/maps/LittlerootTown/scripts.pory"
# 1473 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1474 "data/maps/LittlerootTown/scripts.pory"
# 849 "data/maps/LittlerootTown/scripts.pory"
# 1475 "data/maps/LittlerootTown/scripts.pory"

# 1476 "data/maps/LittlerootTown/scripts.pory"
# 850 "data/maps/LittlerootTown/scripts.pory"
# 1477 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale4:
# 1478 "data/maps/LittlerootTown/scripts.pory"
# 851 "data/maps/LittlerootTown/scripts.pory"
# 1479 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1480 "data/maps/LittlerootTown/scripts.pory"
# 852 "data/maps/LittlerootTown/scripts.pory"
# 1481 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1482 "data/maps/LittlerootTown/scripts.pory"
# 853 "data/maps/LittlerootTown/scripts.pory"
# 1483 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1484 "data/maps/LittlerootTown/scripts.pory"
# 854 "data/maps/LittlerootTown/scripts.pory"
# 1485 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1486 "data/maps/LittlerootTown/scripts.pory"
# 855 "data/maps/LittlerootTown/scripts.pory"
# 1487 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1488 "data/maps/LittlerootTown/scripts.pory"
# 856 "data/maps/LittlerootTown/scripts.pory"
# 1489 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1490 "data/maps/LittlerootTown/scripts.pory"
# 857 "data/maps/LittlerootTown/scripts.pory"
# 1491 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1492 "data/maps/LittlerootTown/scripts.pory"
# 858 "data/maps/LittlerootTown/scripts.pory"
# 1493 "data/maps/LittlerootTown/scripts.pory"

# 1494 "data/maps/LittlerootTown/scripts.pory"
# 859 "data/maps/LittlerootTown/scripts.pory"
# 1495 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale5:
# 1496 "data/maps/LittlerootTown/scripts.pory"
# 860 "data/maps/LittlerootTown/scripts.pory"
# 1497 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1498 "data/maps/LittlerootTown/scripts.pory"
# 861 "data/maps/LittlerootTown/scripts.pory"
# 1499 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1500 "data/maps/LittlerootTown/scripts.pory"
# 862 "data/maps/LittlerootTown/scripts.pory"
# 1501 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1502 "data/maps/LittlerootTown/scripts.pory"
# 863 "data/maps/LittlerootTown/scripts.pory"
# 1503 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1504 "data/maps/LittlerootTown/scripts.pory"
# 864 "data/maps/LittlerootTown/scripts.pory"
# 1505 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1506 "data/maps/LittlerootTown/scripts.pory"
# 865 "data/maps/LittlerootTown/scripts.pory"
# 1507 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1508 "data/maps/LittlerootTown/scripts.pory"
# 866 "data/maps/LittlerootTown/scripts.pory"
# 1509 "data/maps/LittlerootTown/scripts.pory"

# 1510 "data/maps/LittlerootTown/scripts.pory"
# 867 "data/maps/LittlerootTown/scripts.pory"
# 1511 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomExitThroughDoor:
# 1512 "data/maps/LittlerootTown/scripts.pory"
# 868 "data/maps/LittlerootTown/scripts.pory"
# 1513 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1514 "data/maps/LittlerootTown/scripts.pory"
# 869 "data/maps/LittlerootTown/scripts.pory"
# 1515 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1516 "data/maps/LittlerootTown/scripts.pory"
# 870 "data/maps/LittlerootTown/scripts.pory"
# 1517 "data/maps/LittlerootTown/scripts.pory"

# 1518 "data/maps/LittlerootTown/scripts.pory"
# 871 "data/maps/LittlerootTown/scripts.pory"
# 1519 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_Mom::
# 1520 "data/maps/LittlerootTown/scripts.pory"
# 872 "data/maps/LittlerootTown/scripts.pory"
# 1521 "data/maps/LittlerootTown/scripts.pory"
	lock
# 1522 "data/maps/LittlerootTown/scripts.pory"
# 873 "data/maps/LittlerootTown/scripts.pory"
# 1523 "data/maps/LittlerootTown/scripts.pory"
	faceplayer
# 1524 "data/maps/LittlerootTown/scripts.pory"
# 874 "data/maps/LittlerootTown/scripts.pory"
# 1525 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 1526 "data/maps/LittlerootTown/scripts.pory"
# 875 "data/maps/LittlerootTown/scripts.pory"
# 1527 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetHomeDoorCoordsMale
# 1528 "data/maps/LittlerootTown/scripts.pory"
# 876 "data/maps/LittlerootTown/scripts.pory"
# 1529 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_SetHomeDoorCoordsFemale
# 1530 "data/maps/LittlerootTown/scripts.pory"
# 877 "data/maps/LittlerootTown/scripts.pory"
# 1531 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GiveRunningShoes
# 1532 "data/maps/LittlerootTown/scripts.pory"
# 878 "data/maps/LittlerootTown/scripts.pory"
# 1533 "data/maps/LittlerootTown/scripts.pory"
# 879 "data/maps/LittlerootTown/scripts.pory"
# 1534 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1535 "data/maps/LittlerootTown/scripts.pory"
# 880 "data/maps/LittlerootTown/scripts.pory"
# 1536 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1537 "data/maps/LittlerootTown/scripts.pory"
# 881 "data/maps/LittlerootTown/scripts.pory"
# 1538 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1539 "data/maps/LittlerootTown/scripts.pory"
# 882 "data/maps/LittlerootTown/scripts.pory"
# 1540 "data/maps/LittlerootTown/scripts.pory"
# 883 "data/maps/LittlerootTown/scripts.pory"
# 1541 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1542 "data/maps/LittlerootTown/scripts.pory"
# 884 "data/maps/LittlerootTown/scripts.pory"
# 1543 "data/maps/LittlerootTown/scripts.pory"
# 885 "data/maps/LittlerootTown/scripts.pory"
# 1544 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1545 "data/maps/LittlerootTown/scripts.pory"
# 886 "data/maps/LittlerootTown/scripts.pory"
# 1546 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1547 "data/maps/LittlerootTown/scripts.pory"
# 887 "data/maps/LittlerootTown/scripts.pory"
# 1548 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_SetReceivedRunningShoes
# 1549 "data/maps/LittlerootTown/scripts.pory"
# 888 "data/maps/LittlerootTown/scripts.pory"
# 1550 "data/maps/LittlerootTown/scripts.pory"
	end
# 1551 "data/maps/LittlerootTown/scripts.pory"
# 889 "data/maps/LittlerootTown/scripts.pory"
# 1552 "data/maps/LittlerootTown/scripts.pory"

# 1553 "data/maps/LittlerootTown/scripts.pory"
# 890 "data/maps/LittlerootTown/scripts.pory"
# 1554 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetReceivedRunningShoes::
# 1555 "data/maps/LittlerootTown/scripts.pory"
# 891 "data/maps/LittlerootTown/scripts.pory"
# 1556 "data/maps/LittlerootTown/scripts.pory"
# 892 "data/maps/LittlerootTown/scripts.pory"
# 1557 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_SYS_B_DASH
# 1558 "data/maps/LittlerootTown/scripts.pory"
# 893 "data/maps/LittlerootTown/scripts.pory"
# 1559 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_TOWN_STATE, 4
# 1560 "data/maps/LittlerootTown/scripts.pory"
# 894 "data/maps/LittlerootTown/scripts.pory"
# 1561 "data/maps/LittlerootTown/scripts.pory"
	release
# 1562 "data/maps/LittlerootTown/scripts.pory"
# 895 "data/maps/LittlerootTown/scripts.pory"
# 1563 "data/maps/LittlerootTown/scripts.pory"
	end
# 1564 "data/maps/LittlerootTown/scripts.pory"
# 896 "data/maps/LittlerootTown/scripts.pory"
# 1565 "data/maps/LittlerootTown/scripts.pory"

# 1566 "data/maps/LittlerootTown/scripts.pory"
# 897 "data/maps/LittlerootTown/scripts.pory"
# 1567 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoes::
# 1568 "data/maps/LittlerootTown/scripts.pory"
# 898 "data/maps/LittlerootTown/scripts.pory"
# 1569 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_WearTheseRunningShoes, MSGBOX_DEFAULT
# 1570 "data/maps/LittlerootTown/scripts.pory"
# 899 "data/maps/LittlerootTown/scripts.pory"
# 1571 "data/maps/LittlerootTown/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1572 "data/maps/LittlerootTown/scripts.pory"
# 900 "data/maps/LittlerootTown/scripts.pory"
# 1573 "data/maps/LittlerootTown/scripts.pory"
	message LittlerootTown_Text_SwitchShoesWithRunningShoes
# 1574 "data/maps/LittlerootTown/scripts.pory"
# 901 "data/maps/LittlerootTown/scripts.pory"
# 1575 "data/maps/LittlerootTown/scripts.pory"
	waitfanfare
# 1576 "data/maps/LittlerootTown/scripts.pory"
# 902 "data/maps/LittlerootTown/scripts.pory"
# 1577 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_RECEIVED_RUNNING_SHOES
# 1578 "data/maps/LittlerootTown/scripts.pory"
# 903 "data/maps/LittlerootTown/scripts.pory"
# 1579 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ExplainRunningShoes, MSGBOX_DEFAULT
# 1580 "data/maps/LittlerootTown/scripts.pory"
# 904 "data/maps/LittlerootTown/scripts.pory"
# 1581 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ComeHomeIfAnythingHappens, MSGBOX_DEFAULT
# 1582 "data/maps/LittlerootTown/scripts.pory"
# 905 "data/maps/LittlerootTown/scripts.pory"
# 1583 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 1584 "data/maps/LittlerootTown/scripts.pory"
# 906 "data/maps/LittlerootTown/scripts.pory"
# 1585 "data/maps/LittlerootTown/scripts.pory"
	delay 30
# 1586 "data/maps/LittlerootTown/scripts.pory"
# 907 "data/maps/LittlerootTown/scripts.pory"
# 1587 "data/maps/LittlerootTown/scripts.pory"
	return
# 1588 "data/maps/LittlerootTown/scripts.pory"
# 908 "data/maps/LittlerootTown/scripts.pory"
# 1589 "data/maps/LittlerootTown/scripts.pory"

# 1590 "data/maps/LittlerootTown/scripts.pory"
# 909 "data/maps/LittlerootTown/scripts.pory"
# 1591 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_OurNewHomeLetsGoInside:
# 1592 "data/maps/LittlerootTown/scripts.pory"
# 910 "data/maps/LittlerootTown/scripts.pory"
# 1593 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: {PLAYER}, we're here, honey!\p"
# 1594 "data/maps/LittlerootTown/scripts.pory"
# 911 "data/maps/LittlerootTown/scripts.pory"
# 1595 "data/maps/LittlerootTown/scripts.pory"
	.string "It must be tiring riding with our things\n"
# 1596 "data/maps/LittlerootTown/scripts.pory"
# 912 "data/maps/LittlerootTown/scripts.pory"
# 1597 "data/maps/LittlerootTown/scripts.pory"
	.string "in the moving truck.\p"
# 1598 "data/maps/LittlerootTown/scripts.pory"
# 913 "data/maps/LittlerootTown/scripts.pory"
# 1599 "data/maps/LittlerootTown/scripts.pory"
	.string "Well, this is LITTLEROOT TOWN.\p"
# 1600 "data/maps/LittlerootTown/scripts.pory"
# 914 "data/maps/LittlerootTown/scripts.pory"
# 1601 "data/maps/LittlerootTown/scripts.pory"
	.string "How do you like it?\n"
# 1602 "data/maps/LittlerootTown/scripts.pory"
# 915 "data/maps/LittlerootTown/scripts.pory"
# 1603 "data/maps/LittlerootTown/scripts.pory"
	.string "This is our new home!\p"
# 1604 "data/maps/LittlerootTown/scripts.pory"
# 916 "data/maps/LittlerootTown/scripts.pory"
# 1605 "data/maps/LittlerootTown/scripts.pory"
	.string "It has a quaint feel, but it seems to be\n"
# 1606 "data/maps/LittlerootTown/scripts.pory"
# 917 "data/maps/LittlerootTown/scripts.pory"
# 1607 "data/maps/LittlerootTown/scripts.pory"
	.string "an easy place to live, don't you think?\p"
# 1608 "data/maps/LittlerootTown/scripts.pory"
# 918 "data/maps/LittlerootTown/scripts.pory"
# 1609 "data/maps/LittlerootTown/scripts.pory"
	.string "And, you get your own room, {PLAYER}!\n"
# 1610 "data/maps/LittlerootTown/scripts.pory"
# 919 "data/maps/LittlerootTown/scripts.pory"
# 1611 "data/maps/LittlerootTown/scripts.pory"
	.string "Let's go inside.$"
# 1612 "data/maps/LittlerootTown/scripts.pory"
# 920 "data/maps/LittlerootTown/scripts.pory"
# 1613 "data/maps/LittlerootTown/scripts.pory"

# 1614 "data/maps/LittlerootTown/scripts.pory"
# 921 "data/maps/LittlerootTown/scripts.pory"
# 1615 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_WaitPlayer:
# 1616 "data/maps/LittlerootTown/scripts.pory"
# 922 "data/maps/LittlerootTown/scripts.pory"
# 1617 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: Wait, {PLAYER}!$"
# 1618 "data/maps/LittlerootTown/scripts.pory"
# 923 "data/maps/LittlerootTown/scripts.pory"
# 1619 "data/maps/LittlerootTown/scripts.pory"

# 1620 "data/maps/LittlerootTown/scripts.pory"
# 924 "data/maps/LittlerootTown/scripts.pory"
# 1621 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_WearTheseRunningShoes:
# 1622 "data/maps/LittlerootTown/scripts.pory"
# 925 "data/maps/LittlerootTown/scripts.pory"
# 1623 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: {PLAYER}! {PLAYER}! Did you\n"
# 1624 "data/maps/LittlerootTown/scripts.pory"
# 926 "data/maps/LittlerootTown/scripts.pory"
# 1625 "data/maps/LittlerootTown/scripts.pory"
	.string "introduce yourself to PROF. BIRCH?\p"
# 1626 "data/maps/LittlerootTown/scripts.pory"
# 927 "data/maps/LittlerootTown/scripts.pory"
# 1627 "data/maps/LittlerootTown/scripts.pory"
	.string "Oh! What an adorable POKéMON!\n"
# 1628 "data/maps/LittlerootTown/scripts.pory"
# 928 "data/maps/LittlerootTown/scripts.pory"
# 1629 "data/maps/LittlerootTown/scripts.pory"
	.string "You got it from PROF. BIRCH. How nice!\p"
# 1630 "data/maps/LittlerootTown/scripts.pory"
# 929 "data/maps/LittlerootTown/scripts.pory"
# 1631 "data/maps/LittlerootTown/scripts.pory"
	.string "You're your father's child, all right.\n"
# 1632 "data/maps/LittlerootTown/scripts.pory"
# 930 "data/maps/LittlerootTown/scripts.pory"
# 1633 "data/maps/LittlerootTown/scripts.pory"
	.string "You look good together with POKéMON!\p"
# 1634 "data/maps/LittlerootTown/scripts.pory"
# 931 "data/maps/LittlerootTown/scripts.pory"
# 1635 "data/maps/LittlerootTown/scripts.pory"
	.string "Here, honey! If you're going out on an\n"
# 1636 "data/maps/LittlerootTown/scripts.pory"
# 932 "data/maps/LittlerootTown/scripts.pory"
# 1637 "data/maps/LittlerootTown/scripts.pory"
	.string "adventure, wear these RUNNING SHOES.\p"
# 1638 "data/maps/LittlerootTown/scripts.pory"
# 933 "data/maps/LittlerootTown/scripts.pory"
# 1639 "data/maps/LittlerootTown/scripts.pory"
	.string "They'll put a zip in your step!$"
# 1640 "data/maps/LittlerootTown/scripts.pory"
# 934 "data/maps/LittlerootTown/scripts.pory"
# 1641 "data/maps/LittlerootTown/scripts.pory"

# 1642 "data/maps/LittlerootTown/scripts.pory"
# 935 "data/maps/LittlerootTown/scripts.pory"
# 1643 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_SwitchShoesWithRunningShoes:
# 1644 "data/maps/LittlerootTown/scripts.pory"
# 936 "data/maps/LittlerootTown/scripts.pory"
# 1645 "data/maps/LittlerootTown/scripts.pory"
	.string "{PLAYER} switched shoes with the\n"
# 1646 "data/maps/LittlerootTown/scripts.pory"
# 937 "data/maps/LittlerootTown/scripts.pory"
# 1647 "data/maps/LittlerootTown/scripts.pory"
	.string "RUNNING SHOES.$"
# 1648 "data/maps/LittlerootTown/scripts.pory"
# 938 "data/maps/LittlerootTown/scripts.pory"
# 1649 "data/maps/LittlerootTown/scripts.pory"

# 1650 "data/maps/LittlerootTown/scripts.pory"
# 939 "data/maps/LittlerootTown/scripts.pory"
# 1651 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ExplainRunningShoes:
# 1652 "data/maps/LittlerootTown/scripts.pory"
# 940 "data/maps/LittlerootTown/scripts.pory"
# 1653 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: {PLAYER}, those shoes came with\n"
# 1654 "data/maps/LittlerootTown/scripts.pory"
# 941 "data/maps/LittlerootTown/scripts.pory"
# 1655 "data/maps/LittlerootTown/scripts.pory"
	.string "instructions.\p"
# 1656 "data/maps/LittlerootTown/scripts.pory"
# 942 "data/maps/LittlerootTown/scripts.pory"
# 1657 "data/maps/LittlerootTown/scripts.pory"
	.string "“Press the B Button while wearing these\n"
# 1658 "data/maps/LittlerootTown/scripts.pory"
# 943 "data/maps/LittlerootTown/scripts.pory"
# 1659 "data/maps/LittlerootTown/scripts.pory"
	.string "RUNNING SHOES to run extra-fast!\p"
# 1660 "data/maps/LittlerootTown/scripts.pory"
# 944 "data/maps/LittlerootTown/scripts.pory"
# 1661 "data/maps/LittlerootTown/scripts.pory"
	.string "“Slip on these RUNNING SHOES and race\n"
# 1662 "data/maps/LittlerootTown/scripts.pory"
# 945 "data/maps/LittlerootTown/scripts.pory"
# 1663 "data/maps/LittlerootTown/scripts.pory"
	.string "in the great outdoors!”$"
# 1664 "data/maps/LittlerootTown/scripts.pory"
# 946 "data/maps/LittlerootTown/scripts.pory"
# 1665 "data/maps/LittlerootTown/scripts.pory"

# 1666 "data/maps/LittlerootTown/scripts.pory"
# 947 "data/maps/LittlerootTown/scripts.pory"
# 1667 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ComeHomeIfAnythingHappens:
# 1668 "data/maps/LittlerootTown/scripts.pory"
# 948 "data/maps/LittlerootTown/scripts.pory"
# 1669 "data/maps/LittlerootTown/scripts.pory"
	.string "… … … … … … … …\n"
# 1670 "data/maps/LittlerootTown/scripts.pory"
# 949 "data/maps/LittlerootTown/scripts.pory"
# 1671 "data/maps/LittlerootTown/scripts.pory"
	.string "… … … … … … … …\p"
# 1672 "data/maps/LittlerootTown/scripts.pory"
# 950 "data/maps/LittlerootTown/scripts.pory"
# 1673 "data/maps/LittlerootTown/scripts.pory"
	.string "To think that you have your very own\n"
# 1674 "data/maps/LittlerootTown/scripts.pory"
# 951 "data/maps/LittlerootTown/scripts.pory"
# 1675 "data/maps/LittlerootTown/scripts.pory"
	.string "POKéMON now…\l"
# 1676 "data/maps/LittlerootTown/scripts.pory"
# 952 "data/maps/LittlerootTown/scripts.pory"
# 1677 "data/maps/LittlerootTown/scripts.pory"
	.string "Your father will be overjoyed.\p"
# 1678 "data/maps/LittlerootTown/scripts.pory"
# 953 "data/maps/LittlerootTown/scripts.pory"
# 1679 "data/maps/LittlerootTown/scripts.pory"
	.string "…But please be careful.\n"
# 1680 "data/maps/LittlerootTown/scripts.pory"
# 954 "data/maps/LittlerootTown/scripts.pory"
# 1681 "data/maps/LittlerootTown/scripts.pory"
	.string "If anything happens, you can come home.\p"
# 1682 "data/maps/LittlerootTown/scripts.pory"
# 955 "data/maps/LittlerootTown/scripts.pory"
# 1683 "data/maps/LittlerootTown/scripts.pory"
	.string "Go on, go get them, honey!$"
# 1684 "data/maps/LittlerootTown/scripts.pory"
# 956 "data/maps/LittlerootTown/scripts.pory"
# 1685 "data/maps/LittlerootTown/scripts.pory"

# 1686 "data/maps/LittlerootTown/scripts.pory"
# 957 "data/maps/LittlerootTown/scripts.pory"
# 1687 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_CanUsePCToStoreItems:
# 1688 "data/maps/LittlerootTown/scripts.pory"
# 958 "data/maps/LittlerootTown/scripts.pory"
# 1689 "data/maps/LittlerootTown/scripts.pory"
	.string "If you use a PC, you can store items\n"
# 1690 "data/maps/LittlerootTown/scripts.pory"
# 959 "data/maps/LittlerootTown/scripts.pory"
# 1691 "data/maps/LittlerootTown/scripts.pory"
	.string "and POKéMON.\p"
# 1692 "data/maps/LittlerootTown/scripts.pory"
# 960 "data/maps/LittlerootTown/scripts.pory"
# 1693 "data/maps/LittlerootTown/scripts.pory"
	.string "The power of science is staggering!$"
# 1694 "data/maps/LittlerootTown/scripts.pory"
# 961 "data/maps/LittlerootTown/scripts.pory"
# 1695 "data/maps/LittlerootTown/scripts.pory"

# 1696 "data/maps/LittlerootTown/scripts.pory"
# 962 "data/maps/LittlerootTown/scripts.pory"
# 1697 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_BirchSpendsDaysInLab:
# 1698 "data/maps/LittlerootTown/scripts.pory"
# 963 "data/maps/LittlerootTown/scripts.pory"
# 1699 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH spends days in his LAB\n"
# 1700 "data/maps/LittlerootTown/scripts.pory"
# 964 "data/maps/LittlerootTown/scripts.pory"
# 1701 "data/maps/LittlerootTown/scripts.pory"
	.string "studying, then he'll suddenly go out in\l"
# 1702 "data/maps/LittlerootTown/scripts.pory"
# 965 "data/maps/LittlerootTown/scripts.pory"
# 1703 "data/maps/LittlerootTown/scripts.pory"
	.string "the wild to do more research…\p"
# 1704 "data/maps/LittlerootTown/scripts.pory"
# 966 "data/maps/LittlerootTown/scripts.pory"
# 1705 "data/maps/LittlerootTown/scripts.pory"
	.string "When does PROF. BIRCH spend time\n"
# 1706 "data/maps/LittlerootTown/scripts.pory"
# 967 "data/maps/LittlerootTown/scripts.pory"
# 1707 "data/maps/LittlerootTown/scripts.pory"
	.string "at home?$"
# 1708 "data/maps/LittlerootTown/scripts.pory"
# 968 "data/maps/LittlerootTown/scripts.pory"
# 1709 "data/maps/LittlerootTown/scripts.pory"

# 1710 "data/maps/LittlerootTown/scripts.pory"
# 969 "data/maps/LittlerootTown/scripts.pory"
# 1711 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut:
# 1712 "data/maps/LittlerootTown/scripts.pory"
# 970 "data/maps/LittlerootTown/scripts.pory"
# 1713 "data/maps/LittlerootTown/scripts.pory"
	.string "Um, um, um!\p"
# 1714 "data/maps/LittlerootTown/scripts.pory"
# 971 "data/maps/LittlerootTown/scripts.pory"
# 1715 "data/maps/LittlerootTown/scripts.pory"
	.string "If you go outside and go in the grass,\n"
# 1716 "data/maps/LittlerootTown/scripts.pory"
# 972 "data/maps/LittlerootTown/scripts.pory"
# 1717 "data/maps/LittlerootTown/scripts.pory"
	.string "wild POKéMON will jump out!$"
# 1718 "data/maps/LittlerootTown/scripts.pory"
# 973 "data/maps/LittlerootTown/scripts.pory"
# 1719 "data/maps/LittlerootTown/scripts.pory"

# 1720 "data/maps/LittlerootTown/scripts.pory"
# 974 "data/maps/LittlerootTown/scripts.pory"
# 1721 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_DangerousIfYouDontHavePokemon:
# 1722 "data/maps/LittlerootTown/scripts.pory"
# 975 "data/maps/LittlerootTown/scripts.pory"
# 1723 "data/maps/LittlerootTown/scripts.pory"
	.string "It's dangerous if you don't have\n"
# 1724 "data/maps/LittlerootTown/scripts.pory"
# 976 "data/maps/LittlerootTown/scripts.pory"
# 1725 "data/maps/LittlerootTown/scripts.pory"
	.string "your own POKéMON.$"
# 1726 "data/maps/LittlerootTown/scripts.pory"
# 977 "data/maps/LittlerootTown/scripts.pory"
# 1727 "data/maps/LittlerootTown/scripts.pory"

# 1728 "data/maps/LittlerootTown/scripts.pory"
# 978 "data/maps/LittlerootTown/scripts.pory"
# 1729 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_CanYouGoSeeWhatsHappening:
# 1730 "data/maps/LittlerootTown/scripts.pory"
# 979 "data/maps/LittlerootTown/scripts.pory"
# 1731 "data/maps/LittlerootTown/scripts.pory"
	.string "Um, hi!\p"
# 1732 "data/maps/LittlerootTown/scripts.pory"
# 980 "data/maps/LittlerootTown/scripts.pory"
# 1733 "data/maps/LittlerootTown/scripts.pory"
	.string "There are scary POKéMON outside!\n"
# 1734 "data/maps/LittlerootTown/scripts.pory"
# 981 "data/maps/LittlerootTown/scripts.pory"
# 1735 "data/maps/LittlerootTown/scripts.pory"
	.string "I can hear their cries!\p"
# 1736 "data/maps/LittlerootTown/scripts.pory"
# 982 "data/maps/LittlerootTown/scripts.pory"
# 1737 "data/maps/LittlerootTown/scripts.pory"
	.string "I want to go see what's going on,\n"
# 1738 "data/maps/LittlerootTown/scripts.pory"
# 983 "data/maps/LittlerootTown/scripts.pory"
# 1739 "data/maps/LittlerootTown/scripts.pory"
	.string "but I don't have any POKéMON…\p"
# 1740 "data/maps/LittlerootTown/scripts.pory"
# 984 "data/maps/LittlerootTown/scripts.pory"
# 1741 "data/maps/LittlerootTown/scripts.pory"
	.string "Can you go see what's happening\n"
# 1742 "data/maps/LittlerootTown/scripts.pory"
# 985 "data/maps/LittlerootTown/scripts.pory"
# 1743 "data/maps/LittlerootTown/scripts.pory"
	.string "for me?$"
# 1744 "data/maps/LittlerootTown/scripts.pory"
# 986 "data/maps/LittlerootTown/scripts.pory"
# 1745 "data/maps/LittlerootTown/scripts.pory"

# 1746 "data/maps/LittlerootTown/scripts.pory"
# 987 "data/maps/LittlerootTown/scripts.pory"
# 1747 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_YouSavedBirch:
# 1748 "data/maps/LittlerootTown/scripts.pory"
# 988 "data/maps/LittlerootTown/scripts.pory"
# 1749 "data/maps/LittlerootTown/scripts.pory"
	.string "You saved PROF. BIRCH!\n"
# 1750 "data/maps/LittlerootTown/scripts.pory"
# 989 "data/maps/LittlerootTown/scripts.pory"
# 1751 "data/maps/LittlerootTown/scripts.pory"
	.string "I'm so glad!$"
# 1752 "data/maps/LittlerootTown/scripts.pory"
# 990 "data/maps/LittlerootTown/scripts.pory"
# 1753 "data/maps/LittlerootTown/scripts.pory"

# 1754 "data/maps/LittlerootTown/scripts.pory"
# 991 "data/maps/LittlerootTown/scripts.pory"
# 1755 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_GoodLuckCatchingPokemon:
# 1756 "data/maps/LittlerootTown/scripts.pory"
# 992 "data/maps/LittlerootTown/scripts.pory"
# 1757 "data/maps/LittlerootTown/scripts.pory"
	.string "Are you going to catch POKéMON?\n"
# 1758 "data/maps/LittlerootTown/scripts.pory"
# 993 "data/maps/LittlerootTown/scripts.pory"
# 1759 "data/maps/LittlerootTown/scripts.pory"
	.string "Good luck!$"
# 1760 "data/maps/LittlerootTown/scripts.pory"
# 994 "data/maps/LittlerootTown/scripts.pory"
# 1761 "data/maps/LittlerootTown/scripts.pory"

# 1762 "data/maps/LittlerootTown/scripts.pory"
# 995 "data/maps/LittlerootTown/scripts.pory"
# 1763 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_TownSign:
# 1764 "data/maps/LittlerootTown/scripts.pory"
# 996 "data/maps/LittlerootTown/scripts.pory"
# 1765 "data/maps/LittlerootTown/scripts.pory"
	.string "LITTLEROOT TOWN\n"
# 1766 "data/maps/LittlerootTown/scripts.pory"
# 997 "data/maps/LittlerootTown/scripts.pory"
# 1767 "data/maps/LittlerootTown/scripts.pory"
	.string "“A town that can't be shaded any hue.”$"
# 1768 "data/maps/LittlerootTown/scripts.pory"
# 998 "data/maps/LittlerootTown/scripts.pory"
# 1769 "data/maps/LittlerootTown/scripts.pory"

# 1770 "data/maps/LittlerootTown/scripts.pory"
# 999 "data/maps/LittlerootTown/scripts.pory"
# 1771 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ProfBirchsLab:
# 1772 "data/maps/LittlerootTown/scripts.pory"
# 1000 "data/maps/LittlerootTown/scripts.pory"
# 1773 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH'S POKéMON LAB$"
# 1774 "data/maps/LittlerootTown/scripts.pory"
# 1001 "data/maps/LittlerootTown/scripts.pory"
# 1775 "data/maps/LittlerootTown/scripts.pory"

# 1776 "data/maps/LittlerootTown/scripts.pory"
# 1002 "data/maps/LittlerootTown/scripts.pory"
# 1777 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_PlayersHouse:
# 1778 "data/maps/LittlerootTown/scripts.pory"
# 1003 "data/maps/LittlerootTown/scripts.pory"
# 1779 "data/maps/LittlerootTown/scripts.pory"
	.string "{PLAYER}'s HOUSE$"
# 1780 "data/maps/LittlerootTown/scripts.pory"
# 1004 "data/maps/LittlerootTown/scripts.pory"
# 1781 "data/maps/LittlerootTown/scripts.pory"

# 1782 "data/maps/LittlerootTown/scripts.pory"
# 1005 "data/maps/LittlerootTown/scripts.pory"
# 1783 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ProfBirchsHouse:
# 1784 "data/maps/LittlerootTown/scripts.pory"
# 1006 "data/maps/LittlerootTown/scripts.pory"
# 1785 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH'S HOUSE$"
# 1786 "data/maps/LittlerootTown/scripts.pory"
# 1007 "data/maps/LittlerootTown/scripts.pory"
# 1787 "data/maps/LittlerootTown/scripts.pory"

# 1788 "data/maps/LittlerootTown/scripts.pory"
# 1008 "data/maps/LittlerootTown/scripts.pory"
# 1789 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_BirchSomethingToShowYouAtLab:
# 1790 "data/maps/LittlerootTown/scripts.pory"
# 1009 "data/maps/LittlerootTown/scripts.pory"
# 1791 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH: Well, well, {PLAYER}{KUN}!\n"
# 1792 "data/maps/LittlerootTown/scripts.pory"
# 1010 "data/maps/LittlerootTown/scripts.pory"
# 1793 "data/maps/LittlerootTown/scripts.pory"
	.string "That was good work out there!\p"
# 1794 "data/maps/LittlerootTown/scripts.pory"
# 1011 "data/maps/LittlerootTown/scripts.pory"
# 1795 "data/maps/LittlerootTown/scripts.pory"
	.string "I knew there was something special\n"
# 1796 "data/maps/LittlerootTown/scripts.pory"
# 1012 "data/maps/LittlerootTown/scripts.pory"
# 1797 "data/maps/LittlerootTown/scripts.pory"
	.string "about you when I first saw you,\l"
# 1798 "data/maps/LittlerootTown/scripts.pory"
# 1013 "data/maps/LittlerootTown/scripts.pory"
# 1799 "data/maps/LittlerootTown/scripts.pory"
	.string "but I never expected this.\p"
# 1800 "data/maps/LittlerootTown/scripts.pory"
# 1014 "data/maps/LittlerootTown/scripts.pory"
# 1801 "data/maps/LittlerootTown/scripts.pory"
	.string "Oh, yes. Do you still have the POKéDEX\n"
# 1802 "data/maps/LittlerootTown/scripts.pory"
# 1015 "data/maps/LittlerootTown/scripts.pory"
# 1803 "data/maps/LittlerootTown/scripts.pory"
	.string "I gave you?\p"
# 1804 "data/maps/LittlerootTown/scripts.pory"
# 1016 "data/maps/LittlerootTown/scripts.pory"
# 1805 "data/maps/LittlerootTown/scripts.pory"
	.string "I have something to show you.\n"
# 1806 "data/maps/LittlerootTown/scripts.pory"
# 1017 "data/maps/LittlerootTown/scripts.pory"
# 1807 "data/maps/LittlerootTown/scripts.pory"
	.string "Let's go to my LAB.$"

Littleroot_Techguy_Talk::
# 1840 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1841 "data/maps/LittlerootTown/scripts.pory"
	applymovement 3, Littleroot_Techguy_Talk_Movement_0
# 1842 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Techguy_Talk_Text_0
# 1844 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_Player_Mailbox::
# 1848 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1849 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Player_Mailbox_Text_0
# 1852 "data/maps/LittlerootTown/scripts.pory"
	playse MUS_OBTAIN_ITEM
# 1853 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Player_Mailbox_Text_1
# 1854 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_SYS_POKEDEX_GET
# 1855 "data/maps/LittlerootTown/scripts.pory"
	waitbuttonpress
# 1856 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Player_Mailbox_Text_2
# 1857 "data/maps/LittlerootTown/scripts.pory"
	playse MUS_OBTAIN_ITEM
# 1858 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Player_Mailbox_Text_3
# 1859 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_SYS_POKENAV_GET
# 1860 "data/maps/LittlerootTown/scripts.pory"
	waitbuttonpress
# 1861 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_Rival_Mailbox::
# 1865 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1866 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Rival_Mailbox_Text_0
# 1867 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_RivalHouseSign::
# 1871 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1872 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_RivalHouseSign_Text_0
# 1873 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_LabSign::
# 1877 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1878 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_LabSign_Text_0
# 1879 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_CemeterySign::
# 1883 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1884 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_CemeterySign_Text_0
# 1885 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


Littleroot_TownSign::
# 1889 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1890 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_TownSign_Text_0
# 1892 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


LittlerootTown_Trigger_Blocknopokes::
# 1896 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1897 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_Blocknopokes_Text_0
# 1898 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, NoGoRoute
# 1899 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 1900 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


# 1903 "data/maps/LittlerootTown/scripts.pory"
NoGoRoute:
# 1904 "data/maps/LittlerootTown/scripts.pory"
	walk_down
	step_end

LittlerootTown_Trigger_Blockgorival::
# 1908 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1909 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_Blockgorival_Text_0
# 1910 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, NoGoRoute2
# 1911 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 1912 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


# 1915 "data/maps/LittlerootTown/scripts.pory"
NoGoRoute2:
# 1916 "data/maps/LittlerootTown/scripts.pory"
	walk_down
	step_end

LittlerootTown_Trigger_NoEnterRival1::
# 1920 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1921 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_NoEnterRival1_Text_0
# 1923 "data/maps/LittlerootTown/scripts.pory"
	waitbuttonpress
# 1924 "data/maps/LittlerootTown/scripts.pory"
	call RivalShake
# 1925 "data/maps/LittlerootTown/scripts.pory"
	playse SE_BANG
# 1926 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_NoEnterRival1_Text_1
# 1927 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Trigger_NoEnterRival1_Text_2
# 1928 "data/maps/LittlerootTown/scripts.pory"
	waitmessage
# 1929 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, LittlerootTown_Trigger_NoEnterRival1_Movement_0
# 1930 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 1931 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return


RivalShake::
# 1935 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8004, 2
# 1936 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8005, 6
# 1937 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8006, 4
# 1938 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8007, 4
# 1939 "data/maps/LittlerootTown/scripts.pory"
	special ShakeCamera
	return


Littleroot_Idletalk_Oldman::
# 1944 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1945 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, Littleroot_Techguy_Talk_Movement_0
# 1946 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 0
	goto_if_eq Littleroot_Idletalk_Oldman_3
Littleroot_Idletalk_Oldman_1:
# 1951 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 0
	goto_if_eq Littleroot_Idletalk_Oldman_8
Littleroot_Idletalk_Oldman_6:
# 1953 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 3
	goto_if_eq Littleroot_Idletalk_Oldman_13
Littleroot_Idletalk_Oldman_11:
# 1955 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_LITTLEROOT_PHASE, 5
	goto_if_eq Littleroot_Idletalk_Oldman_17
Littleroot_Idletalk_Oldman_16:
# 1963 "data/maps/LittlerootTown/scripts.pory"
endfirstgreeting:
# 1964 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return

Littleroot_Idletalk_Oldman_2:
# 1947 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_0
# 1949 "data/maps/LittlerootTown/scripts.pory"
	setflag Birchafter1stgreeting
# 1950 "data/maps/LittlerootTown/scripts.pory"
	goto endfirstgreeting
	goto Littleroot_Idletalk_Oldman_1

Littleroot_Idletalk_Oldman_3:
# 1946 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset Birchafter1stgreeting, Littleroot_Idletalk_Oldman_2
	goto Littleroot_Idletalk_Oldman_1

Littleroot_Idletalk_Oldman_7:
# 1952 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_1
	goto Littleroot_Idletalk_Oldman_6

Littleroot_Idletalk_Oldman_8:
# 1951 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set Birchafter1stgreeting, Littleroot_Idletalk_Oldman_7
	goto Littleroot_Idletalk_Oldman_6

Littleroot_Idletalk_Oldman_12:
# 1954 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_2
	goto Littleroot_Idletalk_Oldman_11

Littleroot_Idletalk_Oldman_13:
# 1953 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set checkonrival, Littleroot_Idletalk_Oldman_12
	goto Littleroot_Idletalk_Oldman_11

Littleroot_Idletalk_Oldman_17:
# 1956 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 1957 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, MALE
	goto_if_eq Littleroot_Idletalk_Oldman_19
# 1961 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_4
	goto Littleroot_Idletalk_Oldman_16

Littleroot_Idletalk_Oldman_19:
# 1958 "data/maps/LittlerootTown/scripts.pory"
	msgbox Littleroot_Idletalk_Oldman_Text_3
	goto Littleroot_Idletalk_Oldman_16


LittlerootTown_Eventscript_Oldmanasking::
# 1968 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1969 "data/maps/LittlerootTown/scripts.pory"
	goto_if_unset checkonrival, LittlerootTown_Eventscript_Oldmanasking_2
# 1985 "data/maps/LittlerootTown/scripts.pory"
	setflag checkonrival
LittlerootTown_Eventscript_Oldmanasking_1:
# 1986 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return

LittlerootTown_Eventscript_Oldmanasking_2:
# 1971 "data/maps/LittlerootTown/scripts.pory"
	playse SE_PIN
# 1972 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, LittlerootTown_Eventscript_Oldmanasking_Movement_0
# 1974 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Eventscript_Oldmanasking_Text_0
# 1975 "data/maps/LittlerootTown/scripts.pory"
	waitbuttonpress
# 1976 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, LittlerootTown_Eventscript_Oldmanasking_Movement_1
# 1977 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, LittlerootTown_Eventscript_Oldmanasking_Movement_2
# 1978 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 1979 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Eventscript_Oldmanasking_Text_1
# 1982 "data/maps/LittlerootTown/scripts.pory"
	waitbuttonpress
# 1983 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, LittlerootTown_Eventscript_Oldmanasking_Movement_3
# 1984 "data/maps/LittlerootTown/scripts.pory"
	setflag checkonrival
	goto LittlerootTown_Eventscript_Oldmanasking_1


OldManThanks::
# 1990 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 1991 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_0
# 1992 "data/maps/LittlerootTown/scripts.pory"
	waitmessage
# 1993 "data/maps/LittlerootTown/scripts.pory"
	setobjectxy 1, 14, 16
# 1994 "data/maps/LittlerootTown/scripts.pory"
	applymovement 1, OldManThanks_Movement_0
# 1995 "data/maps/LittlerootTown/scripts.pory"
	waitmovement
# 1996 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_1
# 1999 "data/maps/LittlerootTown/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 2000 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_SYS_B_DASH
# 2001 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 2002 "data/maps/LittlerootTown/scripts.pory"
	compare VAR_RESULT, MALE
	goto_if_eq OldManThanks_2
# 2008 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_4
# 2009 "data/maps/LittlerootTown/scripts.pory"
	waitmessage
# 2010 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_5
OldManThanks_1:
# 2012 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_6
# 2014 "data/maps/LittlerootTown/scripts.pory"
	applymovement 4, OldManThanks_Movement_1
# 2015 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 2016 "data/maps/LittlerootTown/scripts.pory"
	removeobject 1
# 2017 "data/maps/LittlerootTown/scripts.pory"
	setobjectxy 1, 4, 17
# 2018 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_PHASE, 5
# 2020 "data/maps/LittlerootTown/scripts.pory"
	releaseall
	return

OldManThanks_2:
# 2003 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_2
# 2004 "data/maps/LittlerootTown/scripts.pory"
	waitmessage
# 2005 "data/maps/LittlerootTown/scripts.pory"
	msgbox OldManThanks_Text_3
	goto OldManThanks_1


# 1841 "data/maps/LittlerootTown/scripts.pory"
Littleroot_Techguy_Talk_Movement_0:
# 1841 "data/maps/LittlerootTown/scripts.pory"
	face_player
	step_end

# 1929 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Trigger_NoEnterRival1_Movement_0:
# 1929 "data/maps/LittlerootTown/scripts.pory"
	walk_down
	step_end

# 1972 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Eventscript_Oldmanasking_Movement_0:
# 1972 "data/maps/LittlerootTown/scripts.pory"
	emote_exclamation_mark
	step_end

# 1976 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Eventscript_Oldmanasking_Movement_1:
# 1976 "data/maps/LittlerootTown/scripts.pory"
	face_down
# 1976 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1976 "data/maps/LittlerootTown/scripts.pory"
	face_left
	step_end

# 1977 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Eventscript_Oldmanasking_Movement_2:
# 1977 "data/maps/LittlerootTown/scripts.pory"
	face_right
	step_end

# 1983 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Eventscript_Oldmanasking_Movement_3:
# 1983 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1983 "data/maps/LittlerootTown/scripts.pory"
	face_down
	step_end

# 1994 "data/maps/LittlerootTown/scripts.pory"
OldManThanks_Movement_0:
# 1994 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1994 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1994 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1994 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1994 "data/maps/LittlerootTown/scripts.pory"
	walk_up
	step_end

# 2014 "data/maps/LittlerootTown/scripts.pory"
OldManThanks_Movement_1:
# 2014 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2014 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2014 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2014 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2014 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2014 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 2014 "data/maps/LittlerootTown/scripts.pory"
	walk_down
	step_end

Littleroot_Techguy_Talk_Text_0:
# 1842 "data/maps/LittlerootTown/scripts.pory"
	.string "To think that one can alter Pokémon to\n"
	.string "make them safer...\p"
	.string "Technology is amazing, but it can be\n"
	.string "scary too.$"

Littleroot_Player_Mailbox_Text_0:
# 1849 "data/maps/LittlerootTown/scripts.pory"
	.string "There's a package inside the mailbox. A\n"
	.string "letter is attached to it.\p"
	.string "'For your invaluable service to the\n"
	.string "region, and the losses you suffered\l"
	.string "while performing it, please accept\l"
	.string "these tokens of gratitude, courtesy of\l"
	.string "Devon Corp.$"

Littleroot_Player_Mailbox_Text_1:
# 1853 "data/maps/LittlerootTown/scripts.pory"
	.string "Obtained the DEVONDEX!$"

Littleroot_Player_Mailbox_Text_2:
# 1856 "data/maps/LittlerootTown/scripts.pory"
	.string "There's something else in the package...$"

Littleroot_Player_Mailbox_Text_3:
# 1858 "data/maps/LittlerootTown/scripts.pory"
	.string "Obtained the DEVONAV!$"

Littleroot_Rival_Mailbox_Text_0:
# 1866 "data/maps/LittlerootTown/scripts.pory"
	.string "The mailbox is empty.$"

Littleroot_RivalHouseSign_Text_0:
# 1872 "data/maps/LittlerootTown/scripts.pory"
	.string "{RIVAL}'s house.$"

Littleroot_LabSign_Text_0:
# 1878 "data/maps/LittlerootTown/scripts.pory"
	.string "Littleroot's Pokémon Lab.$"

Littleroot_CemeterySign_Text_0:
# 1884 "data/maps/LittlerootTown/scripts.pory"
	.string "East - Littleroot Graveyard.$"

Littleroot_TownSign_Text_0:
# 1890 "data/maps/LittlerootTown/scripts.pory"
	.string "{COLOR LIGHT_GRAY}{SHADOW WHITE}'Littleroot Town\p"
	.string "A t-wn t-at -an't be sh--ed -ny -ue.'\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The elements have faded most of the\n"
	.string "writing.$"

LittlerootTown_Trigger_Blocknopokes_Text_0:
# 1897 "data/maps/LittlerootTown/scripts.pory"
	.string "I better go to the lab first...$"

LittlerootTown_Trigger_Blockgorival_Text_0:
# 1909 "data/maps/LittlerootTown/scripts.pory"
	.string "I should check on {RIVAL}.$"

LittlerootTown_Trigger_NoEnterRival1_Text_0:
# 1921 "data/maps/LittlerootTown/scripts.pory"
	.string "(You hear someone yelling inside...)\p"
	.string "DAMN YOU, KANTONIANS! You will NOT TAKE\n"
	.string "HOENN FROM US!\p"
	.string "Take this...$"

LittlerootTown_Trigger_NoEnterRival1_Text_1:
# 1926 "data/maps/LittlerootTown/scripts.pory"
	.string "ORYAAAAAAAAHH!$"

LittlerootTown_Trigger_NoEnterRival1_Text_2:
# 1927 "data/maps/LittlerootTown/scripts.pory"
	.string "(Whatever is happening inside, it does\n"
	.string "not look like a good time to visit...)$"

Littleroot_Idletalk_Oldman_Text_0:
# 1947 "data/maps/LittlerootTown/scripts.pory"
	.string "Ah, {PLAYER}! I'm so glad to see you.\p"
	.string "Please, go inside - Professor Balsam is\n"
	.string "waiting for you.\p"
	.string "I've retired, you see, and left her in\n"
	.string "charge of things.$"

Littleroot_Idletalk_Oldman_Text_1:
# 1952 "data/maps/LittlerootTown/scripts.pory"
	.string "Take some shelter, {PLAYER}. Balsam\n"
	.string "has many things she wants to talk\l"
	.string "about.$"

Littleroot_Idletalk_Oldman_Text_2:
# 1954 "data/maps/LittlerootTown/scripts.pory"
	.string "Have you paid {RIVAL} a visit yet?\n"
	.string "Please... old people need their sleep.$"

Littleroot_Idletalk_Oldman_Text_3:
# 1958 "data/maps/LittlerootTown/scripts.pory"
	.string "How are the new crutches treating you,\n"
	.string "{PLAYER}?\p"
	.string "The war left the terrain in a\n"
	.string "treacherous state, so please take care.$"

Littleroot_Idletalk_Oldman_Text_4:
# 1961 "data/maps/LittlerootTown/scripts.pory"
	.string "How is the new arm sling treating you,\n"
	.string "{PLAYER}?\p"
	.string "The war left the terrain in a\n"
	.string "treacherous state, so please take care.$"

LittlerootTown_Eventscript_Oldmanasking_Text_0:
# 1974 "data/maps/LittlerootTown/scripts.pory"
	.string "Ah, {PLAYER}, do you have a minute?$"

LittlerootTown_Eventscript_Oldmanasking_Text_1:
# 1979 "data/maps/LittlerootTown/scripts.pory"
	.string "Would you mind paying {RIVAL} a\n"
	.string "visit? They have been making quite a\l"
	.string "ruckus lately...\p"
	.string "It's as if they are reliving things that\n"
	.string "happened during the war.\p"
	.string "You went to the front together, didn't\n"
	.string "you? Perhaps you can calm them down.$"

OldManThanks_Text_0:
# 1991 "data/maps/LittlerootTown/scripts.pory"
	.string "Ah, {PLAYER}!$"

OldManThanks_Text_1:
# 1996 "data/maps/LittlerootTown/scripts.pory"
	.string "I saw {RIVAL} storming out like a\n"
	.string "frenzied Linoone! What got into them?\p"
	.string "Well, at least you got them to leave the\n"
	.string "house. That may do them some good.\p"
	.string "Thank you for checking on them. Here,\n"
	.string "take this as a form of thanks.$"

OldManThanks_Text_2:
# 2003 "data/maps/LittlerootTown/scripts.pory"
	.string "Obtained the Better Crutches!$"

OldManThanks_Text_3:
# 2005 "data/maps/LittlerootTown/scripts.pory"
	.string "These are some old crutches of mine.\p"
	.string "TI noticed yours are not in the best\n"
	.string "shape - these should help you move\l"
	.string "around better.$"

OldManThanks_Text_4:
# 2008 "data/maps/LittlerootTown/scripts.pory"
	.string "Obtained the Better Arm Sling!$"

OldManThanks_Text_5:
# 2010 "data/maps/LittlerootTown/scripts.pory"
	.string "This is an old arm sling of mine.\p"
	.string "TI noticed yours is not in the best\n"
	.string "shape - this one should secure your arm\l"
	.string "better, so you can move around more\l"
	.string "easily.$"

OldManThanks_Text_6:
# 2012 "data/maps/LittlerootTown/scripts.pory"
	.string "Well, take care on your trip to Oldale\n"
	.string "now!\p"
	.string "There's much hardship in these parts\n"
	.string "lately, and people are not as friendly\l"
	.string "as they used to.\p"
	.string "But have faith in your Pokémon, and you\n"
	.string "should be fine. Good bye!$"
